### ISSUE TITLE
Documentation error: Undefined options variable inside all vanilla JS inits

### ISSUE THREAD

**Issue by doughballs** [materializecss/materialize#1]
Materialize attracts many new developers - in many cases they are using code snippets direct from the documentation, and in every single example the code contains a breaking error. For instance, select:

https://materializecss.com/select.html#initialization

```
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, options);
  });

  // Or with jQuery

  $(document).ready(function(){
    $('select').formSelect();
  });
```

This results in:

> Uncaught ReferenceError: options is not defined

`options` is not only not defined, it is never mentioned, and it is not included in the jQuery init. Example [here](https://codepen.io/doughballs/pen/xxwByZM). Remove options (and the comma) and it works fine.

We can imagine a new developer, excited by the project, using it for the first time and then being tripped up not even by a typo of his own, but by the documentation! it is unacceptable really.

Two proposed fixes:

**1) Remove `options` from every affected page:**

```
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });
```

**2) Make reference to `options`:**

  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });

> To initialise with options (for instance, to set a classname on the select container), we first declare the options and then pass as the second argument:

```
var options = { 'classes': 'my-select-class' }
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, options);
});
```

Or even:

```
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, {});
  });

  // Or with jQuery

  $(document).ready(function(){
    $('select').formSelect({});
  });
```

Beyond this, to expand on the documentation, we should:

1) Create a new general page -  Initialisation. List all components with a checkbox to indicate if it needs initialising. A cheat sheet almost.

2) Expand on the init examples provided. It is not immediately obvious how to set options, and it should be. The framework should be as easy as possible to use.

**Affected components:**

https://materializecss.com/floating-action-button.html
https://materializecss.com/navbar.html (sidenav)

https://materializecss.com/carousel.html
https://materializecss.com/collapsible.html
https://materializecss.com/dropdown.html
https://materializecss.com/feature-discovery.html
https://materializecss.com/media.html
https://materializecss.com/modals.html
https://materializecss.com/parallax.html
https://materializecss.com/pushpin.html
https://materializecss.com/scrollspy.html
https://materializecss.com/sidenav.html
https://materializecss.com/tabs.html
https://materializecss.com/tooltips.html
https://materializecss.com/autocomplete.html
https://materializecss.com/chips.html
https://materializecss.com/pickers.html
https://materializecss.com/select.html

**Comment by DanielRuf** [comment]
What solution do you suggest @doughballs?

cc @materializecss/members

**Comment by mau5ken** [comment]
@DanielRuf @materializecss/members, I guess it would be great to have a slack channel for better communication for everyone.

**Comment by DanielRuf** [comment]
I'm not sure if slack is the best solution. I already have many and it is hard to keep track of the different channels and it is not very open as people have to get an invite afaik and there may be limitations to the size for free Slack channels.

Discord may be probably better as we have many big communities there and use it for a few projects. Otherwise Gitter would have been perfect but the materializecss org can not be used there as it is reserved by someone else.

I'm open to more suggestions and we should probably discuss this in a separate issue or use the GitHub Discussions: https://docs.github.com/en/github/building-a-strong-community/about-team-discussions

**Comment by mau5ken** [comment]
>   document.addEventListener('DOMContentLoaded', function() {
>     var elems = document.querySelectorAll('select');
>     var instances = M.FormSelect.init(elems, {});
>   });
> 
>   // Or with jQuery
> 
>   $(document).ready(function(){
>     $('select').formSelect({});
>   });

I really like this approach since many web sites are still using jquery and still having some support to this can be a plus to many other sites that are still using it. 
There many components that need to make that reference to `options` since it makes it more customizable for many users.

**Comment by doughballs** [comment]
> > document.addEventListener('DOMContentLoaded', function() {
> > var elems = document.querySelectorAll('select');
> > var instances = M.FormSelect.init(elems, {});
> > });
> > // Or with jQuery
> > $(document).ready(function(){
> > $('select').formSelect({});
> > });
> 
> I really like this approach since many web sites are still using jquery and still having some support to this can be a plus to many other sites that are still using it.
> There many components that need to make that reference to `options` since it makes it more customizable for many users.

Ok, so it was always the intention to include the jQuery method alongside it. We just need to decide what would be clearer for the user.

1. Leave options out altogether (but describe how to use in a new section, to be discussed)

`var instances = M.FormSelect.init(elems);
`
2. Declare options:
`var options = {}`
`var instances = M.FormSelect.init(elems, options);`

3. Use an empty object:

var instances = M.FormSelect.init(elems, {});

**Comment by doughballs** [comment]
> What solution do you suggest @doughballs?
> 
> cc @materializecss/members

Ok, here is a currently abandoned (how ironic!) attempt to build a more useful documentation site. This is unfiinishedm but you get the idea.

https://materialized.co.uk/components/select/

It was a broad intention to flesh out the current docs, rather than replicate and add - and totally based on my usage of the components. The idea was to find a core set of topics to cover for each component, in this case:

Overview (the theory behind the component, if any)
HTML (the html you need to copy and paste)
Javascript (could be initialisation instead, can be copied an pasted without triggering an error!)
Options (where we discus and show how to use options)
Methods (again, flesh out what methods are available - this is very poor on the current M site)
Issues (known issues and fixes)

In addition to this, if you look at the text-input page, I delve into styling. Most questions I answer are about styling and initialising.

**Comment by DanielRuf** [comment]
I think we can close this issue as https://github.com/materializecss/materialize/pull/19 is merged now.
