### ISSUE TITLE
How to handle website, packages,...

### ISSUE THREAD

**Issue by Huluti** [materializecss/materialize#10]
Hi!

I'm very interested by the reboot of the project because the agency where I work use this project to build a client interface.
But I've several questions regarding the new orgagnization.

How do you will manage releases, packages, and updates of the website because you don't have the rights I think?

Thank's in advance!

**Comment by wuda-io** [comment]
Good question, maybe we could create a github page and make a new (free) domain.
Propably this repo is only targeted for self compiling, I also wanted a newer version as CDN Link.

**Comment by DanielRuf** [comment]
The URLs will definitely differ and the commands to install this version as this is a fork.

I invited the original maintainers but they fidn't accept the invitation to this repo. So we will go our own route. The code and logic will be the same, docs too. Just with a new domain.

**Comment by DanielRuf** [comment]
The URLs will definitely differ and the commands to install this version as this is a fork.

I invited the original maintainers but they didn't accept the invitation to this repo. So we will go our own route. The code and logic will be the same, docs too. Just with a new domain.

**Comment by DanielRuf** [comment]
> Good question, maybe we could create a github page

Same like before. Also GitHub now allows custom path / folder for GitHub pages. No need for an extra repo. Docs / website should currently be in the same repo to stay in sync.

**Comment by Huluti** [comment]
Thank you for your responses. Why not thinking to a new name to go ahead and differentiate this fork?

**Comment by DanielRuf** [comment]
> Thank you for your responses. Why not thinking to a new name to go ahead and differentiate this fork? Because you can't have the exact same name I think.

The package name will be same but it will be under an org. The code and project are still materializecss, it is not a completely new project or fork in the sense of a feature fork.

**Comment by DanielRuf** [comment]
So no need to differentiate as we just pick up the work and continue where it has stopped.

**Comment by Huluti** [comment]
Yes I see but is it legal?

**Comment by DanielRuf** [comment]
What exactly do you mean? THe license is MIT and you can call it materializecss-next or similar. I see no issues regarding the naming.

**Comment by DanielRuf** [comment]
Closing as the questions are answered in my opinion.

**Comment by DanielRuf** [comment]
If there is anything unclear or unanswered, feel free to ask.
