### ISSUE TITLE
What is the difference between this and the original?

### ISSUE THREAD

**Issue by zdpuppet** [materializecss/materialize#104]
I used to use materialize years ago, but after seeing it's not getting support anymore, I start to use this fork. 

I'm really curious, what is the difference between this versus the original? Is it ever going to support Material Design 2?

Thank you!

**Comment by DanielRuf** [comment]
The current changes (as you can see at https://github.com/Dogfalo/materialize/compare/v1-dev...materializecss:v1-dev) are mostly bugfixes, security fixes and a few new features / enhancements.

Material Design 2 (is there a specifications for this?) is probably more like a materializecss v2 or v3 as this would be a completely new design language.

For now we are planning to release the current changes. See also https://github.com/materializecss/materialize/pull/101

Does this answer your question?

**Comment by ChildishGiant** [comment]
You can also see a changelog so far here: https://github.com/ChildishGiant/materialize/blob/v1.1.0-alpha/CHANGELOG.md
