### ISSUE TITLE
sidenav collapsible won't work within a separate JS file

### ISSUE THREAD

**Issue by christinavoudouris** [materializecss/materialize#106]
Hey, so I don't think this is a "how to" question, and I've tried gitter and stackoverflow, but I doubt I'll get an answer there. I'm using the Materialize sidenav by calling M.AutoInit() which works for me until I try putting it in a separate Javascript file. I've been able to set up my footer this way so I don't have repeat code, but this doesn't seem to work for the sidenav. The sidenav shows up but the collapsible part will not open.

I think the problem is it doesn't like calling the collapsible part from HTML that is being inserted dynamically. But I tried separating out the collapsible portion (using 2 different querySelectors) which did not work either. If I were to put at least part of the sidenav back into my HTML page, it would defeat the purpose of me doing this.

Haven't seen a repeat issue, and there are many folks on Stackoverflow using jQuery, so I'm wondering if this is a bug or if anyone has a solution. Thanks for looking at it!

```
document.addEventListener("DOMContentLoaded", () => {
  M.AutoInit()

  document.querySelector('header').insertAdjacentHTML('afterbegin',
    `<ul id="slide-out" class="sidenav sidenav-fixed">
      <li>
        <a
          href="https://www.greece.org/"
          target="_blank"
          rel="noopener noreferrer"
          >HEC Main</a
        >
      </li>
      <li>
        <a href="index.html" class="sidenav-close" rel="noopener noreferrer"
          >Home</a
        >
      </li>
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li>
            <button class="collapsible-header">
              History<i class="material-icons">arrow_drop_down</i>
            </button>
            <div class="collapsible-body">
              <ul class="sidenav-close">
                <li>
                  <a href="a-brief-review.html">A Brief Review</a>
                </li>
                <li><a href="philosophers-list.html">Philosophers List</a></li>
                <li><a href="philosophers-map.html">Philosophers Map</a></li>
                <li><a href="the-beginning.html">The Beginning</a></li>
                <li><a href="socrates.html">Socrates</a></li>
                <li><a href="plato.html">Plato</a></li>
                <li><a href="aristotle.html">Aristotle</a></li>
                <li>
                  <a href="bibliography-references.html"
                  >Bibliograpy / References</a
                  >
                </li>
              </ul>
            </div>
          </li>
        </ul>
      </li>
      <li class="divider"></li>
      <li>
        <a href="media.html" class="sidenav-close">Media</a>
      </li>
      <li>
        <a href="events.html" class="sidenav-close">Events</a>
      </li>
    </ul>`)

  document.querySelector('main').insertAdjacentHTML('afterend',
    `<footer class="page-footer">
        <div class="container">
          <p class="center-align">
            Philosophy is sponsored by
            <a
              href="https://www.greece.org"
              target="_blank"
            >
              www.greece.org 
            </a> | &copy; 2021 All Rights Reserved.
          </p>
        </div>
       <div class="fixed-action-btn">
        <a href="#top" class="btn-floating btn-large" style="background-color: silver;">
          <i class="large material-icons">arrow_upward</i>
        </a>
      </div>
    </footer>`)
})
```

**Comment by Smankusors** [comment]
hmm have you tried to import jQuery on your web?

Because if I remembered correctly, there's still some components on the materializecss that dependent to jQuery

**Comment by christinavoudouris** [comment]
I haven't tried it with jQuery but it turns out someone solved it for me on Stackoverflow. The M.AutoInit() has to come AFTER the code for the menu/collapsible. It only initializes one time so it wasn't able to catch what else was in there. My code is working now, so I'll close this. Hopefully this helps anyone else who's stuck.

**Comment by christinavoudouris** [comment]
By the way, I wouldn't mark this as a 'bug' so people don't assume that it is.
