### ISSUE TITLE
Swipe down to close bottom sheet modals

### ISSUE THREAD

**Issue by manuthecoder** [materializecss/materialize#109]
Hi, 
I was browsing through the material design docs, and when I was looking at bottom sheet modals. Usually in most apps, swiping down on a bottom sheet modal closes it. Could you please add this feature

https://material.io/components/sheets-bottom 
<img src="https://user-images.githubusercontent.com/77016441/115737571-1c6c6680-a341-11eb-95a6-b07b0984b021.png" width="300px">

**Comment by abhimaurya-dev** [comment]
Is this issue still exist?
