### ISSUE TITLE
Disable TravisCI

### ISSUE THREAD

**Issue by ChildishGiant** [materializecss/materialize#114]
All PRs currently have failing CI because of a broken Travis run that we no longer need as all the same tests are being ran through github actions. To remove this would be going to https://github.com/materializecss/materialize/settings/installations and uninstalling the Travis bot. After this we could remove the .travis.yml too

**Comment by DanielRuf** [comment]
> To remove this would be going to [materializecss/materialize/settings/installations](https://github.com/materializecss/materialize/settings/installations) and uninstalling the Travis bot.

Done.

**Comment by ChildishGiant** [comment]
All done now 😄
