### ISSUE TITLE
Option for custom sort in autocomplete

### ISSUE THREAD

**Issue by ChildishGiant** [materializecss/materialize#115]
Currently you can specify a custom "sortFunction" but this only controls which element wins in a 1v1 matchup, not how the matchups are made (Currently just uses array.sort). Adding this would allow end users to use libraries such as [fuse.js](https://fusejs.io/) to do more complex sorting and make results more accurate.

**Comment by ChildishGiant** [comment]
I have a functioning PR, just working on docs for it. This'd be a 2.0.0 feature as `sortFunction` has been renamed to `compareFunction` to avoid confusion and that would be a breaking change. I could always just keep it as sortFunction but having a `sortFunction` and `customSort` that do different things is rather confusing.

**Comment by wuda-io** [comment]
Can be done now with the new onSearch Function. #261
