### ISSUE TITLE
Whilst everyone seems to be moving away from JQuery...

### ISSUE THREAD

**Issue by Mashiane** [materializecss/materialize#117]
Hi there

I understand this is for the maintenance of Materialize and its enhancements. Just a question if you don't mind me asking. There is a seemingly trend of a complete movement away from JQuery whilst off course its still being used in most parts of the world.

Whilst I am not sure the volume of JQuery used internally by this framework, I am curious though if something like that has been considered without breaking working content. #JustAThought.

**Comment by wuda-io** [comment]
I dont know exactly what your question is...
In the Code there is used a Component which is a very small jQuery Replacement which enables the use of $() Selector.
Personally i dont wanna use jQuery at all and try to use document.querySelector()...

Do you mean we should remove this at all inside the Code or
do you mean we should drop suport for jQuery in the Project completely (like in the Docs the possiblity to use jQuery too)?

This is probably a discussion... Please clarifiy you request a little bit more.
Thanks.
