### ISSUE TITLE
Improvement Suggestion: Time Picker allow for typing input

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#118]
<img width="881" alt="Screenshot 2021-04-28 161810" src="https://user-images.githubusercontent.com/26590757/116484183-64a5f000-a83d-11eb-91ce-f726ff290643.png">

I noticed that the time picker only works by dragging and does not allow the user to type in an hour or minute. Dragging works well for bigger device screens and on numbers that are on the clock face like 15 and not in between clock face numbers like 17. This may be an issue for anyone using a small device where clock face numbers are very close together or for someone who has shaky hands and has accessibility problems.

I think this can be fixed by allowing the user to pick their time from the clock and to type it in directly if they need to.

**Comment by ChildishGiant** [comment]
Hmm this should be a fairly easy patch, might take a stab at it at some point 😄

**Comment by nh916** [comment]
Should we allow for keyboard input for the date picker as well

**Comment by Genne23v** [comment]
Can I contribute if this issue is still open?

**Comment by LoganTann** [comment]
Sure ! I'm assigning you then.
