### ISSUE TITLE
Feature Request: Image List drag to change the order of images

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#120]
I saw this on material design documentation and I thought it was the coolest thing ever. I saw that material design has a suggestion for images and media to have a behavior of allowing the user to drag them to change the order of any image when they are in edit mode. I was wondering if we wanted to implement something like this on our framework for when there is a gallery of images or many cards.

Here is the link to that page
https://material.io/components/image-lists#behavior

I am talking about the video with the caption of:
"You can drag an image list item to reorder it, but this interaction should be disabled if images are sorted or filtered."

**Comment by wuda-io** [comment]
Your idea sounds nice!
Maybe we should implement this as an example with many images in a Grid or somthing 🤔 

Do you mean a Drag and Drop / Re-Ordering function for existing Grids,
or do you mean a new Component like *ImageGrid*?

best greetz

**Comment by nh916** [comment]
I think an imageGrid would be cool, but I think we can more or less create that with our rows and columns. 

I think the reordering images by dragging them would be the coolest thing to be able to easily either by touchscreen press and hold or by mouse on desktop taking a picture and dragging it and putting it where you want easily. I think that would be really cool!

**Comment by wuda-io** [comment]
Hm... I think this is a too custom request. The Backend or a Client Setting needs to store the information of the order of cards/object, so i think it has nothing to do with Materialize as a Design Framework.

**Comment by ChildishGiant** [comment]
This could all be implemented client side, and is in the material spec so I wouldn't say definitely no, myself.
