### ISSUE TITLE
chore: cleanup stale branches

### ISSUE THREAD

**Issue by DanielRuf** [materializecss/materialize#121]
Currently we have many stale branches. I'm not sure if we still need some of them but I would suggest that we delete all obsolete branches.

Let's define which can be safely deleted.

https://github.com/materializecss/materialize/branches/stale

@materializecss/members

**Comment by warrenrodrigues** [comment]
I'm all for deleting obsolete branches. And something needs to be done about _master_ branch as well.
The [contributing](https://github.com/materializecss/materialize/blob/v1-dev/CONTRIBUTING.md) document refers to 'master', which can cause confusion, because the primary branch is _v1-dev_. Perhaps we can update the contributing document to reflect this (at least in an example below.)

**Comment by roiLeo** [comment]
Most of these branch have more than 600 commit behind, i think we can simply delete them.

**Comment by ChildishGiant** [comment]
Yea, I really think that calling master "v1-dev" is not good and should be tackled. Ideally master is stable and each version will get it's own branch that is then merged when stable.

**Comment by DanielRuf** [comment]
<img width="950" alt="Bildschirmfoto 2021-05-02 um 15 09 32" src="https://user-images.githubusercontent.com/827205/116814290-739be380-ab58-11eb-816e-b83025e69a84.png">

<img width="926" alt="Bildschirmfoto 2021-05-02 um 15 09 44" src="https://user-images.githubusercontent.com/827205/116814292-772f6a80-ab58-11eb-80a6-e41f0476532d.png">

I have gone ahead and delted all stale branches with no new commits and which are many commits behind.

These stale branches are left:

<img width="952" alt="Bildschirmfoto 2021-05-02 um 15 11 16" src="https://user-images.githubusercontent.com/827205/116814330-b2319e00-ab58-11eb-92e8-4e9799506698.png">

**Comment by DanielRuf** [comment]
<img width="950" alt="Bildschirmfoto 2021-05-02 um 15 09 32" src="https://user-images.githubusercontent.com/827205/116814290-739be380-ab58-11eb-816e-b83025e69a84.png">

<img width="926" alt="Bildschirmfoto 2021-05-02 um 15 09 44" src="https://user-images.githubusercontent.com/827205/116814292-772f6a80-ab58-11eb-80a6-e41f0476532d.png">

I have gone ahead and deleted all stale branches with no new commits and which are many commits behind.

These stale branches are left:

<img width="952" alt="Bildschirmfoto 2021-05-02 um 15 11 16" src="https://user-images.githubusercontent.com/827205/116814330-b2319e00-ab58-11eb-92e8-4e9799506698.png">

**Comment by ChildishGiant** [comment]
From a glance, the rollup branch has some changes that would fix #44 but obviously it was made by someone who's not on our project and with an end goal that's not entirely clear. I think unless we are actively aiming to introduce similar features or have the person on board we can probably nix them all.

**Comment by ChildishGiant** [comment]
Would love people to have a look at #186

**Comment by ChildishGiant** [comment]
All done!
