### ISSUE TITLE
Circular Gradient on waves ripple

### ISSUE THREAD

**Issue by manuthecoder** [materializecss/materialize#122]
In the new materialize CSS update, there's a small gradient on the waves ripple. 
Here's what I mean: 
![image](https://user-images.githubusercontent.com/77016441/116714095-3d106e00-a98a-11eb-93b9-21f6f967a78b.png)

In the previous version, it looked like this: 
![image](https://user-images.githubusercontent.com/77016441/116714304-79dc6500-a98a-11eb-8b4e-9ce2cfc1063e.png)

Notice the difference?
It becomes a bit more clear when you add the waves-effect class to a large element:
![image](https://user-images.githubusercontent.com/77016441/116715377-81503e00-a98b-11eb-8f34-c97a404a3a37.png)

This does not follow material design guidelines

![image](https://user-images.githubusercontent.com/77016441/116714993-274f7880-a98b-11eb-988a-3d30176502ba.png)

Video example: https://fast.wistia.net/embed/iframe/gzr1k22mil?videoFoam=true

**Comment by wuda-io** [comment]
What... Thats really a strange Behavoir.
Maybe thats due to changes in the waves componenent or some Css changes. Does anyone knows why this is? What has changed?
Best regards

**Comment by ChildishGiant** [comment]
We updated waves.js with 1.1.0 (https://github.com/materializecss/materialize/commit/fce7b8be7b94cb8d0792f560694aa72cc12abcdb) so this will be due to that. The [original project](https://github.com/fians/Waves) seems fairly dead so we may have to patch this ourselves.

**Comment by wuda-io** [comment]
Ok, thanks Allie for pointing that out.
I look in the Project and its fairly small, so it makes sense as you said to maintain the code ourselves.
I looked in the project in the sass folder an i think i already found the gradient which causes this behavoir.
As i tested it on their project-page, it does not ooks too bad to me, so I would suggest that we should discuss here if we should change it according to the google specs? What are the benefits of changing the design? Is it "faster" to use no gradient?
Thanks

**Comment by ChildishGiant** [comment]
https://github.com/materializecss/materialize/blob/a088f1480879fcb5da1b6daab3512821258e259e/sass/components/_waves.scss#L49 basically this should be a hard gradient, not smoothed over

**Comment by wuda-io** [comment]
Thats awesome! Thank you 🙏

**Comment by ChildishGiant** [comment]
Not really sure why but it also sticks around after using until the user clicks off (using the undocumented btn-flat to make it clear)

https://user-images.githubusercontent.com/13716824/117042254-a209f200-ad03-11eb-9a42-c833a44cb121.mp4

**Comment by DanielRuf** [comment]
Hm, maybe some focus or class related issue?

**Comment by ManuTheCoder** [comment]
Also, could there be a class for a centered ripple?

**Comment by wuda-io** [comment]
new implementation in [v2-dev](https://github.com/materializecss/materialize/tree/v2-dev)
