### ISSUE TITLE
Dynamically adding Selects and initiliazing them will create non-clickable Select duplicates

### ISSUE THREAD

**Issue by JoaoBM1** [materializecss/materialize#124]
## Expected Behavior
When reinitializing Selects, the old Selects should be deleted and replaced by the new ones.

## Current Behavior
When reinitializing, the current Select becomes unclickable and a new, working Select is created under the first.

## Steps to Reproduce (for bugs)
Code pen:  https://codepen.io/JoaoBM/pen/GRrVdXP

## Context
I am trying to dynamically add Selects. When reinitializing, the original Select becomes unclickable and unusable and a new Select that works properly is created below.

## Your Environment
* Version used: Materialize 1.0.0
* Browser Name and version: Firefox 88.0 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Home 64 bit

**Comment by ChildishGiant** [comment]
I imagine it won't make a difference but have you tried on 1.1.0-alpha?

**Comment by JoaoBM1** [comment]
> 
> 
> I imagine it won't make a difference but have you tried on 1.1.0-alpha?

Hi! Thanks for the input! Unfortunately, the bug still occurs. Is it something tricky I am not seeing or is it a bug with no work around?

**Comment by Smankusors** [comment]
I think, you need to avoid using `innerHTML`, because the internal state of the select elements will be lost.

Instead of using `innerHTML`, you can use `insertAdjacentHTML`. For example :

```
form.insertAdjacentHTML('beforeend', content);
```

IMO, this is not the bug from materializecss.

[reference here](https://stackoverflow.com/questions/37448622/why-can-event-listeners-stop-working-after-using-element-innerhtml)

**Comment by JoaoBM1** [comment]
> 
> 
> I think, you need to avoid using `innerHTML`, because the internal state of the select elements will be lost.
> 
> Instead of using `innerHTML`, you can use `insertAdjacentHTML`. For example :
> 
> ```
> form.insertAdjacentHTML('beforeend', content);
> ```
> 
> IMO, this is not the bug from materializecss.
> 
> [reference here](https://stackoverflow.com/questions/37448622/why-can-event-listeners-stop-working-after-using-element-innerhtml)

Hi! I had been trying to solve this issue for a couple of days and I wanted to thank you for helping me solve it. I'll start avoiding innerHTML and replace it with insertAdjacentHTML. Thanks for the tip.
