### ISSUE TITLE
Feature Improvement: Allow for Swiping on Slider

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#125]
I was looking through materialize and I was trying out the slider and to my surprise I was not able to swipe on the slides to change slides and I was only able to click on the bottom dots to switch between slides. 

This is not a huge problem by any means and from accessibility stand point it is fine, as I imagine everyone can either click on the dots or navigate to them through tab and click on them that way.

However, I believe we should add a functionality to allow users to change slides by swiping because the way the slides are presented to the user it gives the impression and the affordance that the slides are something to interact with and the user can swipe between different slides. It would be a bit odd if the user sees such affordance and gets such impression and when s/he swipes they see nothing happens. It almost becomes a bit frustrating and makes the site feel undeveloped and broken.

![image](https://user-images.githubusercontent.com/26590757/116950361-a073f780-ac39-11eb-8b10-528cb73f6046.png)

![image](https://user-images.githubusercontent.com/26590757/116950440-da44fe00-ac39-11eb-8975-86896d823fe8.png)

**Comment by roiLeo** [comment]
You can already create a swipeable fullscreen slider by using [carousel component](https://materializecss.github.io/materialize/carousel.html)

**Comment by wuda-io** [comment]
I am able to swipe on Android Chrome and Firefox.
Althoug it laggs on mobile.. 
What Browser are you using? @nh916

**Comment by nh916** [comment]
I was using brave browser
