### ISSUE TITLE
Feature Request: Materialize audio player

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#126]
I was thinking that we already have a materialize style video player and it would be soo cool to have a audio player or materialize media player.

I think something like this says materialize to me:

![image](https://user-images.githubusercontent.com/26590757/116950592-593a3680-ac3a-11eb-9646-51da55df330a.png)

I think that is good and basic and has good accessibility for everyone and has UX and UI.

Something more fun like this seems even cooler to me but I don't know if others would like it too:

![image](https://user-images.githubusercontent.com/26590757/116950651-871f7b00-ac3a-11eb-8802-42f1a4d53ed9.png)

![image](https://user-images.githubusercontent.com/26590757/116950662-8be42f00-ac3a-11eb-8626-e50461644b65.png)

or if we come up with other cool media player styles that would be awesome too!

This is not pressing issue by any means, but I just thought it might be really cool!

**Comment by roiLeo** [comment]
The [<audio> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) might be a solution.

**Comment by ChildishGiant** [comment]
What are you suggesting? An audio component that's styled by us? As far as I know the audio element can't have custom styles so we'd need to make our own one. This seems out of the scope of the project.

**Comment by DanielRuf** [comment]
I'm not sure if this is part of the Material Design specification.

**Comment by DanielRuf** [comment]
> This seems out of the scope of the project.

I agree with this.

**Comment by ray007** [comment]
Maybe as adapter for existing audio/video libs?

**Comment by wuda-io** [comment]
I think we can close this. This wont be implemented in the near future and has to be created individually.
