### ISSUE TITLE
Invalid link for Sass version

### ISSUE THREAD

**Issue by lelabo-m** [materializecss/materialize#127]
The `SASS` button on the documentation point to the following URL: `https://github.com/materializecss/materialize/releases/download/1.1.0-alpha/materialize-src-v1.1.0-alpha.zip`.

## Expected Behavior

I was expecting to download a zip with the following structure:
```
  |--js/
  |  |--bin/
  |
  |--scss/
  |  |--materialize.scss
  |  |--components/
  ```

## Current Behavior

This file does not exist, or is now missing.
I could download the entire repository, clean it, but I don't know how to build the `materialize.js` and `materialize.min.js`.

## Possible Solution
Maybe something is missing from the current release flow.
I would be nice to have this version available, as it was supported before and help people getting started quickly with materializecss.

## Steps to Reproduce (for bugs)

Click the SASS `SOURCE` button.

## Context
I am new to web development (I come from the back-end side) and I was trying to get the sass version of materialize theme.

## Your Environment
* Version used: https://materializecss.github.io/materialize/getting-started.html
* Browser Name and version: Chrome (90.0.4430.93 - Official Build - 64-bit)
* Operating System and version (desktop or mobile): Windows 10 (Build 21370.1)

**Comment by CypherpunkSamurai** [comment]
Hello @DanielRuf I think this issue has been resolved long time ago.

Getting started page download looks fine as of now:
https://materializeweb.com/getting-started.html 

Can / should close this issue?

**Comment by DanielRuf** [comment]
Thanks for letting me know, closing.
