### ISSUE TITLE
Where can I get compiled builds

### ISSUE THREAD

**Issue by RandomUnknown** [materializecss/materialize#13]
Thanks for the great work continuing this project, I've looked through some of the latest gits and they fix some problems I have been having but I can't seem to be able to compile this version correctly, is there builds on Travis? If so I could not find them, is there anywhere I can download the current build? Thanks!

**Comment by Smankusors** [comment]
unfortunately the current build is currently not available yet...

btw, what errors you get when compiling materialize?

**Comment by Wouter8** [comment]
When are you planning to release a new version? I'm still waiting on the select fix. https://github.com/Dogfalo/materialize/issues/6464

**Comment by DanielRuf** [comment]
Probably when we find some free time to do that.

**Comment by ChildishGiant** [comment]
We could do nightly builds pretty easily with github actions, I could do that if wanted.

**Comment by DanielRuf** [comment]
> We could do nightly builds pretty easily with github actions, I could do that if wanted.

Do you mean on npmjs? Because this and the CDNs are the main source for consumers.
I'm not sure if nightly builds make so much sense in general as there are not that many changes per day.

**Comment by ChildishGiant** [comment]
By nightly I just mean with each change to master. The builds could be here as releases or just at a link (still hosted by github) so not to spam the releases with every commit

**Comment by DanielRuf** [comment]
Hm, I'm not sure. I don't see much benefit in there so far.
I would also prefer semantic-releases or similar.

**Comment by wuda-io** [comment]
When can i use the newest version as cdn?

**Comment by DanielRuf** [comment]
> When can i use the newest version as cdn?

When it is released on npmjs. But I recommend to download the files then and host them yourself - especially regarding GDPR and CDNs can also have outages.

**Comment by wuda-io** [comment]
Ok is there any time shedule? I prefer weekly releases for dev version so everyone and I can easily use the latest release and we can improve faster as a team.

So whats the Plan? I want this to get started. Thanks

**Comment by DanielRuf** [comment]
> Ok is there any time shedule?

No, as I already wrote when I find some time to plan and do this.

> I prefer weekly releases for dev version so everyone and I can easily use the latest release and we can improve faster as a team.

Please see my previous comments. semantic-releases makes more sense (but not daily or weekly, there is no specific time-interval that I would use).

**Comment by assistcontrol** [comment]
It might make sense to publish 1.0.0 to npm and cdnjs. Even though it's identical to the upstream release, it'd allow people to get the deps set now in `package.json` and simply `yarn upgrade` when you do cut new releases.

I totally understand the time issue, but I'm putting this out there as a lower-hanging fruit.

**Comment by Smankusors** [comment]
@DanielRuf Sorry I haven't tried to build this........ but how to build materialize? Is `grunt monitor` will also compile the framework? Or is there a specific command to compile/build it? 😕

**Comment by DanielRuf** [comment]
> It might make sense to publish 1.0.0 to npm and cdnjs

It already is as already mentioned ;-)

https://www.npmjs.com/package/@materializecss/materialize

**Comment by DanielRuf** [comment]
> @DanielRuf Sorry I haven't tried to build this........ but how to build materialize? Is `grunt monitor` will also compile the framework? Or is there a specific command to compile/build it? confused

`grunt monitor` watches only for changes and then compiles.
There are 3 grunt tasks for compiling the files:
https://github.com/materializecss/materialize/blob/v1-dev/Gruntfile.js#L660-L662

We might have to extend https://github.com/materializecss/materialize/blob/v1-dev/CONTRIBUTING.md

**Comment by Smankusors** [comment]
update: it's mentioned on the travis file that it's using Node.js v6.10

https://github.com/materializecss/materialize/blob/875719d9874503af266d372fc6c0db37e488382b/.travis.yml#L2-L3

I think this is what OP encountered, it's failing to run `npm install` because the Node.js that OP uses might be too new. I tried with Node.js v14.11.0 and it's somewhat failing at building `node-sass`.

So I tried starting from v8 and v9. They can still runs fine. But when I tried with Node.js v10.22.1, it's failing when trying to build `node-sass`. So I suppose this needs to be written in the documentation that it's required at least v6, but at most v9? But those Node.js versions already EOL. So...... maybe updating the `node-sass` version number will solve this issue?

**Comment by DanielRuf** [comment]
You have to upgrade node-sass for node 14, correct.

That's on the roadmap too.

**Comment by DanielRuf** [comment]
> You have to upgrade node-sass for node 14, correct.
> 
> That's on the roadmap too.

@nekonenene already did this in some PRs =)

**Comment by newpen** [comment]
Hey it has been quite a long time, any updates on the build?
I think at least some nightly builds should be released as the old version has some bugs that really need to be fixed asap. 
We may need to switch to other libraries if we have to wait indefinitely.

**Comment by DanielRuf** [comment]
So far no updates as you can see. A new release is planned for this year.

**Comment by newpen** [comment]
> So far no updates as you can see. A new release is planned for this year.

Any updates on the release date? Thanks.

**Comment by Smankusors** [comment]
> Any updates on the release date? Thanks.

I think with PR #63, we can first try with nightly builds. See if there's any problem with the nightly one, before moving to stable release.

**Comment by ChildishGiant** [comment]
That's been merged so you can now get the latest nightly build here: https://nightly.link/materializecss/materialize/workflows/nightly/dev/build.zip
