### ISSUE TITLE
Create/Integrate Stepper Component

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#130]
I recently saw that some guy developed a Stepper Component as AddOn for Materialize.
I think it would be cool for Version 2.0 to create a new Component which only displays the Steps without the content stuff. This is awesome to visualize a Process on a Card and enhanced User Experience.

Here is the Project:
https://kinark.github.io/Materialize-stepper/

It would be mainly CSS and a bit JS for jumping to the Steps or Events on clicking certain Steps. There also should be the possibility to disable Steps.

Maybe we can integrate most of the already existing Code, since it is also MIT Licence.
Maybe I can try to build a Draft soon.
What do you think?

**Comment by roiLeo** [comment]
I've been using it for a while and it's really great, it need some minor tweak and polyfill to work with IE.
I agree that it should be included in a future version as a new component.
See [#3777](https://github.com/Dogfalo/materialize/issues/3770) for reference.

**Comment by wuda-io** [comment]
I suggest using [collections](https://materializeweb.com/collections.html) for vertical steps.
And the [preloader](https://materializeweb.com/preloader.html) for horizontal steps or progress.
But this is out of scope for now.
