### ISSUE TITLE
Feature: Update to work again with meteor 2.x

### ISSUE THREAD

**Issue by TomFreudenberg** [materializecss/materialize#131]
We start using latest materializecss:materialize (v1-dev/v1-1-stable) for meteor.js in conjunction with react-materialize.

It is not working anymore out of the box for meteor 2.x release and must be re-worked, also in replacing fourseven:sass.

We are working on two branches to make that compatible for meteor 2.x and new (DART) sass tool.

If interested or have comments please checkout:

* https://github.com/4commerce-technologies-AG/materialize/tree/meteor-2.x
* https://github.com/4commerce-technologies-AG/react-materialize/tree/meteor-2.x
* https://sass-lang.com/

Outdated:

* https://github.com/Meteor-Community-Packages/meteor-scss

**Comment by ChildishGiant** [comment]
What exactly would need changing? These two branches seem to have just changed the git repo it points to, no?

**Comment by TomFreudenberg** [comment]
Hi Allie - its work in progress - I just wanted to let anybody know - someone is working on.

The package.js  needs to get a re-work and there must be a builder package for meteor to replace fourseven:sass.

For the first shot I changed the repo links to make a installation via `meteor add` and `npm install` possible without getting unusable dependencies.

I will update this issue and send in a PR when finished.

**Comment by wuda-io** [comment]
Is this still relevant? I saw the linked projects, and the last commit was 2 years ago.
I will close this here. Feel free to reopen if something changed. Thanks.
