### ISSUE TITLE
Options in select element still highlighted after unselecting it.

### ISSUE THREAD

**Issue by Singha360** [materializecss/materialize#133]
![Peek 2021-05-05 20-58](https://user-images.githubusercontent.com/35334787/117227375-aeb24700-ade4-11eb-9dd1-70c49f77219a.gif)

**Comment by DanielRuf** [comment]
Can be reproduced on https://materializecss.github.io/materialize/select.html

It seems the active class is not removed.

<img width="874" alt="Bildschirmfoto 2021-05-06 um 19 44 59" src="https://user-images.githubusercontent.com/827205/117342506-9d7c3f80-aea3-11eb-9e6e-36f8d925ef11.png">

The issue does not exist on https://materializecss.com/select.html
One of the commits that is not in the used version there and that might be relevant is https://github.com/materializecss/materialize/commit/c0da34049deec36efbd4681f73b3446e92918ca8#diff-f23639ab50ee01de087486418e0e652284a0a5e6d05cc0698a6e85521bb46a38

At least I think so.

Maybe someone can do a `git bisect`:

```
git bisect start
git bisect good v1.0.0
git bisect bad v1.1.0-alpha
...
git bisect bad/good
```

**Comment by DanielRuf** [comment]
@materializecss/members

**Comment by bugy** [comment]
I think it was broken here:
https://github.com/materializecss/materialize/pull/98

After I reverted the changes in dropdown.js locally, it worked fine for me

@ChildishGiant

**Comment by DanielRuf** [comment]
Ah, that makes sense as it uses the dropdown component.

I think we should try to do at least one review per PR in the future =)

**Comment by ChildishGiant** [comment]
I'm on holiday right now but will take a look at patching it 😅 Does look like I broke it, but this is what alphas are for 😉

**Comment by DanielRuf** [comment]
> Does look like I broke it, but this is what alphas are for 😉

Exactly =)

> I'm on holiday right now but will take a look at patching it 😅

No hurry, enjoy your holiday =)
