### ISSUE TITLE
Update normalize.css

### ISSUE THREAD

**Issue by WebVPF** [materializecss/materialize#137]
Current version in materialize v7.0.0 https://github.com/materializecss/materialize/blob/v1-dev/sass/components/_normalize.scss

The author has the latest version 8.0.1 https://github.com/necolas/normalize.css/releases

Latest version file: https://github.com/necolas/normalize.css/blob/master/normalize.css

**Comment by LoganTann** [comment]
> The better move would be using the npm package over just having it locally. We might want to look into changing to another package anyway: [necolas/normalize.css#856 (comment)](https://github.com/necolas/normalize.css/issues/856#issuecomment-830704976)

what are your thought about switching to [modern-normalize](https://github.com/sindresorhus/modern-normalize) (as suggested in [necolas/normalize.css#856 (comment)](https://github.com/necolas/normalize.css/issues/856#issuecomment-830704976)) for 1.2.0 @materializecss/members ?
It's normalize, but improved and used by tailwind.

**Comment by DanielRuf** [comment]
> what are your thought about switching to [modern-normalize](https://github.com/sindresorhus/modern-normalize) (as suggested in [necolas/normalize.css#856 (comment)](https://github.com/necolas/normalize.css/issues/856#issuecomment-830704976)) for 1.2.0 @materializecss/members ?
> It's normalize, but improved and used by tailwind.

Generally a good idea, but since we plan v2 after v1.1 (https://github.com/materializecss/materialize/releases) we can do it there. This will include upgrade of all relevant parts.

We already have a `v2-dev` branch which will become the new default branch then.

**Comment by LoganTann** [comment]
> How to assess if it is backwards compatible?

Hi @RamonvdW,
a normalizer is a small CSS file that overrides default styling of elements (which are different across browsers) in order to provide a better cross-browser consistency.
If the unit tests are well written and passes correctly, we can assume that switching to modern-normalize is indeed backward compatible.
