### ISSUE TITLE
Time to stop worrying about ie support?

### ISSUE THREAD

**Issue by ChildishGiant** [materializecss/materialize#14]
Several changes (such as passive event receivers) were recently blocked to keep compat with ie without the use of polyfills. [Microsoft just announced they're dropping IE](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666), maybe it's about time we do the same?

**Comment by Smankusors** [comment]
IMO, if we dropping IE, then we should increase the major number, for example to v2.x

**Comment by ray007** [comment]
As much as I do not like IE, end of support from Microsoft is a year from now, so maybe continue a `1.x` line for IE until then?

**Comment by ChildishGiant** [comment]
We're all agreed on dropping IE for 2.0, right?
![image](https://user-images.githubusercontent.com/13716824/117880761-5f668d80-b2a0-11eb-9d91-42530b4afef0.png)
