### ISSUE TITLE
Materialize and Material You

### ISSUE THREAD

**Issue by shenef** [materializecss/materialize#145]
Recently Google announced Material You. https://material.io/blog/announcing-material-you
This is not meant to be a feature request for materialize to switch to a new Material You design language, rather it's meant to be a discussion thread to ask and answer questions that will arise as Google unveils new information around Material You.
For example:
- Should materialize switch to the Material You design language?
- How applicable is it to what materialize is trying to accomplish and to webdesign in general?
- Is it even viable to add Material You features and parts of the design or would that require big changes to underlying structures?

**Comment by ChildishGiant** [comment]
I imagine that Google will implement this themselves using flutter. It seems a key part of this is that settings are carried from one app to another, something I imagine we won't be able to tap into.

**Comment by wuda-io** [comment]
This is out of Scope of this Project and can not be realized across different domains.
