### ISSUE TITLE
Rounding artefacts with dark table row

### ISSUE THREAD

**Issue by RamonvdW** [materializecss/materialize#146]
global.scss contain this style:

```
td, th{
  padding: 15px 5px;
  display: table-cell;
  text-align: left;
  vertical-align: middle;
  border-radius: 2px;  // this causes issues
}
```

The border radius is not visible when the table cell background color is identical to all cells around it.
When highlighting a table row by changing the background color, the area between each adjacent td in that row shows the rounding effects: a few white pixels on every corner.

Material design does not specify any rounding on table cells.
See https://material.io/archive/guidelines/components/data-tables.html

Snippet to reproduce the issue:
```
<table class="white">
   <tr><td>First</td><td>Second</td><td>Third</td></tr>
   <tr class="darkgreen"><td>First</td><td>Second</td><td>Third</td></tr>
   <tr><td>First</td><td>Second</td><td>Third</td></tr>
<table>
```

Example:
![image](https://user-images.githubusercontent.com/50547870/120900692-83ff1c80-c636-11eb-94e5-644327c05353.png)

I have not found any component in materializecss where the border rounding of td or th elements is useful. I might have missed one - please reply and let me know.

Proposed solution: change line marked above from 2px to 0.

Environment:
- Visible with Chrome version 91.0 (and many versions back) on Debian 10 and Windows 10
- Not visible with Firefox 78.10

**Comment by Smankusors** [comment]
Honestly, I'm just realized the app that I have developed for 2 years have a CSS override like this.

```
td,th {
	border-radius: 0 !important;
}
```

Stupid past me 🤦, there's no documentation why this CSS rule exist. Perhaps this artefact is the reason...

---

Looking on the commit from 7 years ago, I don't think there's any reason removing border-radius would cause any UI problem. Feel free to create a PR to fix this issue. The line you looking is here :

https://github.com/materializecss/materialize/blob/eb04cbfff7b523ee76167af1e2401c3d95762c8c/sass/components/_global.scss#L446

---

On the other hand, there's `border-radius: 0` if you use `striped` class. Perhaps if line above removed, these lines are also safe to removed?

https://github.com/materializecss/materialize/blob/eb04cbfff7b523ee76167af1e2401c3d95762c8c/sass/components/_global.scss#L417-L419

What do you think about this? Safe to remove both of these rules? @materializecss/members

**Comment by roiLeo** [comment]
I can't find the purpose of using border-radius in table cells, I think we can safely remove it.
