### ISSUE TITLE
Deprecation Warning in scss files

### ISSUE THREAD

**Issue by roiLeo** [materializecss/materialize#147]
When building css files with Dart Sass it results with many warning : 
```
Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($gutter-width, 3)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

## Possible Solution
Use Recommendation: math.div()
see [slash-div](https://sass-lang.com/documentation/breaking-changes/slash-div) for references

**Comment by prafullaranjan** [comment]
## Quick Fix
`npm i -g sass-migrator`

`sass-migrator division node_modules/___YOUR_FRAMEWORK_PATH/scss/*.scss
`

Repeat this step for each of the files showing error using asterisks. This is temporary fix, changes will get removed if you update the framework else it's fine to use as of now.
