### ISSUE TITLE
autocomplete with materializecss + jquery tokeninput

### ISSUE THREAD

**Issue by scabros** [materializecss/materialize#15]
hi, i am a web developer and i used materializecss for a couple of projects in the past. 

in the last project i integrated a (now archived) jquery plugin for autocomplete with ajax and tokens with the chips from materializecss (https://github.com/loopj/jquery-tokeninput)

i think that it's a better alternative to the autocomplete functionality offered by materializecss right now, it has ajax loading, prepopulate, adding tokens on the fly, and other triggers, but i dont think i have the technical level to contribute code to a open source project. 

anyway, if you thinks it's usable, i created a gist with the two "hacked" files (jquery.tokeninput.js + token-input.css) and an example so you can merge it on the project or use it freely as you see fit.

GIF DEMO: https://imgur.com/gallery/CqfATAb
GIST: https://gist.github.com/scabros/36ec20611166bfe642a24c39fc84bff8

**Comment by DanielRuf** [comment]
Afaik materialize stricly follows the Material Design specification by Google. So we have to check there if this functionality is in there.

**Comment by scabros** [comment]
ok, i understand. i was referring as a replacement for this functionality: https://materializecss.com/autocomplete.html
but the one i sent uses chips as "tokens".

**Comment by DanielRuf** [comment]
I took a closer look at the code / repo. The code seems to be from 2014 (the repository is also archived), there are many open issues there (too many to check and there are probbly also many that would affect us and the whole project contains no license information except https://github.com/loopj/jquery-tokeninput/blob/master/src/jquery.tokeninput.js#L6.

So I think for now the code would not be that helpful. I think it makes more sense to implement the missing / needed features in our code. Also please keep in mind that materialize 1.0.0 dropped jQuery and uses plain JavaScript (and cash-dom as jQuery replacement). Rewriting all the code that you provided to work without jQuery is also extra work.

**Comment by scabros** [comment]
hi daniel, thanks for your time. if i rewrite the js to use cash-dom or vanilla js, would that be useful fot this project?

**Comment by DanielRuf** [comment]
I would not try to rewrite the whole jquery-tokeninput but try to extend our autocomplete component in some way. This is the easier approach imo.

**Comment by wuda-io** [comment]
AFAIK is this feature already implemented also without the additional dependency.
Take a look at https://materializecss.github.io/materialize/chips.html
