### ISSUE TITLE
Date/Time picker with format function

### ISSUE THREAD

**Issue by Calamari** [materializecss/materialize#151]
Hey Materialize-Team.

I have a simple but – in my eyes – useful improvement idea, which would make my life (and [others](https://github.com/Dogfalo/materialize/issues/6257)) easier.

## Desired Behavior
If using the Datepicker, it would be nice to be able to pass a formatting function into the format property, kind of like this:

```js
M.Datepicker.init(elems, {
  format: date => new Intl.DateTimeFormat(locale).format(date)
});
```

## Current Behavior

Currently, we can only add a string there, which makes it hard to have different formats for different locales, since we have to keep a mapping of locales to formats. It would be more practical, to be able to defer it to the Browser itself or a different package that the user probably already uses, like moment.js or date-fns.

## Context

I think I tapped into this in the "Current Behavior" section.

## Your Environment
* Version used: 1.0.0
* Browser Name and version: Any
* Operating System and version (desktop or mobile): Any

**Comment by Calamari** [comment]
If you think that is a good idea, I can also create the PR for this, if it helps.

**Comment by DanielRuf** [comment]
cc @materializecss/members

**Comment by wuda-io** [comment]
Yes, a PR is very welcome 👍

**Comment by Calamari** [comment]
And there is the PR, I hope that is to your liking :-)
I was not quite sure, if I was supposed to merge it against master or v1-dev (which seems to be the default), so I took the default. Also, the master seemed to have some dependency issues and did not want to install at all.
