### ISSUE TITLE
Website GitHub Section

### ISSUE THREAD

**Issue by LWGShane** [materializecss/materialize#152]
The "Latest Commit on GitHub" section on the frontpage of the website contains a commit from the old repo and the "GitHub" button links to the old repo. Maybe this should be 'fixed' to not discourage new users from using the project?

**Comment by ChildishGiant** [comment]
Are you sure you're on the right site? Ours is hosted here: https://materializecss.github.io/materialize/

**Comment by Smankusors** [comment]
if you're talking about https://materializecss.com/, unfortunately no. We don't have access to edit this website.
