### ISSUE TITLE
Communication channels

### ISSUE THREAD

**Issue by IamRifki** [materializecss/materialize#16]
What does everyone recommend for communication? I saw someone recommend Slack, but it has its issues (i.e. Invites Expiring with no option to make a permanent one and [the finicky UX](https://www.swyx.io/writing/slack-fumble/)). Gitter is used by the old project, so no luck there.

I recommend either Discord or Matrix.

What does everyone else think?

**Comment by ray007** [comment]
Why not gitter? What's the problem there?

**Comment by IamRifki** [comment]
> Why not gitter? What's the problem there?

Name's been taken by the original project, so we can't.

**Comment by ray007** [comment]
You think @Dogfalo would insist on keeping it?
And there's no way to choose a different name?

**Comment by IamRifki** [comment]
Not sure if he'll give it. as for a different name, maybe, I guess.

**Comment by Smankusors** [comment]
we could create new one like https://gitter.im/materializecss/materialize instead

IMO discord looks fine for me, I rarely used Slack... Well I never used Matrix too...

**Comment by DanielRuf** [comment]
> we could create new one like [gitter.im/materializecss/materialize](https://gitter.im/materializecss/materialize) instead

Already tried, this does not work.

<img width="841" alt="Bildschirmfoto 2020-08-28 um 00 43 12" src="https://user-images.githubusercontent.com/827205/91502070-7d818e80-e8c7-11ea-842a-c98293d11ae1.png">


Slack costs money so this is not an option. Discord sounds good.

**Comment by Smankusors** [comment]
I don't see why that is not available. The Gitter API isn't returning 409 Conflict, but 200 OK. Perhaps you should login as organization instead of personal account? Maybe [this documentation](https://gitlab.com/gitlab-org/gitter/webapp/-/blob/develop/docs/faq.md#why-isnt-my-github-organisation-or-repos-appearing) could be helpful.

![image](https://user-images.githubusercontent.com/10087890/91510981-cd347a00-e908-11ea-9aac-5e6c724f95be.png)

```
{"type":"GH_ORG"}
```

**Comment by DanielRuf** [comment]
> Perhaps you should login as organization instead of personal account?

I'm not sure I understand. There is no such option for Gitter.

![grafik](https://user-images.githubusercontent.com/827205/91529776-35d02680-e90a-11ea-882e-52da96d7e518.png)

You just login as a personal account not as an org. And communities are not automatically generated.

See the different response when you try to enter an existing org from GitHub (I'm member of the webpack org):

![grafik](https://user-images.githubusercontent.com/827205/91529916-7039c380-e90a-11ea-9f2c-2dc092ac234e.png)

**Comment by DanielRuf** [comment]
I tried some things before like syncing orgs, didn't change anything. Not sure but something happened and some materializecss community was created but linked with the webpack org. This is very buggy tbh.

I'll invest some more time to find a solution or resolve that with the Gitter team but so far Gitter is not the best platform imho.

**Comment by DanielRuf** [comment]
Granted access for Gitter for the materializecss org now (tried so many times in the past, not sure why it didn't work), and wrote Gitter support to delete the accidentally created community.

**Comment by Smankusors** [comment]
Btw what is this communication will be used for? Internal dev communications? Help & Support for end users?

**Comment by DanielRuf** [comment]
For help & Support for end users.

GitHub is for the developers (and also org discussions). No more platforms needed than two.

**Comment by DanielRuf** [comment]
https://gitter.im/materializecss/community has been created now.

**Comment by IamRifki** [comment]
Cool! I'm gonna close this issue now.
