### ISSUE TITLE
CSP error when trying to run docs in browser

### ISSUE THREAD

**Issue by christinavoudouris** [materializecss/materialize#160]
I get the following error in the console when I run 'npm run dev' along with a white screen that says Cannot GET / :

Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-d/yERybm6Vg1oK5uXfPNUtFdLqpjo+RlG7iGStOnXLg='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

When using Express/Node, I've installed and set up Helmet, but not sure how to fix the error within this particular project.

**Comment by christinavoudouris** [comment]
Did some digging, and this is apparently an issue with BrowserSync. I was able to load the docs by adding /docs. Closing this for now.

**Comment by ChildishGiant** [comment]
Ah yeah, we made some changes to directories so now you need to add /docs on the end when previewing. If there's a way to make the link in the terminal show that, ill happily make that change.

**Comment by christinavoudouris** [comment]
Not sure about the terminal but I think it'd be a good idea to add /docs to the end of the URL in the README.
