### ISSUE TITLE
Col classes m, lg,  and up adds a huge left margin, v1.0.0

### ISSUE THREAD

**Issue by devtrix** [materializecss/materialize#165]
Col classes "m" and up adds a huge left margin.

**Comment by wuda-io** [comment]
Can you post some Code to clarifiy your problem? Also what Version did you use?

**Comment by devtrix** [comment]
> Can you post some Code to clarifiy your problem? Have you tried with the newest Version 1.1.0 Alpha?
> Which Browser?
> Screenshot?

I am not sure why I was having this problem in the first place.   I had a very simple Html with row and col and a simple card.  Today its working and the weird part is its the same folder/file.  I am embarrassed & terribly sorry to have wasted your time. I think I woke up in a different dimension or something.  Thank you for your prompt response.  Have a great day.  Stay safe.  I am closing this now.
