### ISSUE TITLE
CI: move to GHA

### ISSUE THREAD

**Issue by DanielRuf** [materializecss/materialize#17]
We should move from TravisCI to GHA.

**Comment by ChildishGiant** [comment]
I've got a fair amount of experience with actions and would be willing to help out :)

**Comment by DanielRuf** [comment]
Anyone interested? I can help with this but have not much time. I can also refer to some GHA setups that I use.

@materializecss/members

**Comment by ChildishGiant** [comment]
I think this can be closed now that nightly builds, tests and soon docs are built with GHA
