### ISSUE TITLE
Undesired effect of .waves-circle on floating button

### ISSUE THREAD

**Issue by ivanBell199** [materializecss/materialize#173]
## Expected Behavior
The floating button should be of the same size no matter .waves-circle is present or not. The icon should always be perfectly in the center.

## Current Behavior
The size of the button is smaller and the icon is moved a little bit down. It can be seen in the docs [(Waves -> Circle)](https://materializecss.github.io/materialize/waves.html#!). 

## Possible Solution
Change styles of .waves-circle
```
.waves-circle {
  text-align: center;
  width: 40px; /* instead of 2.5em*/
  height: 40px; /* instead of  2.5em*/
  line-height: 40px; /* instead of  2.5em*/
  border-radius: 50%;
}
```
Another option is to remove `line-height: 40px;` from .btn-floating i, since it is already specified in another place.
```
.btn i, .btn-large i, .btn-small i,
.btn-floating i,
.btn-large i,
.btn-small i,
.btn-flat i {
  font-size: 1.3rem;
  line-height: inherit; /* this line is OK */
}

.btn-floating i {
  width: inherit;
  display: inline-block;
  text-align: center;
  color: #fff;
  font-size: 1.6rem;
  line-height: 40px; /* Is this line needed? It overrides line-height: inherit; from above.
}
```

**Comment by ChildishGiant** [comment]
The `waves-circle` class shouldn't really have any css rules associated with it in my opinion, removing them solves these issues. The only necessary rules should be these.
```css
.waves-button, 
.waves-circle {
  @include waves-transform(translateZ(0));
  -webkit-mask-image: -webkit-radial-gradient(circle, white 100%, black 100%);
}
```

Unless anyone has issues with this I'll happily commit these changes.

**Comment by wuda-io** [comment]
implemented in [v2-dev](https://github.com/materializecss/materialize/tree/v2-dev)
