### ISSUE TITLE
[Feature Request / Discussions] Use of flexbox for materialize grids

### ISSUE THREAD

**Issue by LoganTann** [materializecss/materialize#174]
Hello, thanks for the community to maintain this project !

I liked how the grid system works in MaterializeCSS : intuitive and fast to create.

However, it uses rules like `float: left`, which is not the best practice for creating grids.

Using flexbox or even CSS grids (which is now available in most browsers, in contrary of the 2017-2018 years where materialize have been developed) should be a better way to do such feature.

With materialize.CSS using `float:left` and some other tricks, the layout is sometimes not good with some modern projects, and not easily customizable. Moreover, materialize currently uses flexbox, like the `valign-wrapper` class

I haven't seen a GitHub discussion section in this repository, that's why I'm opening this issue.
If such issue is not allowed, I can close it

**Comment by ivanBell199** [comment]
That would be fantastic. I always get a headache when my cards differ in size and ruin the layout. I use flex as a workaround and would be happy if the framework provided it out of the box

**Comment by wuda-io** [comment]
That sounds awesome! We should defintely upgrade to grid. I am using it as a workaround for Cards etc. too.
How should we update the existing Project?

**Comment by LoganTann** [comment]
> 
> 
> That sounds awesome! We should defintely upgrade to grid. I am using it as a workaround for Cards etc. too.
> How should we update the existing Project?

I think just by updating the `sass/components/_grid.scss` file. Also, for that kind of change, it's necessary to run the unit tests successfully.

We may take inspiration from bootstrap grids : https://getbootstrap.com/docs/5.1/layout/css-grid/ ?

**Comment by ChildishGiant** [comment]
This could be one of the breaking changes we introduce with 2.0

**Comment by wuda-io** [comment]
Is in the new 2.0.0 alpha
