### ISSUE TITLE
Modify some parts of the documentation to mention the new 1.1.0-alpha

### ISSUE THREAD

**Issue by LoganTann** [materializecss/materialize#179]
I have some suggestions to improve the documentation to show more what's changed with the 1.1.0-alpha community release.

## Behaviors
![image](https://user-images.githubusercontent.com/28659185/132951583-290fe1c2-a079-4358-bc9f-48a2cc976758.png)

1. the version in the docs is 1.0.0 and not 1.1.0(-alpha)
2. should the upgrade guide page be changed from `0.100 -> 1.0` to `1.0 -> 1.1.0` ?
3. (not in the screenshot) No mentions that 1.1.0 is a community maintained version (fork) and not the official version

![image](https://user-images.githubusercontent.com/28659185/132952074-fc7ef900-3f9c-4ece-8c8c-404efa27a90e.png)

4. new options don't show that it was introduced by 1.1.0-alpha

## Possible Solution

1. Change the 1.0.0 to 1.1.0 in the first option of the dropdown. We can also add a new dropdown link between 1.1.0 and 0.100.2 with the content `1.0.0` that redirects to the official docs (materializecss.com)
2. We have to debate if it's necessary.
3. Adding a short message directly in the main page, or in the about one.
4. Adding either a badge or the short text "since v1.1.0-alpha" in every added options

## Context

I couldn't see what changed from 1.0 to 1.1 other by checking the release post. Even if it's minor changes, we can see better what's different between the official and the community release/documentation

**Comment by wuda-io** [comment]
Why not remove this button completely.
Is it still needed?

**Comment by DanielRuf** [comment]
Anyone who wants to pick this one up? @materializecss/members 

> Why not remove this button completely.
> Is it still needed?

The "migrate" button?

**Comment by wuda-io** [comment]
> Anyone who wants to pick this one up? @materializecss/members
> 
> > Why not remove this button completely.
> > Is it still needed?
> 
> The "migrate" button?

Yes, i think it is not needed anymore and from a Marketing point of view it os better to have a single and clear "get started" button

**Comment by ChildishGiant** [comment]
I feel like we should just work on getting it out of alpha and then update the site but I agree that the migrate button is no-longer needed (although in the future I imagine we'll make a breaking change and add a page for that)

**Comment by LoganTann** [comment]
I'm starting to work on this issue (hacktober is motivating me :grin:).

I will do the first point (update navbar dropdown) and for the second one I will delete the upgrade guide button, as well as the page by itself since it's no longer needed.
About the third point (mention this is a community project) I think this should rather be fixed in #194

Finally, what are you all thinking about the 4th point (adding a text "since 1.1.0" to options introduced in that pre-release) ?
