### ISSUE TITLE
Testing Stuck Indefinitely

### ISSUE THREAD

**Issue by Smankusors** [materializecss/materialize#183]
Recently, the `npm run test` command stuck for some reason. Causing timeouts on the recent PRs. Please take a look at the recent tests:
https://github.com/materializecss/materialize/actions/runs/1154694124
https://github.com/materializecss/materialize/actions/runs/1173463450
https://github.com/materializecss/materialize/actions/runs/1226735457

## Expected Behavior
The tests should run normally

## Current Behavior
Tests stuck indefinitely

Console output:
```
> @materializecss/materialize@1.1.0-alpha test
> grunt travis

Running "concat:temp" (concat) task

Running "configureBabel" task

Running "babel:bin" (babel) task

Running "clean:temp" (clean) task
>> 1 path cleaned.

Running "sass:gh" (sass) task

Running "sass:bin" (sass) task

Running "postcss:gh" (postcss) task
>> 1 processed stylesheet created.

Running "postcss:bin" (postcss) task
>> 1 processed stylesheet created.

Running "notify:sass_compile" (notify) task

Running "connect:server" (connect) task
Started connect web server on http://localhost:9001

Running "jasmine:components" (jasmine) task

Testing specs with Jasmine/latest via HeadlessChrome/78.0.3882.0
```

## Possible Solution
I also tried with my Windows environment and it's stuck for hours, nothing happened. I spectate there's a problem with headless Chrome? Maybe the version was too old? I haven't investigate this further.

## Steps to Reproduce (for bugs)
1. Run `npm run test`
2. Stuck.

**Comment by DanielRuf** [comment]
Probably Chrome / Chromium related I guess. Can we safely update the devDepencencies to resolve this?

**Comment by LoganTann** [comment]
Experienced the same kind of issue. I thought at first it was my laptop's speed (since in runs in ultra saving mode)
Unfortunately, jasmine is not verbose enough to see why and where this is happening

**Comment by DanielRuf** [comment]
I'll try to update some parts to see if this resolves it.

**Comment by DanielRuf** [comment]
It seems we also use phantomjs-prebuilt?

Anyways, I have opened a PR at https://github.com/Dogfalo/materialize/pull/6660 but this is untested. Feel free to make more changes.

**Comment by DanielRuf** [comment]
Ah, I found something: https://github.com/gruntjs/grunt-contrib-jasmine/issues/339

Maybe we should migrate to some different test setup in the future. I will add these options and check again.

**Comment by DanielRuf** [comment]
It seems we also use phantomjs-prebuilt?

Anyways, I have opened a PR at https://github.com/materializecss/materialize/pull/189 but this is untested.

**Comment by DanielRuf** [comment]
Should be resolved now: https://github.com/materializecss/materialize/pull/189
