### ISSUE TITLE
Rename grunt task

### ISSUE THREAD

**Issue by DanielRuf** [materializecss/materialize#188]
https://github.com/materializecss/materialize/blob/v1-dev/Gruntfile.js#L720

We are not using Travis anymore (after their latest failure regarding security no opensourc eproject should).

https://portswigger.net/daily-swig/credential-leak-fears-raised-following-security-breach-at-travis-ci

**Comment by wuda-io** [comment]
The Line does not exist anymore. What exactly should be renamed here?

**Comment by DanielRuf** [comment]
> We are not using Travis anymore

https://github.com/materializecss/materialize/blob/main/Gruntfile.js#L692
https://github.com/materializecss/materialize/blob/main/package.json#L20

**Comment by LoganTann** [comment]
Okay, so instead of renaming, we just have to remove anything related to travis ?

Or is it a more complex ?

**Comment by DanielRuf** [comment]
> Okay, so instead of renaming, we just have to remove anything related to travis ?

Rename since the `test` script in CI and locally uses this grunt task:

https://github.com/materializecss/materialize/blob/main/Gruntfile.js#L695

<img width="723" alt="Bildschirmfoto 2022-10-14 um 21 23 31" src="https://user-images.githubusercontent.com/827205/195926086-1a81cb0d-fce9-4795-8bc2-fbeb24547e0a.png">

https://github.com/materializecss/materialize/blob/main/package.json#L20

<img width="377" alt="Bildschirmfoto 2022-10-14 um 21 23 52" src="https://user-images.githubusercontent.com/827205/195926096-94c10e1e-5ee0-4680-b379-d43915eae6f6.png">
