### ISSUE TITLE
Materialize Moving Forward

### ISSUE THREAD

**Issue by ryanrapini** [materializecss/materialize#2]
Hey all,

I'm coming here from the discussion [here](https://github.com/Dogfalo/materialize/issues/6515).

I am happy to start providing pull requests. There are several minor issues that I would love to be fixed in the short term, as I have been using materialize in a very mature Laravel/Vue project in production for the last 4+ years. If there's a confirmation that this is in fact the place to put pull requests and that they will be accepted here instead of stagnating, I'd like to help.

Let me know if there is some sort of organization/trello/work board that i can see.

**Comment by mau5ken** [comment]
HI, I was reading that conversation. I'm really excited to see materialize going forward. I'm available too to support this project. I've been a huge fan of Materialize since the beginning. Is there's something I can help with please let me know. I can maintain any other tasks or create pull request in order to support Materialize.
Best Regards!

**Comment by DanielRuf** [comment]
> Let me know if there is some sort of organization/trello/work board that i can see.

So far we have no such board but the project at https://github.com/materializecss/materialize/projects/1

We can probably use the free version of [ZenHub](https://www.zenhub.com/).
I have invited you to the org. We will create different teams later when we have enoug people so we can create a good structure with different permissions.

**Comment by DanielRuf** [comment]
For existing pull requests like https://github.com/Dogfalo/materialize/pull/6521 I did the following:

```shell
# clone the new fork, best is you fork it you clone it to your personal account and use your username instead of materializecss
git clone git@github.com:materializecss/materialize.git
# go into the new folder
cd materialize
# add the original upstream repo as remote
git remote add upstream git@github.com:Dogfalo/materialize.git
# fetch all references from the upstream
git fetch upstream
# checkout the original PR and branch using the GitHub CLI
# alternatively see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally and use upstream instead of origin
gh pr checkout 6521
# now push the branch to your own fork or the materializecss one
# create new PR from the branch and submit it to materializecss/materialize
```

**Comment by DanielRuf** [comment]
@mau5ken I sent you also an invite to the new org.

**Comment by mau5ken** [comment]
All right!!! Very excited. Let's make MaterializeCss great again! <3

**Comment by DanielRuf** [comment]
We want to keep development in one place and not clutter it with many different tools and logins.

So far it works for the projects where I am collaborator.

**Comment by Chrisx84** [comment]
ah ya good idea, kinda does look like a trello board. well good luck with this project, cant wait to use it again on my websites. YES plural, i got many all using bootstrap right now

**Comment by ChildishGiant** [comment]
I have multiple projects that are reliant on materialize so would happily lend a hand.

**Comment by DanielRuf** [comment]
@ChildishGiant awesome =) We could need some help to triage the open PRs from the upstream repo and to decide which we should merge here in the fork.

**Comment by ChildishGiant** [comment]
https://github.com/Dogfalo/materialize/pull/6078 (Add new i18n option 'headerFormat' to datepicker)
https://github.com/Dogfalo/materialize/pull/2490 (Add input suffix)

These both seem like targets. I'm having troubles with my git though, so can't test them rn :/

**Comment by DanielRuf** [comment]
I've added both to #7

**Comment by mau5ken** [comment]
@DanielRuf is there need to be a new site for a the new changes the whole community is doing? I think it would be nice, I can go over a complete new UX/UI design page in order to bring attention to this project. 

Also I'm coming as a 100% supporter. I want to spend more time in Open source project's now, so @DanielRuf feel free to discuss anything priority with me. 

Thanks! <3

**Comment by DanielRuf** [comment]
> @DanielRuf is there need to be a new site for a the new changes the whole community is doing? I think it would be nice, I can go over a complete new UX/UI design page in order to bring attention to this project.

At least the website is a live demo of the framework and its capabilities (eat your own dog food). A distinction and a different design could be useful to make clear that this is a fork with improvements and major changes in the future after the biggest bugs are fixed.

I think we could need more examples, a better search and better getting started guide with some example projects for those who are not that experienced with JS (but would find code blocks useful that contain the needed code). A bit like the coding blocks for Foundation Sites (I'm a maintainer of Foundation Sites): https://get.foundation/building-blocks/ (just an idea). And this would probably help more people to get started with materialize.

**Comment by DanielRuf** [comment]
npmjs org created and original 1.0.0 release uploaded to npmjs: https://www.npmjs.com/package/@materializecss/materialize

**Comment by doughballs** [comment]
@mau5ken this is a great idea. Also, an opportunity to change the default theme colour - lighthouse downgrades the current default colours for poor contrast, if you pay any attention to that sort of thing.

@DanielRuf also great idea - I use materialize exclusively in Wordpress, and am working on a theme at the minute, thinking about how I can help the user with blocks in the same way. Everything is moving in this direction.

I have never worked collaboratively before, so not sure how to contribute beyond my opinion in here.

**Comment by DanielRuf** [comment]
I think we can prepare the next release in the next days / weeks.
I'll go through the current changes then, check if it's a minor or patch release and start preparing some changelogs if I find the time. Help is very welcome.

After this we'll setup semantic-releases probably to automate this, migrate the CI setup (maybe before the release?) and so on.

**Comment by mau5ken** [comment]
How can I contribute to acquire the .org extension for materializeCSS? I would like to make this donation in order to start uploading some new improvements. Plus, I can't download the repo to make some improvements is there a protocol for this @DanielRuf ? 

Thanks for your kind reply.

**Comment by DanielRuf** [comment]
To provide a PR you have to do the following steps:

Fork the repo to your own account:

<img width="324" alt="Bildschirmfoto 2020-09-07 um 22 47 49" src="https://user-images.githubusercontent.com/827205/92416109-33689a80-f15c-11ea-920a-beb91422f3fd.png">

Then clone and checkout your branch.

```
git clone git@github.com:mau5ken/materialize.git
cd materialize
git checkout -b your-new-branch-name
```

Then apply your changes, commit and push them to your fork.
From there you can open a PR to materializecss/materialize.

There are also some guides like https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request and https://opensource.com/article/19/7/create-pull-request-github

**Comment by DanielRuf** [comment]
> How can I contribute to acquire the .org extension for materializeCSS?

I'm not sure if it makes sense to buy the org version when the original project has the com version. This could lead to some confusion when they land on the wrong website / fork.

I might still have a few domains for free in my hosting plan so you may not have to buy one.
Also when someone donates a domain we would need to have control over it (DNS and so on) just in case something happens.

For now it's best when I order some domain, enter the needed registration details and create a separate account in my hosting which contains only the domain and I elect someone or some of us who should also have access to it.

We should discuss and decide together what the best solution is, also regarding the situation that there is still the com version which is used by many.

**Comment by doughballs** [comment]
@DanielRuf one question re PR - now that I’ve created my first one, what about if I need to create a second one? Do I have to do the whole process again? Or a new branch? Or just a new commit to the same branch?!

And re the domain/name/new brand - I realise we may not have the forward movement for materialize2 just yet, but it would be a good idea to really differentiate us from .com (to avoid confusion) and I think a number 2 is a solid way to do it. Or some other clear marker that this is a new path.

**Comment by wuda-io** [comment]
Materializecss2.com sounds good

**Comment by DanielRuf** [comment]
@doughballs in this you create a new branch for the new PR.

**Comment by blackjyn** [comment]
Damn, I'm at the progress on making Materialize CSS course on Udemy.
I'll probably help on making the docs even friendlier cos current docs sucks

**Comment by DanielRuf** [comment]
> Damn, I'm at the progress on making Materialize CSS course on Udemy.
> I'll probably help on making the docs even friendlier cos current docs sucks

That sounds great. Looking forward to your first PR here =)

**Comment by blackjyn** [comment]
@DanielRuf not pretty soon, but I do have collected several bugs and possible enhancements on Forms and JS Comps.
For instance, the Accordion comps does NOT support `<dl><dt><dd>` construct, while other FW like Bootstrap supports it.
Also, incomplete aka partial support on Form's component validation. 
etc. etc..
lot of things.

**Comment by khashashin** [comment]
If you guys need help of the community, I would recommend you to create new release asap and show people that this fork started to make releases and push new features. Then, I believe, people will switch to this fork.

**Comment by DanielRuf** [comment]
> If you guys need help of the community, I would recommend you to create new release asap and show people that this fork started to make releases and push new features. Then, I believe, people will switch to this fork.

This is planned for this or next month (a new release) =)

**Comment by xenkuo** [comment]
You guys are the real hero, thanks for all your efforts.

**Comment by Christopher-Rains** [comment]
@DanielRuf  Greetings! Thank you all for helping to push this project forward. I've used it in several projects before and have thoroughly enjoyed it. I was worried the project might be abandoned so I was very pleased to see this fork moving forward with bug fixes and enhancements. 

I'd like to help participate in the project and contribute in any way I can. I haven't spent a lot of time looking through the source code of the project but I've been developing JavaScript applications for 10+ years so I'm happy to jump in where I can. I'm also happy to help with writing documentation and building out the new website if there is work to be done there.

Thanks again for your dedication to this. Let me know how I can help!

**Comment by DanielRuf** [comment]
> I'd like to help participate in the project and contribute in any way I can. I haven't spent a lot of time looking through the source code of the project but I've been developing JavaScript applications for 10+ years so I'm happy to jump in where I can. I'm also happy to help with writing documentation and building out the new website if there is work to be done there.

Any help is very welcome.

**Comment by erkrapide** [comment]
I am here to pledge my allegiance. Any word on a release anytime soon?

**Comment by DanielRuf** [comment]
We could need some changelog for the release.
See https://github.com/materializecss/materialize/compare/1.0.0...v1-dev for the changes / commits after the v1.0.0 release.

I plan to do the release then with @Smankusors so he knows the publishing process and has the needed rights.

**Comment by TomFreudenberg** [comment]
Just a "Thank you all" continuing this work!  👍 

Thats great!

Tom

**Comment by mxdpeep** [comment]
good to see some progress 💪🤩

**Comment by mxdpeep** [comment]
I may create a Docker release builder of static releases, current building system is quite complicated

**Comment by Smankusors** [comment]
> I may create a Docker release builder of static releases, current building system is quite complicated

well currently it's just as simple as cloning this repo, then `npm install`, then `npm run release -- --oldver=[current version] --newver=[new version]`, and get the files at dists folder. Although this could be improved later...

creating Docker for release builder seems.... IMO more complicated though... 🤔

**Comment by DanielRuf** [comment]
> well currently it's just as simple as cloning this repo, then `npm install`, then `npm run release -- --oldver=[current version] --newver=[new version]`, and get the files at dists folder. Although this could be improved later...
> 
> creating Docker for release builder seems.... IMO more complicated though... thinking

Exactly.

@mxdpeep please test if it works for you or if there are any issues that we have to resolve.

**Comment by DanielRuf** [comment]
> Are there any plans to use webpack (or something) instead of bower + grunt?

In the future (next year) probably as this requires some work.

> I have a suggestion to remove the old branches in this project. Might not be super important, just a suggestion though.

This is on our roadmap, to cleanup / remove old branches.

> Another problem is the jade files (what are they used for?) should be upgraded to pug.

For generating the html files for the documentation.

PRs are very welcome.

**Comment by wuda-io** [comment]
Hey guys! Whats the plan for the upcoming release? Would be great to hear a concrete date. I read somewhere that the plan is to release this year. Thanks for info. Keep up the good work <3

**Comment by DanielRuf** [comment]
No concrete date planned.

**Comment by L1ghtn1ng** [comment]
Is this going to get uploaded to cdnjs.cloudflare.com when the release gets done?

**Comment by DanielRuf** [comment]
> Is this going to get uploaded to cdnjs.cloudflare.com when the release gets done?

Probably under a different name. Also personally I do not recommend the usage of CDNs as the advantages are mostly gone with the new cache partitioning in browsers.

Afaik cdnjs uses a repo and they have to pull that in by request. See https://github.com/cdnjs/packages/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by jshster** [comment]
Hi guys, I posted on the original repo but have since discovered this one.   Just trying to get an understanding of where we're at.   All of my projects are using Materialize 1.0.0.   Apologies for the dumb questions.   I've used GitHub as version control but never collaboratively and am struggling to make sense of where things are at. 

I would love to help out.... just not sure how.   I've spent far too long pulling my hair out trying to work out undocumented features or discovering that components don't work the way the doco seems to suggest.    

I look forward to hearing more soon.

**Comment by wuda-io** [comment]
Hello,
yea in the beginning it was really motivating, but now it seems to stand still too a bit. I made a PR 3 weeks ago which fixes a major bug, but until now nothing happened. Also it was planned to make a release this year, but also nothing... So it would be interesting who is responsible for the management of this repo.
I would also like to push this project further, but i have no rights to accept a PR.
Maybe it would make totally sense to make a weekly PR merge and summary what happened to improve over time.
Best regards

**Comment by jshster** [comment]
> Hello,
> yea in the beginning it was really motivating, but now it seems to stand still too a bit. I made a PR 2 weeks ago which fixes a major bug, but until now nothing happened. Also it was planned to make a release this year, but also nothing... So it would be interesting who is responsible for the management of this repo.
> I would also like to push this project further, but i have no rights to accept a PR.
> Maybe it would make totally sense to make a weekly PR merge and summary what happened to improve over time.
> Best regards

OK, I'll dip my toe in what could be a political minefield - who does have the rights?  And what are they doing?  Is anyone in touch with them?  Would it be crazy to suggest a zoom call between interested parties?

**Comment by DanielRuf** [comment]
> OK, I'll dip my toe in what could be a political minefield - who does have the rights? And what are they doing? Is anyone in touch with them? Would it be crazy to suggest a zoom call between interested parties?
Hi, I'm the owner of the org and @materializecss/members-write-access have write access. But people have more important things at the moment. See the outstanding changes in the PRs for example.

No real need for a zoom call if no one has time at the moment.

Any help is very welcome.

**Comment by DanielRuf** [comment]
> OK, I'll dip my toe in what could be a political minefield - who does have the rights? And what are they doing? Is anyone in touch with them? Would it be crazy to suggest a zoom call between interested parties?

Hi, I'm the owner of the org and @materializecss/members-write-access have write access. But people have more important things at the moment. See the outstanding changes in the PRs for example.

No real need for a zoom call if no one has time at the moment.

Any help is very welcome.

**Comment by wuda-io** [comment]
Hi @DanielRuf
thanks for the merge. Highly appreciate this. 
This is my first PR ever made 🥳
I am looking forward to contribute even more in the future. Have a good time ✌️

**Comment by LoganTann** [comment]
No releases since 10 Sep 2018, and the repository have been created for more than 10 months ... 

Do the team know when we will get a new release (even beta, as long as we have more fixed bugs than 1.0) ?

**Comment by khashashin** [comment]
@LoganTann same question. It may look pointless, but in my opinion, to get more contributors, you should say that there are new features or bug fixes in this repo, even if only 2 lines of code was changed, to get people to start use this repo instead.

**Comment by DanielRuf** [comment]
There is at least a nightly CI job, see https://github.com/materializecss/materialize/actions/runs/689172656

So you can already get nightly builds.

Writing changelogs and coordinating all this is not that easy, especially when you work full time in a company.

Any help is very welcome. If you can help us, feel free to take a look at the open issues, PRs, propose that you want to help with the release(s), and so on and I will invite you to the relevant teams.

**Comment by ChildishGiant** [comment]
I'm happy to write up all the changes and do all the chores required for a release when the time comes (hopefully soon 😉)

**Comment by TomFreudenberg** [comment]
Dear Allie, Daniel @ChildishGiant @DanielRuf 

I was using materializecss for a number of projects but always stay at the 0.x releases - patched by myself while Dogfallo didn't merged anything. I was always very happy with materializecss while it worked and worked and worked.

Starting with a new project I would like to use react-materialize and align that with this repository. But before proceeding I would like to ask if you could give me your current expectation about stability of this repo (v1-dev) in comparison to the old materialize-css@1.0.0-rc.2 branch.

Do you think it is ok to start already a production ready project on this branch?

In general I am willing to support and patch and bring in feedback but for the moment it should work mostly already.

Thanks for your information in advance
Tom

**Comment by DanielRuf** [comment]
> Do you think it is ok to start already a production ready project on this branch?

v1.0.0 of materializecss was already published in the past. See https://www.npmjs.com/package/materialize-css

V1-dev is the latest version - on our fork we use the same plus our changes. Which are released as v1.1.0-alpha.

A fork is a copy of an already existing project which is continued by the community. We do not start from scratch and do not plan to do so.

**Comment by DanielRuf** [comment]
> Do you think it is ok to start already a production ready project on this branch?

v1.0.0 of materializecss was already published in the past. See https://www.npmjs.com/package/materialize-css

v1-dev (also used by the original materialize repo) is the latest version - on our fork we use the same plus our changes (fixes), which are released as v1.1.0-alpha.

A fork is a copy of an already existing project which is continued by the community. We do not start from scratch and do not plan to do so.

**Comment by TomFreudenberg** [comment]
Hi Daniel @DanielRuf 

thanks for your comment. I know that a fork is the copy of an existing repo but in case of materializecss I haven't touched any of the _v1.x_ releases in any project. 

So for that my question is: Is it "safe" to go on with v1.0 or also already with v1.1.-alpha.

Just to get your personal opinion.

Thanks for a clarification and feedback.
Tom

**Comment by DanielRuf** [comment]
> So for that my question is: Is it "safe" to go on with v1.0 or also already with v1.1.-alpha.

This should be safe imo.

Afaik many have worked with the v1.0 version and v1.1-alpha includes many bugfixes for problems in v1.0. At work we have used materialize v1.0 in a big project and so far the requirements could be met.

**Comment by TomFreudenberg** [comment]
Thanks Daniel - so I will proceed!

**Comment by MacGyer** [comment]
Hey guys,

is this project still moving forward?
Will there be any stable release in the near future?

Thanks for getting back and stay safe.

**Comment by DanielRuf** [comment]
Hi @MacGyer,

we can need any help that we can get. Opensource software lives from the contributions of volunteers. Currently I do not and can not invest any time in opensource anymore. The members of the @materializecss/members-write-access can push and make new releases and everyone of @materializecss/members can make reviews.

**Comment by MacGyer** [comment]
@DanielRuf Thanks for clarifying. 

I am a PHP guy, so unfortunately wouldn't be of much help. Was just a question out of curiosity, because I am maintaining a Yii2 implementation of Materialize :)

**Comment by Smankusors** [comment]
> @DanielRuf Thanks for clarifying.
> 
> I am a PHP guy, so unfortunately wouldn't be of much help. Was just a question out of curiosity, because I am maintaining a Yii2 implementation of Materialize :)

wow that's cool 😳 

anyway if you have any issues with materializecss, feel free to create an issue here 😉 

ehm... but unfortunately I'm no longer employed in a place where materializecss is used. So I also don't have time to fix it. But if anyone else creates a PR, I will happily review it and merge it.

We're also planning to release the 1.1.0-beta version soon

**Comment by TomFreudenberg** [comment]
Very sad to see this component going down in usage but as far as more and more are using frameworks like react and MUI or Tailwind or whatever - it will be necessary once to move existing software forward to better and more active supported libraries.

That is the pitty in use of OpenSource - no one is paid so it happens from time to time that things are going down.

Good luck to all here and see you somewhere else in future.

Cheers
Tom

**Comment by doughballs** [comment]
I was a big, big fan of Materialize when I started out as a developer and really enjoyed helping the community, but as time went by I found the need for a framework of any kind receding. I was writing a ton of overrides and leaning on the framework so little that I decided to just go DIY, which suits my control freak tendencies. I have a lot of builds that I maintain that use it but going forwards I’m framework agnostic…

**Comment by jshster** [comment]
> I was a big, big fan of Materialize when I started out as a developer and really enjoyed helping the community, but as time went by I found the need for a framework of any kind receding. I was writing a ton of overrides and leaning on the framework so little that I decided to just go DIY, which suits my control freak tendencies. I have a lot of builds that I maintain that use it but going forwards I’m framework agnostic…



> Hey guys,
> 
> is this project still moving forward? Will there be any stable release in the near future?
> 
> Thanks for getting back and stay safe.

I would love to help out as I use Materialize almost exclusively in my projects now.   I actually haven't run into many issues but maybe that's the simplicity of my implementations.

I would love to help out but I've never worked on an Open Source project before and I honestly don't know where to start.  Usually I'm told go and view the PRs and work from there but to be honest I'm still a bit dumb - where do I go from there?

I anyone has a few minutes to guide me I'd be happy to start ripping in, given that I work with the thing on a daily basis.

Josh

**Comment by mxdpeep** [comment]
People using Materialize CSS (I am running a dozen websites using it, so it
will be tough tasks to migrate it all for free) often move to BeerCSS
https://www.beercss.com/.

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by mxdpeep** [comment]
I have switched to 1.1 alpha and everything works fine so far, will test
the nightly build soon too.

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by LoganTann** [comment]
> I have switched to 1.1 alpha and everything works fine so far, will test the nightly build soon too. *Filip Oščádal* *https://mxd.cz <https://mxd.cz>*

Yep, our fork brings almost only bug fixes, so it should even be more stable than the official 1.0
There are only few breaking changes for security reasons.

**Comment by mxdpeep** [comment]
Well done! ❤️

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by blackjyn** [comment]
The beauty of Materialize is it's neutrality , I mean it is independent from other frameworks.
But nowadays let's admit we are using JS frameworks extensively to build websites. 
However since Materialize is at the "critical condition", here's the alternative you might consider if you were really wish for "moving forward" from Materialize:

- Svelte : [Svelte Material UI](https://sveltematerialui.com/)
- React : [MUI](https://mui.com/)
- Vue : [Vuetify](https://github.com/vuetifyjs/vuetify)

I had assembled Materialize paid course material some 1-2 years ago , but given the project is abandoned so I got no more interest to publish it , hell not even interested to finish it.

**Comment by mxdpeep** [comment]
*Vuetify* looks really nice!

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by wuda-io** [comment]
> The beauty of Materialize is it's neutrality , I mean it is independent from other frameworks. But nowadays let's admit we are using JS frameworks extensively to build websites. However since Materialize is at the "critical condition", here's the alternative you might consider if you were really wish for "moving forward" from Materialize:
> 
> * Svelte : [Svelte Material UI](https://sveltematerialui.com/)
> * React : [MUI](https://mui.com/)
> * Vue : [Vuetify](https://github.com/vuetifyjs/vuetify)
> 
> I had assembled Materialize paid course material some 1-2 years ago , but given the project is abandoned so I got no more interest to publish it , hell not even interested to finish it.

Please dont speak for others, if you cant finish your project, then it is not the fault of Materialize. Not everyone wants to depend on some short living Frameworks which change every now and then so thats fine. Some projects want to use some light, nice independent CSS and JS which can simply be exchanged and be flexible without needing to refactor the whole system. I think that should also be the target of the whole project.

**Comment by wuda-io** [comment]
Maybe we should seek some funding for the project, I would be glad to help out as developer if my work is funded so I can invest time in it. Who would be interested in such a solution too an can provide some fixed amount of time developing it? Then we could set up some funding and project plan.

**Comment by mxdpeep** [comment]
I am moving to Beer.css for the server-side Mustache templating (PHP 8.1),
and v3 of my CMS system will be powered by Vue.js and Vuetify - I need to
learn some modern JavaScript shit :)))

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*

**Comment by wuda-io** [comment]
So you have to depend on 3 things rather than using 1 thing properly? Sounds not very efficient but good luck. Fortunately you got matetialize to work. What made you use beercss? And why on the Server?

**Comment by mxdpeep** [comment]
1) Vue and Vuetify are both in active and rapid development, I don't like
React
2) server-side rendering is still a good option for Progressive Web Apps
3) Beer.css is also actively developed
4) I have no funds to invest into Materialize myself

Filip Oščádal 🍀📱

**Comment by mxdpeep** [comment]
BTW Beer.css is 70 kB only

Filip Oščádal 🍀📱

**Comment by wuda-io** [comment]
Yes beer is cool, but i would miss all the components, like multiselect etc. so i can not use it.
I think this project is awesome, so i will contribute here and push this forward. I think only the design needs some facelift, and some improvements, but the rest looks good 👍

**Comment by DanielRuf** [comment]
For any task there is a fitting tool, or multiple. You can all use what is best and fits your requirements, stack, team knowledge and so on.

I am only aware of one big customer on our side where we have an old Materialize v1 version (not the one from the fork). Other projects are mostly built in React and use Tailwindcss and custom components.

Maintaining opensource software is still a hard job and in most cases you get not paid for it. If you want to start some funding @wuda-io then it should be probably done with https://opencollective.com/.

**Comment by blackjyn** [comment]
> Please dont speak for others, if you cant finish your project, then it is not the fault of Materialize.

I never blame anyone. 
The reason I stop making it, is that why should I selling a course about a framework when the FW itself has no clear progress, no clear maintenance and no clear future?
I won't selling "fraud" course about FW that even the original creators are no longer care about. 

**Materialize has clearly been abandoned and if that's hurt you, its all on you whether you accept it or not.**

**Comment by mxdpeep** [comment]
I feel you, bro. 🍀❤️

Moving forward with a different toolset is my only option. 😂

Yes, making open source is hard...

Filip Oščádal 🍀📱

**Comment by TomFreudenberg** [comment]
@blackjyn - nothing to add

**Comment by wuda-io** [comment]
Yeah you can leave and use other tools.
But if it has no future then why are you looking up this project, come here and tell people what you think?
If you dont have anything to contribute thats fine but you should have some respect for other projects. I dont even know what you want... Would you be using Materialize when there is a fixed release plan or what are your concerns?

**Comment by DanielRuf** [comment]
@wuda-io please let's stay calm. I see no problems with recommendations for actively maintained solutions =)

I already had this case more than once, especially when I stopped maintaining and contributing to Foundation Sites after the original team wasn't working on it anymore.

Frontend is an area where things move fast and it is helpful when others tell us what solutions they use to know their needs. As maintainer you often do not see or want to see how things are changing. That's ok.

I see no disrespectul behavior. Please change your tone and let's move on together. If this does not help I will have to lock and moderate this issue here.

**Comment by wuda-io** [comment]
Yes I see your point.
But what is the solution?
I suggest that we make a release plan.
Next version should be 1.2 and from then every 3 or 6 month we should make the next release.
What do you think?

**Comment by wuda-io** [comment]
Also I think Materialize is not compareable to other big Frameworks. Because the whole Point of this Project is, that it does not require or depend on any framework.

For example if you want to make a small static website like a simple ContactPage, then I would not set up a whole React Project for that purpose, so I think we should not necessarily compare it to React, Vue or smth like this. But it is also nice that people are using it for bigger Projects.

We should keep in mind that this is a Design/Frontend Framework and it should stay that way. We should not handle any Data or Logic with Materialize (e.g. in the Autocomplete Input).
I would be glad to help getting this Project back on track.
Maybe you can give me some access to accept Pull Requests, then we can move faster from here.

**Comment by blackjyn** [comment]
> > Yes I see your point.
> But what is the solution?
> I suggest that we make a release plan.
> Next version should be 1.2 and from then every 3 or 6 month we should make the next release.
> What do you think?

:laughing: , so I think it is you that got the problem with MTFW. Me? I have no problem with it, thanks I did some projects with nice ca$h back in the day when MTFW was actively maintained. 

> I would be glad to help getting this Project back on track.

You can propose many solutions as you want, like bla bla bla bla...
But welcome to the party, if you think you can maintain Open Source projects without any strong financial backups than you are a real hero.  

At this modern era, most OSS projects that are actively maintained and developed got strong financial backups from commercial companies. Because behind every OSS projects there are real programmers (read: human) with their real life , with family to fed , with their prestigious time out of screen enjoying real life too.

> Maybe you can give me some access to accept Pull Requests, then we can move faster from here.

Not only you can pull, you can even fork this repo and then develop, fix, release anything at your own. 
That's another solution I propose you: re-start all on your own , be hero and stop insulting others on their decision.

**Comment by blackjyn** [comment]
> I see no disrespectul behavior. Please change your tone and let's move on together. If this does not help I will have to lock and moderate this issue here.

this is a must. :+1:

**Comment by wuda-io** [comment]
I already forked it and developed it further, thanks i already know that. But why start from 0 if we have already smth which is working and many people are interested in keeping moving.

Also a team is better, than developing alone.
But if your only solution is to kill this project, than please go ahead. I will work on my fork then.
I think maybe i was a bit harsh, but what you say is also very disrespectful.
But who cares? Make some $$ and keep hating.
Cheers bro

**Comment by wuda-io** [comment]
> 😆 , so I think it is you that got the problem with MTFW. Me? I have no problem with it, thanks I did some projects with nice ca$h back in the day when MTFW was actively maintained.

So If you got no ca$h anymore, what went wrong? And what has it to do with maintence of MTFW? ... are you even a developer, or are you a "Buy my Course" Guy? So I think we have different PoV. Please clarify.

**Comment by blackjyn** [comment]
the only thing we need to clarify is : why do you so harsh to me? 
Are you OK? Do you need psychological treatment? 

It is you that is go wrong all the time, messing with someone. 

Are you even a developer or are you a "FUCK YOU DON"T MESS WITH MTFW Guy?" 

Go to the doctor dude , before its too late.

**Comment by wuda-io** [comment]
Everything ok? 😂

**Comment by blackjyn** [comment]
Sorry @wuda-io , I got to block you soon.  Coz you got a way too far. 
But mark my words : even if you tried to maintain MTFW, you are going to fail. Successful OSS projects only possible with healthy contributors not by psychos.

**Comment by wuda-io** [comment]
Ok thats fine. Thanks for your advice.

**Comment by blackjyn** [comment]
To @DanielRuf , thanks for your great initiative and effort. 

After all of this, I'm on 2 surely my last projects ever that using MTFW from a loyal client since 2018, One is at this March 31st due date and another is at April 30th. 

Not a good farewell party but I'm give up on MTFW.  I can't contribute and collaborate with toxic people involved.
For me it is now a lovely time to move on to [Svelte Material UI](https://github.com/hperrin/svelte-material-ui). 

Thank's @DanielRuf , sorry for the unstar and good luck :pray: 
![good bye mtfw](https://user-images.githubusercontent.com/6046191/160846169-9789ae10-8b26-4779-984e-d22a399789f2.png)

**Comment by DanielRuf** [comment]
Guys please refrain from fighting - otherwise I will lock this here. @blackjyn no further comments are needed, this is currently not helpful.

This and other things are reasons why I stopped contributing my free time to opensource projects and especially maintaining. Until today I thought that we could bring this project forward together. But if everyone is just fighting, then I will completely stop the project and archive it. I have no energy to argument in such a heated discussion.

As both of you probably won't stop I'm closing this one here.
I hope you are ok in these hard times, because I'm not.

**Comment by DanielRuf** [comment]
Going to archive this repo since you won't see any future contributions as I will focus on more important things in life.
Any stress is currently very toxic to me, my health and body.

I wish you all a great time with whatever you want to do, create and use.

**Comment by DanielRuf** [comment]
If any of the current @materializecss/maintainers want to bring this project forward, please contact me on LinkedIn.
