### ISSUE TITLE
.git Folder is very big

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#204]
I recognized that the .git Folder of the Project is huge!
So it would be cool if we can clean/clear it, so that we dont have to download **180 MB** of Project Size!
I analyzed the Folder and the .git Directory takes up 92,7% of the whole Size.

If we could clean it that would be super awesome, so we can develop much faster and do not have to wait so long to complete the donwload Process. How can we achieve this?

## Possible Solution
https://stackoverflow.com/questions/5277467/how-can-i-clean-my-git-folder-cleaned-up-my-project-directory-but-git-is-sti

## Steps to Reproduce (for bugs)
1. Git clone Project
2. Wait
3. Check out Folder Size ~180 MB!

## Context
Waiting to download unessercary history or Files annoys and takes away dynamic.

![grafik](https://user-images.githubusercontent.com/27806175/136344298-1b5feec9-412d-40cd-8a44-7db297a51c50.png)

**Comment by DanielRuf** [comment]
> The git folder went below 59.5MB 😮 The drawback is that pushing the changes will rewrite every commit in this repo's history, making their hash different. I don't know it's that's a good idea....

Generally not a good idea.

We will have to see if we can change something in the upcoming v2 branch.

**Comment by cmcknight** [comment]
I get that, but if the size of the repo is an issue, keep the 1.x repo which would have all of that history but start 2.x anew. But again, that’s an opinion based on the question posed about the repo size getting too large. Ultimately, it’s not my decision but that seems to be a practical way of solving both issue. :-/

**Comment by wuda-io** [comment]
> > I recognized that the .git Folder of the Project is huge!
> > So it would be cool if we can clean/clear it, so that we dont have to download **180 MB** of Project Size!
> 
> You can make a `git clone --depth number-of-commits` and use only the last x commits.
> 
> We can not change the old commits ("rewrite history") without breaking PRs.
> 
> https://stackoverflow.com/a/1210012/753676

That would be an awesome solution. If this clones a lot faster, we should put that into the contribute document. I will test this and give an update then.

To clarifiy: I dont want to clear any history or not Credit someone. The goal here is to enable new developers faster and easier contribution. So we need good tested, fast and efficient solutions.

It is not a big issue, because i saw that the node_modules also downloads 500 MB. I just want that we keep this in mind to be lightweight when moving forward.

**Comment by wuda-io** [comment]
> @wuda-io I think for now we should document something like `git clone --depth 10` or some other reasonable default value in the contribution.md file.
> 
> Would you like to do that? I would fast-approve it.

Yes we can do that. Its a good solution. I will soon provide an PR for the docs, because also **master** needs renamed to **main** branch there too. I just wanted to wait for the other open PR.
