### ISSUE TITLE
GHA setup to automate release changelog creation

### ISSUE THREAD

**Issue by DanielRuf** [materializecss/materialize#211]
We should have some setup like this:

https://github.com/MylesBorins/node-osc/blob/main/.github/workflows/create-release.yml

This does several things, when a new tag is created and pushed:
* publish to npm
* create GH release
* generate changelog for the GH release

This may be useful for us. What do you think @materializecss/members?

**Comment by LoganTann** [comment]
This is very nice, but I think we will need to review / rework manually the automated change log if it's based on the commits.
I take for examples some of my PR that haves a bunch of commits for a single bug fix. It's better to have one change log entry instead of five

**Comment by wuda-io** [comment]
The Changelog is generated automatically by GitHub.
I think this is solved. Feel free to reopen.
