### ISSUE TITLE
New Material Design guidelines (material 3)

### ISSUE THREAD

**Issue by ZugBahnHof** [materializecss/materialize#216]
There are new Material Design guidelines for components (e.g. cards at https://m3.material.io/components/cards/specs). I think we should start to update all components to the new guidelines, as well as to the newest css standards. This would make materialize more modern.

**Comment by leonardorafael** [comment]
If you need MATERIAL DESIGN 3 how about https://www.beercss.com?

**Comment by Secret-chest** [comment]
I think there should be a setting somewhere, because m3 sucks. It doesn't feel like material design anymore. Or just stay with m2.

**Comment by Secret-chest** [comment]
M3 isn't material design anymore. It has no shadows, it looks cluttered and makes me dizzy.

**Comment by Secret-chest** [comment]
I'll fork this, anyways.

**Comment by ivanBell199** [comment]
Hello everyone! Now that we have 2.0.1-alpha, I can see some changes in the styles of the framework. So it would be nice to know what should be expected from the future versions of MaterializeCSS. Will it remain Material Design 2 or move to Material Design 3?

**Comment by wuda-io** [comment]
Yes we are moving towards M3. Slowly but steadily :laughing:

**Comment by Secret-chest** [comment]
No problem, I'm making my own framework lol.

**Comment by wuda-io** [comment]
Oh no :( Why do you not like M3?
The shadows are not very good for dark mode, and it sure looks different. But i think in the long term it is more clear if you get used to it. It would be cool to have you on board and share your thoughts.

**Comment by Secret-chest** [comment]
Even if the information density is lower in M3, M2 feels more airy. I don't know exactly why, but I think it's because in M2 everything is either white or accented, never pastel.
