### ISSUE TITLE
Dropdown select misclicks on iOS

### ISSUE THREAD

**Issue by JaccoK** [materializecss/materialize#220]
When clicking on a dropdown menu item, it registers the click as being on the element below the clicked element. I use dropdown Very annoying when navigating a website. There were some complaints about this in the original repo as well: [https://github.com/Dogfalo/materialize/issues/6464](url)

## Expected Behavior

The tapped option should select the actual tapped option, and not the one below it.

## Current Behavior

The tapped option is not selected. The option below is being selected.

## Possible Solution

Multiple suggestions have been added here: [https://github.com/Dogfalo/materialize/issues/6464](url)

## Steps to Reproduce (for bugs)

Check this YouTube link: [https://www.youtube.com/watch?v=8Udc8R6yqwU&feature=youtu.be](url)

## Context

The issue limits navigation ability on mobile.

## Your Environment

iPhone 12 mini / iOS 15.0.2

**Comment by wuda-io** [comment]
This has already been fixed.
Make sure you use the newest Version from the new Repo here.

**Comment by JaccoK** [comment]
My bad, used jsdelivr for js but not (yet) for css, so loaded the old css indeed. Thanks!

**Comment by JaccoK** [comment]
I did some tests, but it seems that I need _closeOnClick: false_ to fix the issue I described earlier on mobile phones. Like so:

var elems = document.querySelectorAll('.dropdown-trigger');
var ddOptions = {
	constrain_width: true, // Does not change width of dropdown to that of the activator
	coverTrigger: false,
    inDuration: 0,  
    outDuration: 0,
    hover: false,
    closeOnClick: false
};
var instances = M.Dropdown.init(elems, ddOptions);
