### ISSUE TITLE
CSS only floating Labels

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#222]
Hey I just discovered https://github.com/anydigital/float-label-css
We could implement this in V2, which solves maybe some of the JS-init issues.
Also needs then less code and also no re-initialization of some components and works with only CSS
What do you think?

**Comment by ygorma** [comment]
Is this even foreseen in [Material Design](https://material.io/design)?

**Comment by ivanBell199** [comment]
As far as I can see, this approach doesn't work if there is no placeholder in the input.

**Comment by wuda-io** [comment]
Yes..this library was just an example, to show how we can start. I meant to replace the current floating label with a css-only approach.

**Comment by ivanBell199** [comment]
Yeah, a CSS only solution would be great. I tried to find it some time ago, but no success. There's either a problem with `placeholder `or `required`

**Comment by wuda-io** [comment]
I would suggest to do it with placeholder shown.
In the meantime other frameworks do it also like this,
because it would also be semantically correct and does not require any JavaScript.
I would suggest to solve issues without JS if there is an easy solution available. Wdyt?

**Comment by wuda-io** [comment]
implemented in [v2-dev](https://github.com/materializecss/materialize/tree/v2-dev)
