### ISSUE TITLE
Beer CSS looks similar to materialize, would they want to join us?

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#223]
I am thinking Beer CSS looks similar to materialize and has similar design, do you think they would want to join our framework and maybe we can try to combine them and have a bigger community, more maintainers, and more developers?

Just a thought, let me know your thoughts.

**Comment by LoganTann** [comment]
Very nice idea !

Some contributors even worked for MaterializeCss and switched to beercss due to lack of official support.

**Comment by nh916** [comment]
They both look very similar and beer css is still way newer than materialize it would be nice if we could combine both of them into one big framework that can compete with bootstrap and foundation!

**Comment by LoganTann** [comment]
Yup, but I think they have a different mentality. BeerCSS aims to be very light by using only a small stylesheet, and materialize tries rather to provide strictly material design components for the web.

**Comment by nh916** [comment]
I asked Beer CSS what their thoughts were on combining both frameworks into a bigger and better framework with a bigger community and more support and the answer from them generally seemed positive.

I linked that discussion below
https://github.com/beercss/beercss/issues/20

**Comment by LoganTann** [comment]
The problem with Beer CSS is the philosophy. They aims to be simple and modern by having a light css file. In the other hand, materialize  wants to follow strictly the material guidelines and features as much web components as you may encounter in mobile apps, but at a cost of having a huge codebase.

So I understand why beer CSS contributors wants to stay in their new project. I see this more as a positive concurrency.

Closing this issue, feel free to reopen if needed
