### ISSUE TITLE
Consider support for multiple fab in card ?

### ISSUE THREAD

**Issue by LoganTann** [materializecss/materialize#224]
## Expected Behavior

making two floating buttons in card should display them side by side

## Current Behavior

THe fabs are overlapping each other.

We see two buttons (add and delete) in the code, but in the render, only the delete icon is visible since it's over the add button :

![image](https://user-images.githubusercontent.com/28659185/140737115-a6761e28-a3cb-4c85-b277-7622a5788277.png)

## Possible Solution

Documentation or use of a special class for a container of buttons.

## Steps to Reproduce (for bugs)

1. Create a modal
2. Create two floating buttons

## Context

I want to create a card of an item, then provide multiple actions : add to cart, delete, see the bill...

## Your Environment
* Version used: 1.1.0-alpha
* Browser Name and version: Firefox 94
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ChildishGiant** [comment]
I don't think multiple FABs is ideal. You can set up more buttons within the main FAB: https://materializecss.github.io/materialize/floating-action-button.html
