### ISSUE TITLE
Icons Reference

### ISSUE THREAD

**Issue by ygorma** [materializecss/materialize#225]
As a recomendation, I think it would be nice to include in the [Icons page](https://materializecss.github.io/materialize/icons.html), a link redirecting to the google fonts site in order to make the search for Icons easier via tags, something that it's not supported via Control + F in the icons page. And you may have realized that not all the Icons are present in that page.

Here is the link: https://fonts.google.com/icons?selected=Material+Icons

**Comment by LoganTann** [comment]
Good suggestion, we'll see what other contributors thinks

**Comment by DanielRuf** [comment]
PRs are very welcome.

I think we should replace this long list with a simple link, as you correctly mention the outdated list in our docs.

**Comment by LoganTann** [comment]
> I think we should replace this long list with a simple link, as you correctly mention the outdated list in our docs.

I'm often in the docs while developing with materialize. Isn't providing both is better than a page with a single link ?

**Comment by DanielRuf** [comment]
> I'm often in the docs while developing with materialize. Isn't providing both is better than a page with a single link ?

Generally that would mean we have to actively maintain the list.

**Comment by MadhaviMandalia** [comment]
I want to contribute, please let me know what should be done here? Should I make changes to the list or just provide a link to the icon page?

**Comment by DanielRuf** [comment]
Hi @MadhaviMandalia,

Thank you very much for asking.

> just provide a link to the icon page?

That should be the right solution.

PRs are very welcome.

**Comment by MadhaviMandalia** [comment]
What is the approach you here? Where should I include the link on the icon page?

**Comment by DanielRuf** [comment]
> What is the approach you here? Where should I include the link on the icon page?

You can safely remove the current list and add a text with the relevant link at the same place.

It doesn't have to be perfect. You will get some feedback like change suggestions during the PR review phase. If everything is fine we will merge and deploy the changes.

**Comment by MadhaviMandalia** [comment]
I have removed the icon list but there is already 'Google Icon' link on right hand side marked as `Search Google Icons` so please let me know what changes should I perform.

![image](https://user-images.githubusercontent.com/96095830/146917371-865b20aa-fa3f-4931-881b-09a3aca8b3a7.png)

**Comment by DanielRuf** [comment]
> I have removed the icon list but there is already 'Google Icon' link on right hand side marked as `Search Google Icons` so please let me know what changes should I perform.

This looks good so far.

I would change this:

> We have included 932 Material Design Icons courtesy of Google. You can download them directly from the Material Design specs.

To something like that:

> We use Google Material Icons by Google. They provide a searchable list here (which we do not include in the documentation here), which also shows you the relevant icon names for the CSS classes. You can download the icons directly from the Material Design specs.

Feel free to improve or use a different wording.

**Comment by ChildishGiant** [comment]
Might be worth pointing to [MDIDX](https://jossef.github.io/material-design-icons-iconfont/) over the official repo as it's far more supported.

**Comment by MadhaviMandalia** [comment]
Ok I will include this one.
Thanks.

**Comment by ygorma** [comment]
> I have removed the icon list but there is already 'Google Icon' link on right hand side marked as `Search Google Icons` so please let me know what changes should I perform.
> 
> ![image](https://user-images.githubusercontent.com/96095830/146917371-865b20aa-fa3f-4931-881b-09a3aca8b3a7.png)

I think it's still too discret.. 

The list should be removed.. It does not include all the icons and may induce the user to think that all the available icons are there and hard to seek without tags, or related words.

**Comment by ygorma** [comment]
> > I have removed the icon list but there is already 'Google Icon' link on right hand side marked as `Search Google Icons` so please let me know what changes should I perform.
> 
> This looks good so far.
> 
> I would change this:
> 
> > We have included 932 Material Design Icons courtesy of Google. You can download them directly from the Material Design specs.
> 
> To something like that:
> 
> > We use Google Material Icons by Google. They provide a searchable list here (which we do not include in the documentation here), which also shows you the relevant icon names for the CSS classes. You can download the icons directly from the Material Design specs.
> 
> Feel free to improve or use a different wording.

You don't need to download, they are already included within materialize.

**Comment by DanielRuf** [comment]
> You don't need to download, they are already included within materialize.

It's a reference if you want to download them manually. Materialize does not include these icons. We just reference the Google Fonts there: 

https://materializecss.github.io/materialize/getting-started.html

<img width="795" alt="Bildschirmfoto 2021-12-21 um 18 09 39" src="https://user-images.githubusercontent.com/827205/146970680-64a63ae9-97af-4b94-a6bf-527a6af87634.png">


> The list should be removed..

That's what she currently does.

**Comment by MadhaviMandalia** [comment]
So, should I include change the reference link or everything is fine?

**Comment by DanielRuf** [comment]
> So, should I include change the reference link or everything is fine?

See my previous comments with the suggested changes.

**Comment by MadhaviMandalia** [comment]
Hello @DanielRuf,
The previous changes were already committed and a PR is also raised for it. I was asking about the below comment that does it require any changes? If yes please let me know.

Thanks.


> > You don't need to download, they are already included within materialize.
> 
> It's a reference if you want to download them manually. Materialize does not include these icons. We just reference the Google Fonts there:
> 
> https://materializecss.github.io/materialize/getting-started.html
> 
> <img alt="Bildschirmfoto 2021-12-21 um 18 09 39" width="795" src="https://user-images.githubusercontent.com/827205/146970680-64a63ae9-97af-4b94-a6bf-527a6af87634.png">
> 
> > The list should be removed..
> 
> That's what she currently does.

**Comment by DanielRuf** [comment]
I see no PR at https://github.com/materializecss/materialize/pulls

What I remember and what your PR should contain:
* remove the current list of icons
* add link to the external list
* improve / rephrase the text a bit

No extra changes needed regarding the quoted comment (as this was a clarification that materializecss does not include / ship the icon fonts).

Does this answer your question @MadhaviMandalia?

**Comment by MadhaviMandalia** [comment]
I have opened a PR in this repo please that check it out and let me know is there any change required
Earlier by mistake I've opened a PR in  Dogfalo/materialize  :smiley:

Regards.

**Comment by DanielRuf** [comment]
> I have opened a PR in this repo please that check it out and let me know is there any change required
Here you go: #235

Awesome, will take a look later today.

**Comment by MadhaviMandalia** [comment]
Hello @wuda-io & @DanielRuf ,
Thank you both 😃
