### ISSUE TITLE
our gitter chat seems to be dead, how do we revive it?

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#228]

**Comment by DanielRuf** [comment]
What exactly is meant with "dead"? Does it technically not work or is there not enough activity?

**Comment by nh916** [comment]
There's very little activity

**Comment by LoganTann** [comment]
Creating a discord server for general purpose help may solve this, but may also make the gitter tchat even more inactive
I started a thread in https://github.com/materializecss/materialize/discussions/205

**Comment by DanielRuf** [comment]
How does Discord solve this problem?

In general Gitter integrates with GitHub and shows activity related to PRs and issues.

**Comment by wuda-io** [comment]
I think it would be cool to move forward and get out of the alpha state. Maybe this increases the motivation. Or to add more features. Greets.

**Comment by nh916** [comment]
In general I personally have noticed that Discord tends to be on most programmers computer and always open so its easier to jump in and chat than going to a website, but I could be wrong
