### ISSUE TITLE
Date picker should be input type date Not input type text

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#230]
Our input picker currently works if it is **type text**, but does not work for the more appropriate version of **type date**. 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/26590757/145325256-d3c6dcb9-33d0-47ab-89be-31153bae128c.png">

However, if it is changed to the appropriate, **type date**, then it looks weird and doesn't work as intended. I clicked on the date icon at the right of the date input and both date pickers popped out

<img width="600" alt="image" src="https://user-images.githubusercontent.com/26590757/145325456-0fa4ae4a-6636-4769-b6bd-9dfd80d48c9d.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/26590757/145325480-8f74994c-d593-4ba2-bf9c-ba723b0f6b82.png">

**Comment by LoganTann** [comment]
`<input type="date" class="datepicker" onClick="event.preventDefault()" />`

should do the trick, let me know if it solves the problem

**Comment by nh916** [comment]
Thank you for the amazing and awesome reply!

I have not tried that, but I will take your word for it that it will work. However, making something type text instead of type date when it is a date picker might have accessibility issues in the future.

**Comment by gselderslaghs** [comment]
Looking into this, it does not really makes sense by replacing the date (text type) field with date (date type) field as date formatting is different over continents and could introduce confusion to end-users

In my opinion the most advised way of working with dates localisation is an implementation with the Moment.js plugin and a additional data-format attribute which handles the presentation format

According to the [HTML5 date input specification](https://www.w3.org/TR/2011/WD-html-markup-20110405/input.date.html) that refers to the [RFC 3339 specification](https://www.rfc-editor.org/rfc/rfc3339), as mentioned on [StackOverflow - Is there any way to change input type="date" format](https://stackoverflow.com/a/9519493/21134334) this would improve usability towards accessibility and scenarios where the data is processed by a backend on form submit, as currently only the date text value is processed and does not comply with RFC 3339 format

**Comment by gselderslaghs** [comment]
Date input is available in v2-dev version since #517, this implementation supports backwards compatibility with standard text input field
