### ISSUE TITLE
Radio Button Error: absolute positioning is not responsive and causing errors

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#231]
I was having an extra margin at the bottom of my website after the footer and it was really a bad look and I could not understand why it was there. After looking through all my html in the developers console, I found that the radio button is set as absolute position and as soon as I removed it everything else worked.

here is the piece of code inside our framework that is causing the error. Specifically, the absolute positioning part

```css
[type="radio"]:not(:checked),
[type="radio"]:checked {
  position: absolute;
  opacity: 0;
  pointer-events: none;
}
```
I think absolute positioning tends to cause lots of problems and specially with responsiveness. I think we might be better off if we change absolute positioning to relative or something different

**Comment by LoganTann** [comment]
good point, there is some component who are using a absolute positioning. This is a problem we should consider for the v2

**Comment by Smankusors** [comment]
wait, I'm having a problem imagining your issue, can you please include the screenshots? 😅

**Comment by nh916** [comment]
I cant really share the code but from what I was working on was I had a navbar, form content with radio buttons inside of it, and footer. I noticed that when I added the radio buttons all the sudden the footer was no longer stuck to the bottom but had like 3rem of space after it, so you could scroll past the footer and see the white of the screen. 

I was using css grids to position things and then I set the position to relative and the footer went back to the bottom and you could no longer scroll past the footer.

I think in general absolute positioning would probably mess things up wherever we put it in a responsive css framework

**Comment by nh916** [comment]
I found another one where there is an absolute positioning on `.file-field input[type=file] { `  where it creates issues. 

The code that I am essentially running looks something like this:

```html
<div class="file-field input-field">
    <div class="btn-floating btn-large waves-effect waves-light red" role="button"
         aria-label="File Upload">
        <label for="image_input">
            <i class="material-icons" style="line-height: 1rem; font-size: 1.5rem">edit</i>
            <input id="image_input" type="file"/>
        </label>
    </div>
    <div class="file-path-wrapper">
        <label>
            <input class="file-path validate" type="text" style="display: none">
        </label>
    </div>
</div>
```

the styles materialize is currently applying looks like this:
```css
.file-field input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    width: 100%;
    margin: 0;
    padding: 0;
    font-size: 20px;
    cursor: pointer;
    opacity: 0;
    filter: alpha(opacity=0);
}
``` 

and with absolute positioning here is what I currently get:
<img width="52" alt="image" src="https://user-images.githubusercontent.com/26590757/147908145-4e2c094c-7a6d-4d87-9faf-9b9ffa92d9f7.png">

as soon as I remove `position: absolute;` and replace it with `position: relative;` everything works as expected
<img width="56" alt="image" src="https://user-images.githubusercontent.com/26590757/147908298-60e0d86e-9546-462b-8780-7066f50b314b.png">

this might be just my code so maybe I am doing something different and bumping into this bug, but whenever I see `position: absolute`, it looks like a red flag to me because absolute positioning tends to rarely be responsive.


Also, we might want to transition away from pixels to rem for better responsiveness in the future.

There was a lot of things in this comment so let me know if you want more information or if you want me to make separate issues from the comments here

**Comment by gselderslaghs** [comment]
@nh916 excuse me for my late review on this issue, this seem to be more kind of a wrong setup on your element positioning, according to the [Materialize buttons documentation](https://materializeweb.com/buttons.html) you should place the icon directly in the button wrapper

Adding the correct wrapper classes and removing the inline-styling fixes this issue: [Codepen example](https://codepen.io/Geert-Selderslaghs/pen/JoPbKxb)

Always make sure you check the documentation before opening an issue
