### ISSUE TITLE
Add a reference link to original https://github.com/Dogfalo/materialize

### ISSUE THREAD

**Issue by zw963** [materializecss/materialize#232]
IMHO, i always forget current project url, if search from google, github, always get https://github.com/Dogfalo/materialize

so, should we add a reference link to that site?

**Comment by ChildishGiant** [comment]
If you mean from that site to this one, we have no control over that site.

**Comment by zw963** [comment]
> If you mean from that site to this one, we have no control over that site.

Oops,  maybe we can create a PR for that, and the best way is, transform the controll, and merge together.

Anyway, i consider this is good for the community.

**Comment by Smankusors** [comment]
wait I don't get what do you mean 😅 

PR for what...?

**Comment by zw963** [comment]
> wait I don't get what do you mean sweat_smile
> 
> PR for what...?

A PR for add our link to https://github.com/Dogfalo/materialize README

**Comment by DanielRuf** [comment]
<img width="353" alt="Bildschirmfoto 2021-12-15 um 23 32 27" src="https://user-images.githubusercontent.com/827205/146275149-aea7dcea-552c-4b68-8cb4-505bc27eae97.png">

Can you see the link at the top left?

**Comment by DanielRuf** [comment]
> A PR for add our link to https://github.com/Dogfalo/materialize README

This would be never merged. The maintaoners of the original project are not active anymore and there are many stale PRs.

Closing as we can not do anything here.
