### ISSUE TITLE
Links to contributors' Githubs should be added

### ISSUE THREAD

**Issue by ghost** [materializecss/materialize#239]
I think we should make avatars link to everyone's Github or website (Github might be more appropriate here, and easier to maintain), otherwise they're just nameless icons.

I also think Meet The Team should go above the Material Design explanation or people may not even look at it. 

Link - https://materializecss.github.io/materialize/about.html

Let's all get the credit we deserve, eh? :)

**Comment by christinavoudouris** [comment]
I also think the section should be called Contribute instead of About, and placed underneath Getting Started in the menu. We may also want to consider putting the Material Design stuff under Getting Started instead. But either way, I think contributors should go at the top of the Contribute page.

This should welcome more people to join us, which we need.

I don't have time to work on this right now which is why I'm opening up an issue and not tackling the PR myself. 

Thoughts? Feel free to comment or start a PR.

**Comment by DanielRuf** [comment]
@materializecss/members anyone interested to help with this?

**Comment by MadhaviMandalia** [comment]
Hello @DanielRuf ,
Yes, I would be happy to make this PR.

Hello @christinavoudouris , 
Ya, I think this is a great idea👍. So I will also change the link right hand side where it said `Meet The Team` and `Material Design`.

Thanks & Regards.

**Comment by LoganTann** [comment]
Hehe my contribution to add the avatars wasn't that useful finally
The only downside is that it requires an frequent update (but since there is no extreme activity in terms of PR, this is not a problem), and how may we sort the contributors ?
But I agree 👍

**Comment by MadhaviMandalia** [comment]
@LoganTann good point to be noticed. I think contributors can add his/her avatars on there own so we can update the [`CONTRIBUTING.md`](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md) that we can also attract new contributors 👍

**Comment by createdbyken** [comment]
How specifically we should add our own avatars? I know by PR but like exactly what part could go nice?

**Comment by LoganTann** [comment]
> How specifically we should add our own avatars? I know by PR but like exactly what part could go nice?

At the moment, the "meet the team" section in doc shows automatically the top 20 committers' avatar to this fork

**Comment by CypherpunkSamurai** [comment]
Hello Everyone, 

I noticed the issue has been stalled for a while, can I help with this issue? 😄

**Comment by CypherpunkSamurai** [comment]
I'm thinking maybe a python / bash script can be added which would fetch contributors list from the api. It would run on each push by a github action. This basically automates the process.

**Comment by DanielRuf** [comment]
Why not some existing GitHub Action?

https://github.com/search?q=github+action+contributors
https://github.com/akhilmhdh/contributors-readme-action

This could be even easier: https://contrib.rocks/preview?repo=materializecss%2Fmaterialize

**Comment by CypherpunkSamurai** [comment]
> Why not some existing GitHub Action? 

Yes that'd be even easier using from the marketplace :)
Should i create a draft PR?

**Comment by DanielRuf** [comment]
> Should i create a draft PR?

Even a draft PR is better than nothing. We can still discuss the last details in the PR then and make easy decisions to bring this topic forward.

If anyone has any objections regarding the solution(s), feel free to do a review of the PR then.

**Comment by CypherpunkSamurai** [comment]
Hello Everyone,

I was about to open a new draft pr when I noticed a problem when using a Github Action CI. The `docs.yml` CI action builds the docs and then it pushes the changes back to the source.

The contributors list ci works by replacing strings in the file with html, so when the ci runs once, the second time the strings are overwritten. [sample here](https://github.com/CypherpunkSamurai/materialize/commit/f7c730637b53cb89b572a9f4a482bdffb203a6a8).

I'm currently new to the project and unaware how we publish the docs. Is it using `gh-pages` branch?
Also, Is it possible to handle publishing the docs with another CI that pushes to `gh-pages` instead?

**Comment by DanielRuf** [comment]
> I'm currently new to the project and unaware how we publish the docs. Is it using `gh-pages` branch?

This is https://materializecss.github.io/materialize/

**Comment by CypherpunkSamurai** [comment]
> This is https://materializecss.github.io/materialize/

@DanielRuf, Should we utilize the current `docs.yml` ci and push to `gh-branch` instead?

or should we write a separate ci for that?

**Comment by DanielRuf** [comment]
@CypherpunkSamurai perfect, that should suit our needs. I slightly remember all-contributors from other projects, totally forgot about this (since I have never setup or used it in my projects).

**Comment by CypherpunkSamurai** [comment]
Hello Everyone,
So I just noticed all-contributors auto add feature was not yet implemented, and the PRs were stalling. I had to use a little bit of regex parsing with all-contributors check command to implement an auto add feature.

I've checked the shell script with cases where contributors were empty, missing, and wrong, and it seems to work. The resulting html from the workflow can be seen [here](https://github.com/CypherpunkSamurai/materialize/blob/44411a07a6aa66d245cb0f3253e5e9fa6fdfe0eb/about.html#L186). The updated ci is [here](https://github.com/CypherpunkSamurai/materialize/blob/c3863ae1d2b24b2aa439c60452cb16fbd38fcc9a/.github/workflows/docs.yml#L14)

Please review if this, if it looks alright, or we should search for alternatives :)

*Noteworthy mention: [This article](https://www.yongliangliu.com/blog/all-contributors-cli-recognize-existing/) uses python instead.*

**Comment by CypherpunkSamurai** [comment]
Ok. I'll make a new draft PR soon.

**Comment by wuda-io** [comment]
For me it makes sense to make
- section for the current teams and members of the organization (if you are longer in the team you get rewarded)
- section for all contributors, where everyone who contributed is listed (if you are a new motivated member and made some PRs you get also rewarded) i dont know how to measure the importance of PRs. This is a bit tricky i guess.

**Comment by DanielRuf** [comment]
> For me it makes sense to make
> 
>     * section for the current teams and members of the organization (if you are longer in the team you get rewarded)
> 
>     * section for all contributors, where everyone who contributed is listed (if you are a new motivated member and made some PRs you get also rewarded) i dont know how to measure the importance of PRs. This is a bit tricky i guess.

Personally I think we don't need any metrics or rewards (at the beginning). That has never worked like that in other projects.

Only Gatsby, webpack and a few others did something like collecting contribution points (PRs, issues, ...) via bots / applications and provide a swag store or payouts via opencollective (and this involved some extra work on the implementation logic).

We should just get this done at the moment to have something that works at least.
