### ISSUE TITLE
Request for more transitions

### ISSUE THREAD

**Issue by manuthecoder** [materializecss/materialize#240]
It would be useful if there were more transitions in MaterializeCSS, such as...
* Fade
* Slide
* Scale
* and more...

Thanks!

**Comment by DanielRuf** [comment]
Hi @ManuTheCoder,

thanks for your issue.
In general I think we should not reinvent the wheel and add more transitions. We just provide a basic set of transitions. You can create any transition that you need or you can use some of these:

https://github.com/loadingio/transition.css (animations for transitions)
https://github.com/argyleink/transition.css
https://github.com/animate-css/animate.css
https://h5bp.org/Effeckt.css/
...

Some more can be found by using a search engine: https://bashooka.com/coding/css3-transition-tutorials-libraries/

What do the others think? @materializecss/members

**Comment by LoganTann** [comment]
We may either : 
- ditch the scale transition, so we can remove the animation section in docs
- add more basic animations provided by the material design specs, especially the ones actually used in the lib.

**Comment by wuda-io** [comment]
I think we should add some basic css transitions and remove the animejs dependency.
Also right now some transitions are done by javascript and this should be changed to CSS only.
This is also more performant and faster. So if someone wants to look into this it would be awesome.
