### ISSUE TITLE
(minor) broken placeholder link in Autocomplete doc page

### ISSUE THREAD

**Issue by LoganTann** [materializecss/materialize#251]
In the Autocomplete documentation page, the icon string of the Google autocomplete option points to a dead site.

## Expected Behavior

The google option should show its logo (or an auto-generated placeholder) instead of a broken image

## Current Behavior

Screen : 

![image](https://user-images.githubusercontent.com/28659185/155888531-e6905d24-6a63-457d-8100-bf3d74fec3be.png)

## Possible Solution

Change the image URL in the component's docs and its demo script

## Steps to Reproduce (for bugs)

1. Visit the Autocomplete doc page (https://materializecss.github.io/materialize/autocomplete.html)
2. Type "Google"

## Context

While trying to provide an anwser to issue 250, I visited the doc page and have seen that the google icon is broken.

This is a minor issue.

## Your Environment

Not useful here

**Comment by DanielRuf** [comment]
Does anyone to pick this up? @materializecss/members

**Comment by DanielRuf** [comment]
Does anyone want to pick this up? @materializecss/members

**Comment by RamonvdW** [comment]
Apparently there is a problem loading the image. Console log contains error messages.
The HTML source code of the page shows this:

  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.autocomplete');
    var instances = M.Autocomplete.init(elems, {
      // specify options here
      data: {
        "Apple": null,
        "Microsoft": null,
        "Google": 'https://placehold.it/250x250'
      }
    });

How is this page generated?

**Comment by LoganTann** [comment]
yup, because this link ('https://placehold.it/250x250') is dead.
Changing it to something else will fix this issue, that why I marked it as minor

**Comment by DanielRuf** [comment]
@RamonvdW see https://github.com/materializecss/materialize/blob/main/docs/js/init.js#L181

**Comment by DanielRuf** [comment]
> or an auto-generated placeholder

Then let's do this. Afaik placeholdit changed their domain.
