### ISSUE TITLE
How to contribute financially?

### ISSUE THREAD

**Issue by LukeSavefrogs** [materializecss/materialize#257]
[Original MaterializeCSS](https://github.com/Dogfalo/materialize/) had Patreon, and i used to contribute there, until i found the community mantained version. 
Is it then possible to contribute here? Do you have Patreon or other means?

**Comment by ChildishGiant** [comment]
We're more a loose group of contributors, your best bet would be sponsoring an individual who you think is making meaningful contributions, through whatever methods they have setup.

**Comment by wuda-io** [comment]
Hey finally we have an OpenCollective!
Here you can support us financially: https://opencollective.com/materialize
If we have some budget the next step is to buy a decent domain with an org-TLD.
What do you think?
thanks
