### ISSUE TITLE
No stable version available on the repo?

### ISSUE THREAD

**Issue by pH-7** [materializecss/materialize#259]
I have noticed there was only one version in this repository, and it's a pre-version one. I was wondering the reason why there was no stable versions.

**Comment by LoganTann** [comment]
Hey there,

As the commits made here are almost only fixes, it have to be more stable than the official version (there might be some breaking changes to enforce security of some components though).

Also, there is a release candidate to be published very soon : https://github.com/materializecss/materialize/pulls

Its code will be most likely the same as the last commit in this repo.

**Comment by Smankusors** [comment]
yeah thanks for the reminder, we finally released the 1.1.0 🎉 

let us know if you encountered any issues on 1.1.0 😅

**Comment by pH-7** [comment]
> yeah thanks for the reminder, we finally released the 1.1.0 🎉
> 

Beautiful! That's a great news 💪

> let us know if you encountered any issues on 1.1.0 

Sure, I will. So far, it works like a charm.
