### ISSUE TITLE
NPM readme is still using the old readme

### ISSUE THREAD

**Issue by ChildishGiant** [materializecss/materialize#26]
https://www.npmjs.com/package/@materializecss/materialize

It links to Dogfalo/materialize and has the incorrect quickstart etc

**Comment by DanielRuf** [comment]
This is correct.

I've pushed the original 1.0.0 tag which was linked to the original 1.0.0 release commit.
The readme is pushed with every version. So it was this one:

https://github.com/materializecss/materialize/tree/1.0.0
So in my opinion this is not incorrect.
The first release by us will contain the new readme.md file in the payload sent to npmjs.
