### ISSUE TITLE
Use PopperJS instead of custom Dropdown-Component

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#268]
I have recently switched to PopperJS in my own Projects [PopperJS](https://popper.js.org/) or now called https://github.com/floating-ui/floating-ui
I already saw that Bootstrap is using it for a long time. In Materialize we currently have our own implementation with the Dropdown Component. But what do you think about switch/implementing to this Library since it is well supported and
already after 1 week i see nice improvements.

This solves nested Dropdowns for me, as they were not possible with the current setup.

Here you  can see an example:
![Screenshot 2022-06-01 111329](https://user-images.githubusercontent.com/27806175/171370286-42af608d-1049-4775-9778-963851ca4d63.png)

What do you guys think? Should we implement it?

**Comment by jshster** [comment]
Certainly looks reasonable.  My only concern would be co-dependencies.  What if that project gets abandoned? What does that mean for Materialize?

**Comment by wuda-io** [comment]
Yess you are right, I also like to have no or less dependencies...

We can fork or implement it as a copy, so we dont have to rely on the project.
Also it is very small, so i see not much of a issue here. We can just copy the JS-File.
Also we have dependencies from waves.js as i remeber.

I dont know why Bootstrap is using it as a seperate CDN-Link implementation. Maybe for saving the space.

**Comment by DanielRuf** [comment]
@materializecss/members
