### ISSUE TITLE
formSelect on Card display issues

### ISSUE THREAD

**Issue by jshster** [materializecss/materialize#269]
Discovered some odd behaviour that I can't work out a solution to.
Basically if you place a SELECT input field on a card you cannot see the selection. 

Example here: https://codepen.io/jshster/pen/GRQGroO

If you do view the example to get the drop down to drop down you have to click above the label that says "Pick a number". 
So you can't see the placeholder (first option) or any selected items.

I suspect there will be a CSS solution but I can't work it out.   Seems very odd.

**Comment by AurelienTisserand** [comment]
input-field class is missing in the div which is containing the select select input.

**Comment by wuda-io** [comment]
In your CodePen there is also the initialization of the Select-Component missing.
Put this in your Javascript Box:
`
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, {
      // specify options here
    });
  });
`

**Comment by jshster** [comment]
Oh my goodness.  What a muppet?  Sorry to have bothered everyone.   I swear on the site where I first witnessed the problem that both of the elements mentioned above were present. I will have to double check.
