### ISSUE TITLE
Modal prevent Form Submit

### ISSUE THREAD

**Issue by Jens1985** [materializecss/materialize#274]
I want to submit an HTML form and display a modal during the reload timer. The reload timer is necessary because the transmitted values are checked and saved by the Webserver during this time.

Without the "modal-trigger" class, the HTML form works as expected. But not with the class. The modal is displayed but the HTML form is not submitted.

## Expected Behavior
Form should be submitted and Modal should be displayed

## Steps to Reproduce (for bugs)
https://codepen.io/jens1985/pen/VwXrNKQ
Remove the "modal-trigger" Class on Line 19 and it works fine.

**Comment by Smankusors** [comment]
thanks for submitting the issue. Btw, can you try to reproduce this with version 1.1?

**Comment by Jens1985** [comment]
I tried for several days.

Now I found the error. I forgot a "#" in the href.

Sorry for wrong reporting.

**Comment by Jens1985** [comment]
Hey, yes, I was already using the latest version.

**Comment by LoganTann** [comment]
Hello, sorry for the reply delay

Looks an expected behavior for me. In most cases, the modal trigger may be an anchor or a button, so I believe the original devs puts some `event.preventDefault()` in the code.

### There are multiple ways to solve it, but there is my solution : 

HTML remains same
```html
<form action="/get" target="hidden-form">
  <input type="text" name="ID" value="%ID%">
  <input type="submit" value="Submit" class="btn modal-trigger" href="#modal1">
</form>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <div class="progress">
      <div class="indeterminate"></div>
    </div>
    Daten werden gespeichert...
  </div>
</div>
```

```js
document.addEventListener('DOMContentLoaded', function() {
  var modal = document.querySelectorAll('.modal');
  var instancesModal = M.Modal.init(modal, {
    // since materialize prevent us submitting the form
    // why not executing a function that will do the job ?
    // Here, I defined the onOpenEnd callback to call
    // the below handleOpenEnd function
    onOpenEnd: handleOpenEnd
  });
});

// Nice ! Materialize provide us two parameters : 
// First one is the DOM element of the modal's div
// Second one is the DOM element of the modal's trigger button (input submit here)
function handleOpenEnd(_modalElement, submitElement) {
  // <input type="submit"> always have a .form property, which point to the 
  // form's DOM element.
  const form = submitElement.form;
  if (form) {
    // we submit the form.
    form.submit();
  }
}
```

**Comment by LoganTann** [comment]
Please close this issue if my solution solved your problem

**Comment by Jens1985** [comment]
This worked for me. Thanks :)
