### ISSUE TITLE
dropdown alignment 

### ISSUE THREAD

**Issue by Duplore** [materializecss/materialize#275]
How to change the dropdown modal alignment?

**Comment by Smankusors** [comment]
you can set it with alignment options that mentioned on the docs: https://materializecss.github.io/materialize/dropdown.html

although to be honest, the docs lacks some example about this...

**Comment by Duplore** [comment]
i thought it would go as like alignment: left but that was wrong?

**Comment by CypherpunkSamurai** [comment]
Hello everyone :)

I would like to contribute to this project, can I help add and document a few examples?

**Comment by LoganTann** [comment]
Hello @CypherpunkSamurai, I just assigned you. Feel free to reply || mention me if you have any questions.

**Comment by CypherpunkSamurai** [comment]
Hello @LoganTann, 
I've made a demo JsFiddle Please review: https://jsfiddle.net/a4wy12cp/1/

**Comment by LoganTann** [comment]
Example is good. However, by saying "lacking some example" I think @Smankusors meant we should document the list of possible values the `alignment` property can take.

@Smankusors can you confirm this ?

**Comment by Smankusors** [comment]
yes, that's correct

I forgot this has been 3 months, but there's a posibility that @Duplore asking about different alignment option. Like he expecting left to be outside instead of inside of the button. (correct me if I'm wrong 😅)

either way, we should show what's the difference between the `left` and `right` options in the docs. And spawning the dropdown outside of the button would be considered a feature request.

**Comment by LoganTann** [comment]
Right, so @CypherpunkSamurai you only have to document the possibles values of the alignment option at the moment.

![image](https://user-images.githubusercontent.com/28659185/196030999-b8bd8f5e-4c57-4083-a4c5-24dabb27176c.png)

**Comment by CypherpunkSamurai** [comment]
Ok. Got it.

From [this line](https://github.com/materializecss/materialize/blob/d694828de6df217ccd187b52012017d1d1114aab/js/global.js#L240) what I understand is that there's `left`, `up`, `right` `down` available for all components.

Also, there's SpaceOnLeft etc, is that available for Drop downs?

**Comment by LoganTann** [comment]
I suppose only left and right are supported (stored in horizontalAligment variable in the code), where left is the default

**Comment by Duplore** [comment]
@Smankusors i was thinking of it being inside

**Comment by CypherpunkSamurai** [comment]
Hello everyone,

I've updated the example with two different Drop Down components that drop down left and right each :)

Please check:
https://jsfiddle.net/uckq8yj4/21/

**Comment by Duplore** [comment]
@CypherpunkSamurai seems to be little weird on it, you cannot click on each other really fast

**Comment by CypherpunkSamurai** [comment]
Yes, I just noticed. I'll try to see if I can fix it.

**Comment by CypherpunkSamurai** [comment]
Ok I'll make a draft PR. With the last jsfiddlen
