### ISSUE TITLE
input type "month" has no styling

### ISSUE THREAD

**Issue by icevelez** [materializecss/materialize#277]
input type "month" has no styling

## Expected Behavior
input type "month" will show styling similarly to input type "date" 

## Current Behavior
it does not have any styling

## Possible Solution
I downloaded the materialize source code and added input[type='month'] to where input[type='date'] is. It somewhat works so far and 
I'm new to github so I don't know how to contribute that "fix" if its even considered a fix  

## Steps to Reproduce (for bugs)
1. set input type="month" 

## Context
using input type="month" to send a get request with said month and year value

## Your Environment
* Version used: 1.1.0
* Browser Name and version: Chromium v104.0.5112.79 
* Operating System and version (desktop or mobile): Linux Mint 20.03 Cinnamon

**Comment by LoganTann** [comment]
Note : Input type month is not supported in Firefox and Safari, only in Chromium-based browsers.

We need to decide which design to choose. In meantime, have a look at https://materializecss.github.io/materialize/pickers.html

**Comment by Smankusors** [comment]
wait, does #270 fixes this?
