### ISSUE TITLE
`striped` does nothing on tables anymore

### ISSUE THREAD

**Issue by rmehner** [materializecss/materialize#279]
## Expected Behavior

Applying `striped` to a `<table>` should make the rows striped based on odd/even.

See this screenshot from 1.0.0 documentation: ![expected](https://user-images.githubusercontent.com/82050/191281147-e06ac15a-ea38-4dd8-9379-1827f5c79c82.png)

## Current Behavior

It does nothing. Table stays unstriped. `highlight` does work as expected though. You can see it not working on the official docs too: https://materializecss.github.io/materialize/table.html (compare with v1.0.0 here: https://materializecss.com/table.html)

Screenshot from current documentation: ![current](https://user-images.githubusercontent.com/82050/191281130-5b2a14d9-dc4f-417e-98c3-6f061bb016ee.png)

## Possible Solution

The offending commit and the lines are here: https://github.com/materializecss/materialize/commit/55e4854de63c5faf2a495453d7ed5399ff4322cf#diff-7d50d61152c39227f20098330f8691eee64bbf47d6f0e8df9225a30587b930d0L411-L420 ... it was removed. Don't see any reasoning behind it, but I might be missing context. Given that it's documented other wise, it's either a matter of removing that from the documentation or to bring those lines back in.

My current solution is to add those line into the application scss.

## Steps to Reproduce (for bugs)

1. Go to https://materializecss.github.io/materialize/table.html 
2. Click on "Striped" on the navigation on the right

## Your Environment

* Version used: 1.1.0
* Browser Name and version: Chrome Version 105.0.5195.125 (Official Build) (x86_64
* Operating System and version (desktop or mobile): macOS 12.6

Thank you!

**Comment by Smankusors** [comment]
Thanks for pointing this out 😃 

Hmm... reading this commit message also doesn't make sense to me, so I'm not sure what's going on there 😅 

I think we should bring back the `> tbody > tr:nth-child(odd)` rule only, since I don't see the other rules affect things? What do you think?

Would you like to create the PR to fix this?

**Comment by rmehner** [comment]
> I think we should bring back the `> tbody > tr:nth-child(odd)` rule only, since I don't see the other rules affect things? What do you think?

At first I was thinking about also including the reset of the border-radius, but since it's also gone for the highlight-case, I think it's better to only include the tbody rule. So yeah, I agree 😄 

> Would you like to create the PR to fix this?

I just did with #282.

Thanks for coming back to me. Let me know if I should adapt anything and thanks for your work so far! 👍🏿
