### ISSUE TITLE
react/nextjs : Select tag renders twice ー one default(browser) and materialize one 

### ISSUE THREAD

**Issue by helioxy** [materializecss/materialize#281]
### Expected Behavior
default(browser) select should be hidden

### Current Behavior
is not hidden

### Possible Solution
set the  select tag inside <div className="input-field">  to display: none

### Steps to Reproduce (for bugs)
full component code: 
```
const TimezoneDropdown = (props: Props) => {
  const ref = useRef(null);

  useEffect(() => {
    const elem = ref.current;
    let M;
    if (typeof window !== 'undefined') {
      M = require('materialize-css');
    }
    M.FormSelect.init(elem, { inDuration: 300, outDuration: 225 });
  }, []);

  return (
    <>
      <div className="input-field">
        <select defaultValue={1} ref={ref}>
          {Object.keys(CL_FORMAT_TIMEZONE_OPTION).map((option) => (
            <option value={option} key={option}>
              {CL_FORMAT_TIMEZONE_OPTION[option]}
            </option>
          ))}
        </select>
        <label>タイムゾーン</label>
      </div>
    </>
  );
};

export default TimezoneDropdown;
`````

### Your Environment
Version used: 1.0.0
Browser Name and version: [Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (arm64)]
Operating System and version (desktop or mobile):  M1 ,macOS Monterrey 12.5

**Comment by Smankusors** [comment]
have you tried with https://github.com/react-materialize/react-materialize ?

**Comment by helioxy** [comment]
Thank you. Read [the same implementation in react-materialize
](https://github.com/react-materialize/react-materialize/blob/master/src/Select.js) and since the logic is similar to mine, the problem must be something else.
I will look into it later so closing this now.
