### ISSUE TITLE
Standard spacer classes

### ISSUE THREAD

**Issue by MacGyer** [materializecss/materialize#309]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

When building a website with Materialize, I felt the need of spacer classes to incorporate spaces between elements in a framework defined way.

Say you have a website which displays two areas with text. Now you want to add some padding or margin. You have to define your spacer classes to add padding/margin. Of course, with SCSS you can derive those from the gutter-width or similar.

But it would be nice to provide standard spacer classes like p-0, p-3, py-4 (and margin respective) to add spacing wherever you want. Compare to Bootstrap (oh no, I said the bad word ;)).

Those spacers can be generated depending on breakpoints, to provide different spacers on the different screen sizes.

### Current Behavior

No classes provided, must be defined manually (and for every project again).

### Possible Solutions or Causes

Provide a set of classes for margin, padding (and even other suitable properties).

https://codepen.io/macgyer/pen/VwdBmrL

https://getbootstrap.com/docs/5.0/utilities/spacing/

### Your Environment

* Version used: 1.1.0
* Browser Name and version: Firefox, current version
* Operating System and version (desktop or mobile): Win 10

**Comment by DanielRuf** [comment]
I'm not sure if this makes sense for materializecss since this would mean much more code that is unused. You can use Tailwind CSS + purgecss (integrated in Tailwind CSS) for this, which covers this much better.

We should not try to replicate Tailwind CSS or other utility frameworks.

**Comment by MacGyer** [comment]
Thanks for clarification. And good to see you being back :)
