### ISSUE TITLE
dropdown.js still has the problem of misaligned taps

### ISSUE THREAD

**Issue by nekonenene** [materializecss/materialize#31]
Dogfalo has fixed `select.js` to resolve the problem of the recognizing position of tap on iOS 13. Meanwhile, dropdown.js still has a such problem.

https://github.com/Dogfalo/materialize/commit/c0da34049deec36efbd4681f73b3446e92918ca8#commitcomment-36941624

I know this problem causes from the strange behavior of iOS 13 (and 14). https://developer.apple.com/forums/thread/120586

My current idea is to use`'ontouchend' in document.documentElement` to check if the browser supports _ontouchend_ and use this event if suppports. If not, then use the _onclick_ event. Though it will work well, I'm not sure if I can spend time solving this, so I wrote it down in this issue anyway.

**Comment by DanielRuf** [comment]
Hm, is there maybe already a relevant PR in the original repo or some issue with proposed solutions by others?

If not we have to see which approach is the best and correct one to resolve this in Safari.

**Comment by nekonenene** [comment]
I searched for "dropdown" in the original repository, but couldn't find any pull request to solve this problem...

**Comment by DanielRuf** [comment]
Ok, and no related issues with solutions by anyone?

If so we have to discuss what the best solution would be.

cc @materializecss/members

**Comment by Smankusors** [comment]
iOS 13 and later.... unfortunately I don't have such device to try it out 😢

**Comment by nekonenene** [comment]
@Smankusors 
Oh... 😢 If you have a macOS computer, you can test with iOS Simulator using Xcode.

**Comment by Smankusors** [comment]
> @Smankusors
> Oh... 😢 If you have a macOS computer, you can test with iOS Simulator using Xcode.

I don't have that either haha..... but is this also happens on Safari MacOS tho?

**Comment by nekonenene** [comment]
@DanielRuf 
https://github.com/Dogfalo/materialize/issues/6514#issuecomment-594657199
I found the simplest solution in this issue, but I have to check if this affects other parts carefully.

**Comment by DanielRuf** [comment]
> iOS 13 and later.... unfortunately I don't have such device to try it out cry

We can probably test on browserstack.com/

**Comment by nekonenene** [comment]
@Smankusors 
This happens only on iOS. Safari on desktop doesn't have the ontouchend event.

@DanielRuf 
I didn't know browserstack.com until now. Great!

**Comment by guizuliani** [comment]
Here #6414, @StaticBR registered the solution for this problem. I tested in iOS13 and it worked for me.

Patch file: [patch_ios13_bug.txt](https://github.com/Dogfalo/materialize/files/4288553/patch_ios13_bug.txt)

**Comment by alberto115** [comment]
Hey everyone, 

I can confirm the changes works on iOS 13 and iOS 14, however the correspoding lines on the patch has changed.

Here is a file with the correct lines based on the latest v1-dev branch: [materializecss-dropdowns.txt](https://github.com/materializecss/materialize/files/5346194/materializecss-dropdowns.txt)

**Comment by AJLeonardi** [comment]
> @DanielRuf
> [Dogfalo#6514 (comment)](https://github.com/Dogfalo/materialize/issues/6514#issuecomment-594657199)
> I found the simplest solution in this issue, but I have to check if this affects other parts carefully.

has this solution been tested across the board yet?

**Comment by AJLeonardi** [comment]
Hey folks, can anyone help me resolve this dropdown issue? I'm using the cdn version of materialize and I'm not sure what the process is to patch it on my end to get working files. Once I have that I'm gtg and can serve them up myself while I wait for the official fix. I just have no idea how to create the patched files. Thanks!

**Comment by guizuliani** [comment]
> Hey folks, can anyone help me resolve this dropdown issue? I'm using the cdn version of materialize and I'm not sure what the process is to patch it on my end to get working files. Once I have that I'm gtg and can serve them up myself while I wait for the official fix. I just have no idea how to create the patched files. Thanks!

Download the file dropdown.js, remove the two lines e put the file in your project.

**Comment by AJLeonardi** [comment]
awesome. Thanks, @guizuliani !

**Comment by guizuliani** [comment]
> awesome. Thanks, @guizuliani ! any issue grabbing the current version of dropdown.js from the repo - or would I need to go back to the version from the latest release?

You can get the current version of dropdown.js from the repo.
