### ISSUE TITLE
[Bug]: Overflow on html element breaks dropdown placement

### ISSUE THREAD

**Issue by sgiehl** [materializecss/materialize#311]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Dropdowns should automatically being placed at the best available position. This normally works nicely. 
Our page is using a `overflow-y: scroll` on the `html` element, to ensure the scrollbar is always shown, even if it isn't scrollable.
This breaks the positioning of dropdowns.

### Current Behavior

When opening a dropdown that is being placed on the lower or righter end of the visible page, the dropdown is always opened below and aligned left, even if that makes the page bigger/wider.

### Expected behavior

The dropdowns should open the default way, looking where the space fits best.

### Possible Solutions or Causes

When checking for the best placement, the dropdown js tries to look for the closest ancestor having an overflow not being visible.
I don't think checking the html element in that case makes much sense.

Testing locally it was enough to exclude `html` element from this check: https://github.com/materializecss/materialize/blob/505f8d46eb0d78bc8116f795306051fafb6ff8d8/js/dropdown.js#L564-L566

### Steps to reproduce

1. Go to https://materializecss.github.io/materialize/select.html
2. Use the browser console to give the html element a `overflow-y: scroll`
3. Open one of the selects that is placed in the end of the visible screen
4. The dropdown will be opened below, even though above would be the better place.

### Your Environment

* Version used: 1.2.0
* Browser Name and version: Chrome or Firefox
* Operating System and version (desktop or mobile): Windows 10
* Additional information you want to tell us:

**Comment by sgiehl** [comment]
Any comments on that one? I've created small codepen for that bug: https://codepen.io/sgiehl/pen/GRBLJEe
Opening the select, currently lets the selection being displayed partially out of the visible space.
Removing the `overflow-y: scroll` makes the select behave correctly...
Similar problem occurs when moving the scroll to the body element. 

I'd be happy to provide a PR to fix this, if it's a valid solution to exclude `html` and `body` element from the check that looking for the next parent that has an `overflow != visible`

**Comment by wuda-io** [comment]
Yes that solution sounds good, I think a PR is nice!
I hope this does not bring problems with a dropdown inside a modal? But I think it should be fine.
Would be happy to merge :) Thanks
