### ISSUE TITLE
[Bug]: page jittered when sidenav slide out

### ISSUE THREAD

**Issue by lindeer** [materializecss/materialize#317]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

page with scrollbar showing, when click menu and sidebar slide out, scrollbar hide, this behavior make whole page jitter.

### Current Behavior

scrollbar hide
navbar:
```html
  <body>
    <div class="navbar-fixed">
    <nav>
      <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large">
        <i class="material-icons">menu</i></a>
      <div class="nav-wrapper">
        <ul id="nav-mobile" class="left">
          <li>
            <a class="waves-effect waves-light">
              <i class="material-icons">arrow_back</i></a>
          </li>
          <li>
            <a class="waves-effect waves-light">
              <i class="material-icons">arrow_forward</i></a>
          </li>
        </ul>
        <span href="#" class="brand-logo center">Title</span>
      </div>
    </nav>
    </div>

      <ul id="slide-out" class="sidenav">
        <li class="chapter " data-level="1.1" data-path="..">
          <a href="..">
            <b>1.1</b>前言</a>
        </li>
        <li class="header">第一章 霍亨斯陶芬的衰落</li>
        <li class="chapter active" data-level="2.1" data-path="section1.html">
          <a href="section1.html">
            <b>2.1</b>序幕</a>
        </li>
        <li class="chapter " data-level="2.2" data-path="section2.html">
          <a href="section2.html">
            <b>2.2</b>幼年</a>
        </li>
       </ul>

    <main class="demo-main container">
      <div class="card-panel">
        <div class="demo-content">
          <div>
            Google &gt; Material Design Lite &gt; How to install MDL
          </div>
          <h3>How to install MDL</h3>
          <p> a lot of content to make scrollbar show ... </p>
        </div>
      </div>
    </main>
```

### Expected behavior

scrollbar not hide

### Steps to reproduce

![影院20221206155543](https://user-images.githubusercontent.com/6064524/205854351-17bb8518-de15-4d66-a662-edca5413cfff.jpg)
![影院20221206155557](https://user-images.githubusercontent.com/6064524/205854361-6c1568e9-a875-4d0f-beb2-fc0a0d3a2946.jpg)

### Your Environment

* Version used: 1.0.0
* Browser Name and version: Chromium 89.0.4389.114 (Developer Build) built on Debian 10.9, running on Debian 10.5 (64-bit)
* Operating System and version (desktop or mobile): Linux 4.19.71-arm64-desktop
* Additional information you want to tell us:

**Comment by Smankusors** [comment]
hmm what do you mean by "jittered"?

**Comment by lindeer** [comment]
@Smankusors sorry for my bad description, the scrollbar's incorrect hiding made the page's width changed, resulting in visual discomfort

**Comment by lindeer** [comment]
I think I find the root cause:  the `overflow: hidden` style make the scrollbar hidden, which is set by code (materialize.js:6244):
```js
      key: "_preventBodyScrolling",
      value: function _preventBodyScrolling() {
        var body = document.body;
        body.style.overflow = 'hidden';
      }
```
not sure if it is necessary.

**Comment by Smankusors** [comment]
ah, now that you mentioned `_preventBodyScrolling`, I found this
https://github.com/materializecss/materialize/blob/68e7cf99cfd523d6e665e748e2512732abd9a32a/js/sidenav.js#L440-L442

you can disable the scrollbar hiding by setting the `preventScrolling` option to `false`. For example
```
$('[your sidenav selector]').sidenav({
  preventScrolling: false
});
```

more information [here](https://materializecss.github.io/materialize/sidenav.html#options)

**Comment by lindeer** [comment]
Great! it works! thanks @Smankusors , initialized code just as below:
```js
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.book-summary');
        var instances = M.Sidenav.init(elems, {
          preventScrolling: false,
        });
      });
    </script>
```
