### ISSUE TITLE
[Bug]: LinkedIn IFrames not expanded in MaterializeCSS

### ISSUE THREAD

**Issue by sisaha9** [materializecss/materialize#328]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

LinkedIn IFrames are a great way to show featured posts on a website. I am trying to integrate some posts I have been featured in. However, they appear minimized in height instead of being longer like the other sections of websites

### Current Behavior

LinkedIn posts/iframes don't expand in height

### Expected behavior

The height be controllable so that I can set a base size and have it rescaled responsively

### Steps to reproduce

https://codepen.io/sisaha/pen/poZQMxe

### Your Environment

* Version used: Latest
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Both
* Additional information you want to tell us:

**Comment by Jerit3787** [comment]
Hi @sisaha9, I would like to ask why you put the iframe inside `video-container`? This is clearly not a bug in materialize but rather a problem on your side. Please do understand the HTML language first before trying to do anything. The issue before this shouldn't be asked if you would understand your own code better. Please this is not a support page. If you need it, you can google it. There is a lot of resources online including stackoverflow to help you out with this issue. From what I've seen, this webpage has minimum width as well so it can't be restricted its width. And for the height, I don't quite understand why you put it inside the `video-container` div. The video container clearly has css that restrict it's height. So please do your own research first before opening an issue. Here is only if there is a bug regarding the materialize code set.

ALSO, THE VERSION YOUR USING IS THE OLD ONE! ours already reached v1.2.1. CDNJS doesn't have ours version of materialize. Please recheck the documentation.

Thanks with regrads.
