### ISSUE TITLE
Removing noUiSlider

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#353]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Do we need this Plugin? If yes for what?
I would remove it for the next release. Please comment here if there is any need in keeping this Plugin.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Additional information you want to tell us:

**Comment by wuda-io** [comment]
implemented in [v2-dev](https://github.com/materializecss/materialize/tree/v2-dev)

**Comment by pfafman** [comment]
What is your alternative for this?  HTML5 range does not do a dual selector without a fair bit of code.
