### ISSUE TITLE
Sidenav from right side

### ISSUE THREAD

**Issue by jshster** [materializecss/materialize#354]
Hey guys,
I'm not sure if this should go in the Issues or Discussion but according to the doco to get the Sidenav sliding in from the right I supposedly only need to use "edge: 'right'" in the configuration. 

I've done that but nothing changes.   Only way I could get it to switch to the right side was to modify the CSS but now I have a weird issue where it's still sliding out from the left .... and when I toggle it to disappear it remains in the screen albeit to the left of the "slideout" position.

I've reviewed all of the doco.... I am missing something but I can't quite work it out?

I'm using 1.2.2 so the latest version.  Trying to decrease the dependence on jQuery so have removed that too.  

PS - Just picked up on some of the extra doco added.  Great job guys.  Much more thorough than the original.  Just missing my little issue!

**Comment by wuda-io** [comment]
Hey @jshster, currently the docu and the release is out of sync.
I am trying to figure out how to make a proper versioning to keep the old 1.2.1 docu with the next release.
In the next release there will be no jquery, so good when you are reducing it :+1: 
have a nice weekend! cheers

**Comment by jshster** [comment]
Hey @wuda-io I don’t suppose you have any input into the issue I’m having?  Or are you saying there is doco that explains what I need to do somewhere?

thanks

**Comment by wuda-io** [comment]
Hey @jshster I just have tested it in the development branch and there it works for me.
Soon, there will be an 1.0.2-alpha release with the new M3-Specs too for the Sidebar.

Please provide a sandbox or code sample. I used the sample from the docs and this code which worked:
```javascript
  document.addEventListener('DOMContentLoaded', function() {
    let elems = null, instances = null;

    elems = document.querySelectorAll('.sidenav');
    instances = M.Sidenav.init(elems, {
      // specify options here
      edge: 'right'
    });

      elems = document.querySelectorAll('.collapsible');
      instances = M.Collapsible.init(elems, {
        // specify options here
      });
    });
``
