### ISSUE TITLE
[Bug]: Inconsistent behaviour when Datepicker has an implicit label

### ISSUE THREAD

**Issue by kisatan** [materializecss/materialize#356]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

When the field of the datepicker is the child of a `label` node (implicit label) the controls in the title portion behave differently than when no label is used, or the label is set explicitly via the `for` attribute.

### Current Behavior

With implicit label in Edge, Chrome and Opera:

- Clicking on the button for previous month goes back 2 months
- Clicking on the button for next month does nothing
- Clicking on the space in between the buttons and the month/year dropdown goes back one month (on both sides of the dropdowns)

With implicit label in Firefox:

- Clicking on the space in between the buttons and the month/year dropdown goes back one month (on both sides of the dropdowns)

### Expected behavior

I expected the behaviour to match the one exhibited on all browsers with explicit or no labels:

- Clicking on the button for previous month goes back 1 month
- Clicking on the button for next month goes forward 1 month
- Clicking on the space in between the buttons and the month/year dropdown does nothing

### Steps to reproduce

1. Open https://codepen.io/kisatan/pen/JjmPjvV
2. See how the first datepicker behaves differently from the second and third

### Your Environment

* Version used: I have noticed it first in version 1.0.0, but the codepen uses 1.2.2 I believe
* Browser Name and version: Edge 111.0.1661.62, Chrome 111.0.5563.147, Opera 97.0.4719.43, Firefox 111.0.1
* Operating System and version (desktop or mobile): Windows 10 Pro Education Version 21H2
* Additional information you want to tell us:

**Comment by zetabug** [comment]
@kisatan I checked the codepen, i think it is working fine. let me know if i am missing something.

**Comment by kisatan** [comment]
> @kisatan I checked the codepen, i think it is working fine. let me know if i am missing something.

Thanks for checking.

I also can't reproduce it on my Linux machine anymore.

From experimenting with the imported version, it looks like it was fixed with the `2.0.0-alpha` release.

I'll confirm on Wednesday when I have access to my work PC with Windows again (where we had the issue initially) and close or update as appropriate.
