### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by redz1029** [materializecss/materialize#357]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Chips Autocomplete Options does not work as expected.

### Current Behavior

When typing an item that exists from autocompleteOptions, no suggestion box/dropdown content shows.

### Expected behavior

It should show suggestion box.

### Your Environment

* Version used: 1.2.2
* Browser Name and version: Google Chrome Version 111.0.5563.147 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 11
* Additional information you want to tell us: Please see the attached file to replicate this issue. Thanks
[chip-test.zip](https://github.com/materializecss/materialize/files/11206038/chip-test.zip)

**Comment by wuda-io** [comment]
Please provide a sandboxed code example and also use a title for the issue.
Also use more description what you did and what is not working.

**Comment by mauromascarenhas** [comment]
I've checked the attached source, and it is actually working.

The only thing you will have to update is the "data" option. The structure you are using is only available since Materialize v2. For the "correct" format in v1.x, you may check the [old documentation](https://materializecss.com/chips.html#options).

Terefore, in order for the plugin to work, you will have to replace:

```js
$('.chips-autocomplete').chips({
    autocompleteOptions: {
        data: [
            { id: 12, text: "Apple" },
            { id: 13, text: "Microsoft" },
            { id: 42, text: "Google", image: 'http://placehold.it/250x250' }
        ]
    }
});
```

by:

```js
$('.chips-autocomplete').chips({
    autocompleteOptions: {
        data: {
          "Apple": null,
          "Microsoft": null,
          "Google": 'http://placehold.it/250x250'
        }
    }
});
```
