### ISSUE TITLE
Typo in Documentation for Floating Action Button

### ISSUE THREAD

**Issue by mud-ali** [materializecss/materialize#358]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

![image](https://user-images.githubusercontent.com/96320211/232173660-922aaecf-6ac9-4d7c-b474-f8a6f85c30c1.png)

[https://materializecss.com/floating-action-button.html](https://materializecss.com/floating-action-button.html)

### Current Behavior

For the direction option:
```
Can be 'top', 'right', 'buttom', 'left'
```

### Expected behavior

This should be changed to 
```
Can be 'top', 'right', 'bottom', 'left'
```

### Your Environment

* Version used: 4/14/2023
* Browser Name and version: Mozilla Firefox 112.0
* Operating System and version (desktop or mobile): Windows 11

**Comment by mud-ali** [comment]
i closed this upon realizing I was looking at an older version of the site 😅

...but i then just realized that it is still linked on the new one (presumably reference for the older version of the library) and wouldn't hurt to still fix. Not sure where the source is for that, though.

**Comment by CypherpunkSamurai** [comment]
Hello @mud-ali, thank you for reporting this issue.

The spelling was corrected in recent version. I'm unsure which older version might have the issue 

Would you please let us know the version?
Note that the current documentation for floating action bar is:

https://github.com/materializecss/materialize/blob/main/pug/page-contents/floating-action-button-content.html

**Comment by wuda-io** [comment]
Thank you it is now fixed. See here [https://materializeweb.com/floating-action-button.html](https://materializeweb.com/floating-action-button.html)
