### ISSUE TITLE
Feature request: Search/Filter bar in the multi-select Select form component

### ISSUE THREAD

**Issue by computerwiz12890** [materializecss/materialize#36]
Would love to have the option to **_easily_** add a Search/Filter bar at the top of the multi-select dropdown boxes.  

![image](https://user-images.githubusercontent.com/67020697/94196552-25b05600-fe7a-11ea-86d5-3558abe72361.png)

The above screenshot is using Bootstrap's Multi-Select plugin.  So I am looking for that same functionality from Materialize.  Here is a live example of how it works: https://www.jquery-az.com/boots/demo.php?ex=63.0_9

Thanks!

**Comment by DanielRuf** [comment]
I'm not sure if Google Material Design specifies something like this.
https://material.io/components/text-fields

I think it is the Autocomplete component but with different options / entries.
https://materializecss.com/autocomplete.html

**Comment by computerwiz12890** [comment]
Yeah, I looked at Autocomplete and the existing Select "multi" function.  There is nothing currently that fully meets my needs.  The existing Select "multi" is very close...it just needs the filter bar.  And as you type in the bar, the list shrinks to only what matches.  If that could be added, that would perfect!

**Comment by 4lenz1** [comment]
I'm not familiar with materialcss code, but there is a thread talking about this topic and gave temp  solution before. Hope it helps and can integrate into new features in the future ：D 


https://github.com/Dogfalo/materialize/issues/3096#issuecomment-621497307

**Comment by Cherrg** [comment]
Hi, I added some features to the script, linked above:

- nicer handling of optgroups -> hide if no child matches search pattern, show optgroup if it has at least 1 visible child
- handle keyboard navigation
   - handle ArrowUp + ArrowDown focus selection
   - grab focus when open event was triggered by keyboard
- supports multi select

You can find a demo here https://jsfiddle.net/cherrg/vgn3Law4/
The code could be found here: https://github.com/Dogfalo/materialize/issues/3096#issuecomment-778513315

Sorry for the duplicate with the referenced issue, but here are some maintainers :) may this feature finds its way into the code.
If you find some bugs or possible improvements (or suggestions) to the behavior of this script, please comment.

(May I will build an update for materializecss and create an PR after some time.)

**Comment by DanielRuf** [comment]
Thank you, this looks good =)

> May I will build an update for materializecss and create an PR after some time

That would be awesome 👍

**Comment by DanielRuf** [comment]
@LoganTann I would say this is out of scope of the Google Material spec so this should be some separate package.

I would vote to close this issue. What do you think @materializecss/members

**Comment by DanielRuf** [comment]
@computerwiz12890 sure, but otherwise we would end in feature creep, adding more and more features to materialize which introduce new problems, need more tests and so on.

Generally we should check what the other members think about this, that's why I've mentioned the members of the org.

If there is a PR that can be reviewed (even if it is unfinished or a draft) that would be helpful because getting feedback as early as possible is very important.

At the moment v1 and the v1.1 release are meant to fix bugs. New features will be introduced in v2, which will be the new default branch after the v1.1 release.

**Comment by LoganTann** [comment]
In my opinion, adding a basic search feature as option is a good idea. For the more advanced ones, we can separate that in another package.

The material based framework Vuetify features this, but in a separate component called "[autocomplete](https://vuetifyjs.com/en/components/autocompletes/#asynchronous-items)".
