### ISSUE TITLE
M.textareaAutoResize function missing in the release 2.0.0-alpha

### ISSUE THREAD

**Issue by OlivierMadant** [materializecss/materialize#362]
Hi,

The function M.textareaAutoResize() is no longer accessible in the release 2.0.0-alpha
That function is described in the textarea documentation as the function we need to execute when dynamically changing the value of a textarea.

Is it because now the Textfields are css only in 2.0.0-alpha? 
In this case, perhaps the documentation should be adapted?

Thank you for this new version and your excellent work,

Olivier

**Comment by OlivierMadant** [comment]
Hello,

The problem is still present with the version 2.0.1-alpha.
The function M.textareaAutoResize() was working properly before the release 2.0.0-alpha. 

The function still seems necessary because the height of the textarea is not updated when dynamically changing the value of a textarea.


We can reproduce the issue really simple by navigating to [https://materializeweb.com/text-inputs.html](https://materializeweb.com/text-inputs.html)
And execute in the console:
`document.getElementById('textarea1').value = 'Hello \nMaterialize\nTeam.\nThis\nframework\nis\nawesome!'`



Thank you again for your excellent work,

Olivier

**Comment by FewCryptos** [comment]
Hello,
The function M.updateTextFields() was also removed, but still need to be used.
Thank you

**Comment by mauromascarenhas** [comment]
Hello,

I've checked the repo and, in fact, those functions have been removed (probably durin the transition from JS to TS + jQuery removal).
I'll try to reimplement them asap.

Thank you for your feedback :)

**Comment by wuda-io** [comment]
Hello, I removed _updateTextFields_, because it is no needed anymore.
The Label-Animation is now fully done in CSS.
The only thing needed now is a placeholder Attribute in the Inputs. I see that this i missing in the documentation.
This needs a documentation update.

**Comment by mauromascarenhas** [comment]
As of #382. this issue must be resolved :smile:

**Comment by OlivierMadant** [comment]
Thank you so much for fixing the issue and updating the documentation!
