### ISSUE TITLE
CI/Documentation: Handling Pull Requests

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#367]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

We should update Documentation: **Every** new PR should be included in the Dev Branch.

I mistakenly wrote in the documentation, that Fixes should be merged into Main and Improvements should be merged into Dev, but I think we should ALWAYS merge every PR into dev-Branch. In the longer term we should merge from DEV -> MAIN only when a new release is done.

What do you think? I would update the documentation accordingly.

### Current Behavior

Different process for a FIX and FEATURE.

### Expected behavior

ONE process for every change.

### Possible Solutions or Causes

Base PRs always from dev branch.

**Comment by DanielRuf** [comment]
> In the longer term we should merge from DEV -> MAIN only when a new release is done.

Exactly my thought.
