### ISSUE TITLE
Moving to Beta

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#403]
Moving to beta release we should consider following things:

- [x] Using as modular components see #44 
- [ ] Removing the color palette CSS from the core and load it optionally. Only use Primary/Secondary Colors. This would save a lot of space and bandwidth.
- [ ] Make Components more like M3 Design and use appropriate css-variables (Switches, Cards, SideNav)
- [ ] Remove the generated GUIDs of IDs and dynamically re-created Elements (This creates a lot of problems e.g. in React and in general for DOM Manipulations) #393 

I will update this list if you have important things to consider. We can discuss here.

**Comment by InitialCrow** [comment]
How is my issue #398 my fix  #399 considered ? I think it is necessary to fix the events for function with React and other frameworks of this type, currently using it on a project I need to have a state to know if I have to go back to V1 or if I can work with my fork while it is considered. I think it should be considered for the beta or even before thank you and sorry if the message is not correct place

**Comment by InitialCrow** [comment]
@wuda-io hi again can I have AN ETA of considering my issue/pull request please thank you.

**Comment by wuda-io** [comment]
Hey @InitialCrow 
Thanks for your contribution to Materialize. Your change looks good and I will merge it in!
Glad to have you on board and welcome 🤝

**Comment by InitialCrow** [comment]
@wuda-io thank ya 🙏
