### ISSUE TITLE
Improvement of icon

### ISSUE THREAD

**Issue by adamrusted** [materializecss/materialize#405]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

The current SVG icon used on the docs homepage has a lot of imperfections. We'd like to include a variation in [Simple Icons](https://github.com/simple-icons/simple-icons) but we're struggling to work with the current SVG. Some of our other contributors have found [tidied versions](https://seeklogo.com/vector-logo/296808/materialize) of the logo online - and I was wondering if there was any interest in fixing up the logo. It's a minor thing, but will likely save on some file size every time the logo is loaded.

**Comment by wuda-io** [comment]
Hello @adamrusted  I did not notice it until now and I will look into it and change it soon.
Thanks for the suggestion! Can we support your project anyhow?
We also would be glad if you link our project too. Thank you!

**Comment by wuda-io** [comment]
I fixed the Logo and it will be in the next release. Thanks for the clear communicated issue.
