### ISSUE TITLE
Spacing helper classes in CSS

### ISSUE THREAD

**Issue by manusandoval05** [materializecss/materialize#407]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

It is generally very simple to configure spacing horizontally by just adding gap to the element style. However, vertical alignment is sometimes complicated. Would it be possible to implement helper spacing classes to the SCSS, with classes such as margins and paddings with the m and p prefixes, t, r, b, l, x, y infixes and number suffixes, to configure spacing per component?

### Current Behavior

No component specific spacing helpers

### Expected behavior

To be able to add utility classes per component to configure spacing manually, such as mt-3, px-2, and so on.

**Comment by wuda-io** [comment]
Hello @manusandoval05 
yes this was requested some while ago. But actually I think now it is a good idea.
Because in Version 2 we updated to the Grid Variant for the Columns and Rows and this could be used for the Gaps.
A PR would be very helpful if you have time and interest.
Thank you.

**Comment by manusandoval05** [comment]
Great. I'll for sure make a PR. Should I also update the docs?

**Comment by wuda-io** [comment]
Yess please, cool Ill check it tomorrow!🖖
