### ISSUE TITLE
[Bug]: DayPicker - Month Selection not working

### ISSUE THREAD

**Issue by kenny-nt** [materializecss/materialize#412]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Month selection of daypicker is not working

### Current Behavior

Click on month selection and change to another month > select a day > Daypicker keep on back to day of current month.

### Expected behavior

Select month in month seletion then select a day must return the right value .

### Steps to reproduce

https://jsfiddle.net/SeCrEt_BoY/m50y8Lq3/8/

### Your Environment

* Version used: 2.0.2 alpha
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Additional information you want to tell us:

**Comment by wuda-io** [comment]
Thats correct! Thanks, such fine details sometimes are overseen.
Are you interested in providing a relevant PR?

**Comment by Lord-Leonard** [comment]
Hey, 
the same error occurs when selecting the Year.

**Comment by abhigyanghosh30** [comment]
> Thats correct! Thanks, such fine details sometimes are overseen. Are you interested in providing a relevant PR?

Hi,
I see this issue is still open and I'm interested in fixing it. Working on a PR for it

**Comment by abhigyanghosh30** [comment]
@kenny-nt  @wuda-io Just to confirm that I am fixing the correct issue. The bug is that when you change the month or year in the dropdown, it does not actually change the month or year in the shown calendar. Is my understanding correct?
