### ISSUE TITLE
doc: images not found component Carousel

### ISSUE THREAD

**Issue by roiLeo** [materializecss/materialize#42]
## Current Behavior
On Carousel documentation page, the images are no longer available.

![Carousel - Materialize](https://user-images.githubusercontent.com/9987732/96102068-611cce00-0ed6-11eb-9967-f3a490f5bc7f.png)

**Comment by Smankusors** [comment]
lorempixel.com seems temporarily down... let's wait at least... 1 week?

**Comment by DanielRuf** [comment]
We should switch to another service if there are better alternatives or self-host the files.

**Comment by nekonenene** [comment]
@roiLeo 
Thank you for reporting! This problem seems to continue, so I created PR #45 .
