### ISSUE TITLE
[Bug]: Slider

### ISSUE THREAD

**Issue by baccarg** [materializecss/materialize#433]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Slider not work in 2.0.3

Im cant found the media tab in website (direct link works: https://materializeweb.com/media.html but search dont found this, only show https://materializeweb.com/media-css.html)

Slider initialize, but when change image get a white image and console error: 
Uncaught TypeError: can't access property "style", e is null [materialize.min.js:6:129084]

### Your Environment

* Version used: 2.0.3
* Browser Name and version: firefox
* Operating System and version (desktop or mobile): windows
* Additional information you want to tell us:

**Comment by Jerit3787** [comment]
Hi, could you give the respective code for us to replicate or make a jsfiddle link? Thanks.

**Comment by wuda-io** [comment]
Hello, I think this are 2 issues:
- [x] docs: media not found ([fixed here](https://github.com/materializecss/materialize-docs/commit/87de858287577322e56cf33b0f336f41007ab1e3))
- [ ] slider issue: needs more details as @Jerit3787 already said

**Comment by baccarg** [comment]
ok! I thought there was a problem with the slider and that's why it had been removed from the website.
Yesterday Im discard the slider and set a carousell element. Let me rewritte my code and try again. I will back with news

**Comment by wuda-io** [comment]
Ok please make a new issue if you found something.

**Comment by HenningHeinz** [comment]
I have seen this error if the content of your slider misses the caption class (for example you only show an image)

> Uncaught TypeError: can't access property "style", e is null [materialize.min.js

To work around this just add an empty caption tag like 
`<div class="caption"></div`
