### ISSUE TITLE
Using as modular components

### ISSUE THREAD

**Issue by ChildishGiant** [materializecss/materialize#44]
There's been a long-standing issue when trying to import parts of materialize individually (https://github.com/Dogfalo/materialize/issues/5958) and from what others are saying it should be a fairly easy fix. Any thoughts?

**Comment by Smankusors** [comment]
pardon me, but how is it "fairly easy fix"? 🤔 

is that.... every js file needs to have it's own import even though it's already imported by the parent?

**Comment by ChildishGiant** [comment]
The only issue is with component.js and people in the linked thread have made forks that fix this (from the looks of things)

**Comment by DanielRuf** [comment]
That would be very good if users can import the pieces they only need.

**Comment by ChildishGiant** [comment]
It's pretty much already there, there's just an issue with the component file. There's workarounds in the linked thread but those shouldn't be needed

**Comment by DanielRuf** [comment]
> It's pretty much already there, there's just an issue with the component file.

That's what I meant, would be good to have this resolved so they can use this feature without any issues. So I guess it is a bugfix then or did it prevent the usage of the imports at all and it's a new feature?

**Comment by ChildishGiant** [comment]
I've been using them as modules for a while but it was never intentionally supported to my knowledge, just a side effect of the structure.

**Comment by LoganTann** [comment]
Added to 2.0 milestone as it is not worth the time for a v1 update

**Comment by wuda-io** [comment]
I think this can be marked as solved due to the usage of typescript. Wdyt @danice ?

**Comment by danice** [comment]
I agree. The original request was about the difficulty of finding component dependencies and this is explicit now.
