### ISSUE TITLE
[Bug]: Autocomplete size ist not correct sometimes

### ISSUE THREAD

**Issue by lschwend** [materializecss/materialize#441]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Unfortunately I don't have a test case for this, but I sometimes have the problem that the autocomplete field doesn't have the correct width (see screenshot). Can someone confirm that they've noticed this too?

![image](https://github.com/materializecss/materialize/assets/50238981/65bd84eb-a8f4-4226-9b52-25c87eb370a4)

### Your Environment

* Version used: 2.03 beta
* Browser Name and version: Chrome Version 119.0.6045.200
* Operating System and version (desktop or mobile): Windows 10 desktop
* Additional information you want to tell us:

**Comment by wuda-io** [comment]
I think you can fix this with the dropdown options. And there you can set *constrainWidth* to true.
The default is true normally. If this occours sporadic, then I dont know what is the cause.
Thanks for pointing it out... Maybe we will find the answer.

**Comment by gselderslaghs** [comment]
This works as expected in current v2.1.1
