### ISSUE TITLE
Difference Slider and Carousel?

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#442]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

I dont see any big differences in this two components.
I suggest to merge the two into one component.
[Slider](https://materializeweb.com/media.html#slider)
[Carousel](https://materializeweb.com/carousel.html#slider)

What do you guys think?

### Current Behavior

Slider and Carousel are basically the same

### Expected behavior

One Component

### Possible Solutions or Causes

Merge the two into one with the best code of both components.

### Your Environment

* Version used: 2.0.3-beta
* Browser Name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu
* Additional information you want to tell us:

**Comment by danice** [comment]
Doing some quick testing it seems Carousel behaves much better for mobile that Slider.

After quick checking the only functionality of Slider that is missing in Carousel seems to be the Fullscreen Slider.

**Comment by wuda-io** [comment]
Yes thats true and we should merge the components into one component with the features combined.
Because they are both called **Slider** and I often wonder, which one is meant.
So this would clear things up. Wdyt?

**Comment by danice** [comment]
About this, also note that Slider is used in [M3 specification](https://m3.material.io/components/sliders/overview) as the component that we call [Range](https://materializeweb.com/range.html). 

This would be another argument in favor of removing current slider component.

Not sure if is a good idea to rename Range to Slider following M3 or it would cause confusion.

**Comment by wuda-io** [comment]
We could keep the old names as undocumented names and use new names in the docs to ensure backwards compatibility.

**Comment by wuda-io** [comment]
We can use the name Carousel for the merged component then.
