### ISSUE TITLE
[Bug]: Textarea not autoresize

### ISSUE THREAD

**Issue by baccarg** [materializecss/materialize#446]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Textarea input not resize when add a line break.

### Your Environment

* Version used: 2.0.3 alpha
* Browser Name and version: firefox / chrome
* Operating System and version (desktop or mobile): Win11
* Additional information you want to tell us:

**Comment by tkoschnick** [comment]
I was able to solve this by explicitly initialising each text area:

```
document.querySelectorAll('.materialize-textarea').forEach(function(element){
    M.Forms.InitTextarea(element);
});
```

**Comment by kenny-nt** [comment]
Current version 2.0.3: textarea still do not resize when enter a long text or enter line break...

**Comment by kenny-nt** [comment]
> I was able to solve this by explicitly initialising each text area:
> 
> ```
> document.querySelectorAll('.materialize-textarea').forEach(function(element){
>     M.Forms.InitTextarea(element);
> });
> ```

Document do not mention about init textarea for autoresize when enter long text which must be default for textarea :|

**Comment by attid** [comment]
![изображение](https://github.com/materializecss/materialize/assets/93135385/07f5b6f2-91aa-4254-a41a-e81d1a477e71)
it also dont work at docs
