### ISSUE TITLE
[Bug]: Materialize Select auto scroll to top on Safari

### ISSUE THREAD

**Issue by teknosains** [materializecss/materialize#447]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Im Using Select component, when user click the options (On Change effect) on Safari, the page auto scroll to the top

### Current Behavior

Click / Change Select component on Safari trigger the page to auto scroll to the top

### Expected behavior

When clicking an Option on Safari, web page stay on current position

### Your Environment

* Version used: 1.0.0
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): Ios, Safari
* Additional information you want to tell us:

**Comment by wuda-io** [comment]
Can you try this with the newest version 2.0.3 or at least try 1.2.2.
If it still exists then please reopen again.

**Comment by teknosains** [comment]
Tested version 2.0.3 on Safari. Its now working as expected
