### ISSUE TITLE
[Bug]: Autocomplete issues

### ISSUE THREAD

**Issue by eschneor** [materializecss/materialize#454]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

I want to use the Autocomplete element, I did all the steps from the docs but still don't get it work, what am I missing?

### Current Behavior

The auto complete is not styled and the options are not exists.

### Expected behavior

Autocomplete works and looks good.

### Steps to reproduce

https://jsfiddle.net/fp2cr3so/8/

### Your Environment

* Version used:
* Browser Name and version: Chrome 121 on Windows 10
* Operating System and version (desktop or mobile): desktop
* Additional information you want to tell us:

**Comment by Jerit3787** [comment]
The one you're using is from outdated document. Please use the latest version of materialize and refer latest docs for method of usage. https://materializeweb.com/autocomplete.html
