### ISSUE TITLE
[Bug]: Failed to resolve entry for package "@materializecss/materialize

### ISSUE THREAD

**Issue by axelf** [materializecss/materialize#455]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Hi,
i want to use materialize in a laravel / vite project.

### Current Behavior

After importing the package in my app.js
`import { Sidenav } from '@materializecss/materialize';`

i got this message:
`Failed to resolve entry for package "@materializecss/materialize". The package may have incorrect main/module/exports specified in its package.json.`

### Expected behavior

Import this module without error messages

### Your Environment

* Version used: 2.0.3
* Browser Name and version: Firefox 122
* Operating System and version (desktop or mobile): macOS Sonoma 14.2.1
* Additional information you want to tell us:

**Comment by danice** [comment]
Hello, 
[Materialize-docs](https://github.com/materializecss/materialize-docs) is an example of using materialize from a vite project. Can you provide an example project to test this issue?

Thanks!

**Comment by axelf** [comment]
HI,

i have no project i can show you. But i replaced this lib with the old lib of materialize: https://www.npmjs.com/package/materialize-css and it is working. Perhaps you can deduce an error. If not, I would have to set up a new project first, which I can share publicly

`import 'materialize-css';`

I think the project here is much newer and would like to use it.

**Comment by axelf** [comment]
This is working: `import { M } from "@materializecss/materialize/dist/js/materialize.js";` 
This is the path of the main entry of the package json. 
But why is`import { M } from "@materializecss/materialize";` not working?

**Comment by danice** [comment]
it's because the package has also this entry that takes preference in the import:
`  "module": "src/index.ts",`

I think we should replace "src/index.ts" here by the ".d.ts" that your comment says. But we should check that it keeps the library working when used from webpack and as a workspace (as we did in materialize-docs).
