### ISSUE TITLE
NPM Package has outdated readme.md with old repo link

### ISSUE THREAD

**Issue by samschurter** [materializecss/materialize#47]
## Expected Behavior
The NPM page for the maintained fork should point to the correct fork
https://www.npmjs.com/package/@materializecss/materialize
## Current Behavior

There are many links that still point to the old repo, and the stats on issues and PRs is from the old repo

## Possible Solution
I don't know anything about the process of publishing to npm, but I'm assuming that the version there is the 1.0.0 release and doesn't include any of the changes made since the fork. I think at the very least the readme changes should be pushed to 1.0.0 of materializecss/materialize to make sure npm is pointing to the correct fork. Those stats on open PRs and issues look bad, and some users might go to the old repo and leave without realizing there is an actively maintained fork. 

## Steps to Reproduce (for bugs)

1. visit https://www.npmjs.com/package/@materializecss/materialize

**Comment by ChildishGiant** [comment]
See #26

**Comment by samschurter** [comment]
Sorry, didn't check closed issues. Makes sense to me as long as we can get something out soon. 
I'm working on some dropdown/autocomplete bugs.
