### ISSUE TITLE
[Bug]: Modal with Fixed Footer Always has Scrollbar

### ISSUE THREAD

**Issue by mpiggott** [materializecss/materialize#477]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

It appears the modal with fixed-footer is a pixel or two too large which results in a scrollbar always being present on the page. This is present even on the materializeweb site example.

### Current Behavior

There is always a scrollbar even if the content does not overflow the modal.

### Expected behavior

I'd expect a scrollbar to only be visible if the content overflows. 

### Steps to reproduce

1. https://materializeweb.com/modals.html
2. Scroll to Modals with Fixed Footer
3. Click button :)

### Your Environment

* Version used: 2.0.4
* Browser Name and version: 124.0.6367.119
* Operating System and version (desktop or mobile): Windows 10
* Additional information you want to tell us:

**Comment by wuda-io** [comment]
Hello, thanks for reporting.
This is due to the top border of the footer.
