### ISSUE TITLE
[Bug]: Tonal button seems not presenting

### ISSUE THREAD

**Issue by luckycatx** [materializecss/materialize#478]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Tonal buttons behave exactly the same as standard buttons
![image](https://github.com/materializecss/materialize/assets/15809204/380b5068-1963-4c16-8d08-4a2e4eb12daf)

### Current Behavior

Tonal class has no effect on the button but on official website it functions normally

### Expected behavior

Funcitons like offcial website

### Your Environment

* Version used: materialize@2.0.3-alpha
* Browser Name and version: Google Chrome 125.0.6422.113
* Operating System and version (desktop or mobile): desktop
* Additional information you want to tell us:

**Comment by Jerit3787** [comment]
This issue is not present on version 2.0.4. Please use Materialize version 2.0.4 instead. Thanks! 

p/s: refer this jsfiddle https://jsfiddle.net/j6zvx4rh/5/
