### ISSUE TITLE
Marquee Component

### ISSUE THREAD

**Issue by Kam3leoN** [materializecss/materialize#482]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Je voudrais mettre en place un marquee, je pourrais le faire de manière simple en CSS.
Mais j'aimerai qu'il soit possible de le faire via un component MaterializeCSS comme d'autre components.

### Current Behavior

aucun marquee

### Expected behavior

marque a développer éventuellement
J'ai commencé une base comme les autres component mais je ne connais pas le typescript j'ai pris la base de 1.0.0

### Possible Solutions or Causes

`(function($, anim) {
  'use strict';

  let _defaults = {
    width:'auto',					//Sets width of the Marquee.
    height:'auto',					//Sets height of the Marquee.
    direction:'left',				//Sets the direction of the Marquee. //It may take the values: "left", "right", "top", "bottom"
    scrollDelay:85,					//Sets the interval between each scroll movement in milliseconds. //The default value is 85. //Note that any value smaller than 60 is ignored and the value 60 is used instead, unless truespeed is specified.
    scrollAmount:6,					//Sets the amount of scrolling at each interval in pixels. //The default value is 6.
    circular:false,					//Creates the effect of an infinite line.//It may take the values: true, false
    dragAndDrop:true,				//Enable the opportunity to drag the Marquee by the mouse. //It may take the values: true, false
    hoverStop:true,					//Enable the opportunity to pause the Marquee when mouse hover. //It may take the values: true, false
    scrollStop:true,				//Enable the opportunity to pause the Marquee when scroll page. //It may take the values: true, false
    startShow:false,				//If it is true - the content of marquee appears immediately if the lie - gradually	
    xml:false,						//Path to XML file or false
    touchEvent:true,				//This parameter determines if the ticker responds to touch events or not //It may take the values: true or false
    stopOutScreen: true,			//This parameter specifies, the ticker will stop outside the screen or not //It may take the values: true or false
    create:null,			//Triggered when the liMarquee is created.
    moveStart:null,			//Triggered when motion starts.
    moveStop:null,			//Triggered when motion stops.
  };

  /**
   * @class
   *
   */
  class Marquee extends Component {
    /**
     * Construct Slider instance and set up overlay
     * @constructor
     * @param {Element} el
     * @param {Object} options
     */
    constructor(el, options) {
      super(Marquee, el, options);

      this.el.M_Marquee = this;
      this.options = $.extend({}, Marquee.defaults, options);

      this.lastWindowWidth = window.innerWidth;
      this.lastWindowHeight = window.innerHeight;
      // this.caption = this.el.getAttribute('data-caption') || '';

      this._setupMarquee();
    }

    static get defaults() {
      return _defaults;
    }

    static init(els, options) {
      return super.init(this, els, options);
    }

    static getInstance(el) {
      let domElem = !!el.jquery ? el[0] : el;
      return domElem.M_Marquee;
    }

    /**
     * Teardown component
     */
    destroy() {
      this._removeEventHandlers();
      this.el.M_Marquee = undefined;
      this.el.style.transform = '';
    }

    _setupMarquee() {
      //Code
    }

  }

  M.Marquee = Marquee;

  if (M.jQueryLoaded) {
    M.initializeJqueryWrapper(Marquee, 'marquee', 'M_Marquee');
  }
})(cash, M.anime);`

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Additional information you want to tell us:

**Comment by wuda-io** [comment]
Hello @Kam3leoN
Please write the issue in english again.
This will be closed for now. thanks
