### ISSUE TITLE
[Bug]: scrollbar appears with modal in 2.1.0

### ISSUE THREAD

**Issue by OlivierMadant** [materializecss/materialize#484]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

The vertical scrollbar appears on the right  when using modal

![image](https://github.com/materializecss/materialize/assets/17064775/7a95ace9-d599-45d8-bda4-d401c1fc333f)

### Expected behavior

no scrollbar

### Possible Solutions or Causes

I think the bug is due to the code : 

       html.noscroll {
                  position: fixed;
                  overflow-y: scroll;
                  width: 100%
                   }

in https://github.com/materializecss/materialize/blob/main/sass/components/_global.scss  line 118

I think the code should be replaced by: 

       html.noscroll {
                  position: fixed;
                  overflow-y: hidden;
                  width: 100%
                   }

to remove the scrollbar:

![image](https://github.com/materializecss/materialize/assets/17064775/8d98c34b-f6e4-42b0-8f4f-f006e6602f89)

### Steps to reproduce

1.Open the link : https://materializeweb.com/modals.html
2. open a  Modal 

### Your Environment

* Version used: Release 2.1.0

**Comment by OlivierMadant** [comment]
I can prepare a PR if the diagnosis and solution are correct

**Comment by wuda-io** [comment]
Hello @OlivierMadant 
This is intendent behavior. Because before the page content was jumping if a modal is opened. It only appears when there already is a scrollbar.

**Comment by OlivierMadant** [comment]
Hello @wuda-io ,
Thank you for your quick reply and great work.
