### ISSUE TITLE
discussion: needed labels

### ISSUE THREAD

**Issue by DanielRuf** [materializecss/materialize#5]
What labels are you missing? Which ones do we need and which colors would you recommend?

@materializecss/members

**Comment by occirol** [comment]
Maybe we can "create" 3 types of labels : type, status and priority
I would propose:

**Type labels**

- _Type: Bug_ (color #f44336)
- _Type: Enhancement_ (color #2196f3)
- _Type: Question_ (color #9c27b0)

**Status labels**

- _Status: Pending_ (color #607d8b)
- _Status: In progress_ (color #009688)
- _Status: Blocked_ (color #ff5722)
- _Status: Review needed_ (color #ffc107)
- _Status: Completed_ (color #4caf50)
- _Status: Abandoned_ (color #212121)

**Priority labels**

- _Priority: Low_ (color #4caf50)
- _Priority: Medium_ (color #ffeb3b)
- _Priority: High_ (color #ff5722)
- _Priority: Critical_ (color #f44336)

**Comment by DanielRuf** [comment]
in general: this is a bit too verbose and status is covered by the project status (in progress, ..., done).

Type should be covered by issue templates, title and the existing labels.

Not sure about priority, we have to check what each priority means then to see if this would be helpful. For this we can also use a project board maybe like we do for webpack.

I thought about labels per component, code type (js, scss), scope (doc, build, test, feature, fix, ...), similar to several commit rules. So we and users can easily filter by these and find relevant issues and PRs. This is more user-focused than some priority or status label as from my experience they will still ask when things will get fixed and released (assign milestones).

**Comment by DanielRuf** [comment]
In general: this is a bit too verbose and status is covered by the assigned project status board (in progress, ..., done).

Type should be covered by issue templates, title and the existing labels.

Not sure about priority, we have to check what each priority means then to see if this would be helpful. For this we can also use a project board maybe like we do for webpack.

I thought about labels per component, code type (js, scss), scope (doc, build, test, feature, fix, ...), similar to several commit rules. So we and users can easily filter by these and find relevant issues and PRs. This is more user-focused than some priority or status label as from my experience they will still ask when things will get fixed and released (assign milestones).

**Comment by occirol** [comment]
I like the idea of labels per component, code type and scope.

As for the status, yes it is covered by the assigned project status board (maybe we should define some more or different status there) but when you are consulting the issue, I find it difficult in one look to see it's status. That's why I proposed a status label.

Same for issue's prioritization. While you can prioritize issues in the project board, I find it helpful to have a prioritization label. It improves readability (as many people will not consult the project board at all).

**Comment by DanielRuf** [comment]
I think we need labels by component so we can filter by them when we work on a component.

What do you think @materializecss/members?

**Comment by doughballs** [comment]
So each component gets its own coloured label?

**Comment by DanielRuf** [comment]
> So each component gets its own coloured label?

Probably the same color (some grey?) for components.

**Comment by nicknickel** [comment]
My two cents would be that labels by component would help for sure.

**Comment by doughballs** [comment]
Agreed, sounds like it would be very useful!

**Comment by Pierstoval** [comment]
Agreed, especially for grey for every component 👍

**Comment by DanielRuf** [comment]
I have created a few labels for existing issues and PRs. Feel free to recommend more in the relevant issues and PRs.

Users with write access (currently @Smankusors) should be able to create new ones.
