### ISSUE TITLE
[Bug]: Collapsible can't be nested - Worked in 1.0.0

### ISSUE THREAD

**Issue by KajKandler** [materializecss/materialize#501]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Set up a nested collapsible like in https://github.com/KajKandler/ce-sidepanel-colapsible-test/blob/main/sidepanel.html

### Current Behavior

When opening the Collapsible "2." and some of its siblings "2.1" ... The collapsible body does not expand to contain the larger height elements.

### Expected behavior

The box expands and pushes down the rest of the content

### Possible Solutions or Causes

I did not compare the code between the versions or triaged which version introduced the bug.

### Steps to reproduce

What steps will reproduce the problem?
(1) Checkout the project at https://github.com/KajKandler/ce-sidepanel-colapsible-test
(2) Open the sidepanel.html with a live server (Visual Code)
(3) Open "2."; Then "2.1.", then "2.2."
(4) Close and re-open "2."

### Your Environment

* Version used: 2.1.0
* Browser Name and version: Chrome 128.0.6613.115 (Official Build) (arm64) 
* Operating System and version (desktop or mobile): MacOS 14.16.1 desktop
* Additional information you want to tell us:

**Comment by gselderslaghs** [comment]
This does not seem to be a bug as the current Collapsible component follows the Material M3 guidelines where only single-item lists are allowed, this would be a implementation out of scope

As a result I would recommend implementing a custom solution for your issue
