### ISSUE TITLE
Programmatically triggered Wave Effects

### ISSUE THREAD

**Issue by ryanrapini** [materializecss/materialize#51]
https://github.com/Dogfalo/materialize/issues/3193

Would like to take this on, will work on it and send pull request unless anyone has any objections? Looks like at a cursory glance this may involve removing the wave library and either updating or replacing it.

**Comment by wuda-io** [comment]
Yes I like that Idea. Especially nice for Call to Action Buttons. But why would it be necessary to remove the Library? Better would be to update or enhance the library. What do you think? Best regards

**Comment by ryanrapini** [comment]
Just basing it on the discussion they were having in that thread.
