### ISSUE TITLE
datepicker does not support date range neither a method to change Min/Max Date

### ISSUE THREAD

**Issue by ruitalia** [materializecss/materialize#56]
datepicker does not support the feature to select a range between two dates.

In the previous version (pickadate plug in) it works better than this all new writen datepicker plugin.

It does not even have a Method to change the initial options, and, for examaple, to change the MinDate and MaxDate options on change the start/end date input fields.

Also the possibility of pick only months isnt possible.

Thanks

**Comment by wuda-io** [comment]
Yes there is something wrong with the Library... if I try to use Dropdown, it does not work anymore either!
I think we started from an old or outdated Version!
