### ISSUE TITLE
Dropdown wrong item click on ios14 (only when closeOnClick is true)

### ISSUE THREAD

**Issue by nipmarsh** [materializecss/materialize#58]
When clicking on a dropdown item on ios14, the wrong one is clicked.
I set the timeouts to 200 in _handleDocumentClick for a test and this solve the problem

**Comment by ChildishGiant** [comment]
Is this not a duplicate of #31?

**Comment by Smankusors** [comment]
> Isn't this a duplicate of #31?

hmm... yeah there's similiarity with that. Except with different solution, @nipmarsh using timeout, while @nekonenene using ontouchend

**Comment by nipmarsh** [comment]
@ChildishGiant yes indeed this seems to be

**Comment by wuda-io** [comment]
https://github.com/materializecss/materialize/pull/195
