### ISSUE TITLE
loading data on FormSelect

### ISSUE THREAD

**Issue by danielemontesi** [materializecss/materialize#66]
How can I clear all FormSelect options and add new?
If I use browser-default class it works, but if I don't put it it doesn't work

```
<select name="my_select" id="my_select">
<option value="" disabled></option>
</select>

<script>
....
var results = data.data;

var select = document.getElementById('my_select');
// Clear previous options
var length = select.options.length;
for (i = length-1; i >= 0; i--) {
  select.options[i] = null;
}

for (var i = 0; i < results.length; i++) {
  var item = data.data[i];
  var option = document.createElement('option');
  option.text = item.name;
  option.value = item.id;
  select.add(option, i);
}
</script>
```

**Comment by roiLeo** [comment]
Have you tried to [Initialize](https://materializecss.com/select.html#initialization) the component after you've put data in ?

**Comment by danielemontesi** [comment]
@roiLeo yes, no effects

**Comment by ChildishGiant** [comment]
Could you make a minimum reproduction codepen? Here's a template with materialize already included: https://codepen.io/pen?template=MRNObV

**Comment by danielemontesi** [comment]
@ChildishGiant
Codeopen url: https://codepen.io/danielemontesi/pen/jOVPxmX
It works, but if you remove **browser-default** class to **select_2** it does not works more

**Comment by Smankusors** [comment]
> @roiLeo yes, no effects

no you don't. Viewing your given codepen, you did initialize **before** you've put data in.

Every time you add or remove options on the select, you need to "re-initialize" the select after that.

**Comment by roiLeo** [comment]
As written in documentation you have to initialize select component each time you change data.
In your case you should put after the 'for' loop:
```javascript
M.FormSelect.init(select, options);
```

**Comment by danielemontesi** [comment]
Thanks to all
