### ISSUE TITLE
Host new page for updated docs?

### ISSUE THREAD

**Issue by aramodi** [materializecss/materialize#71]
Possibly something like materializecss.js.org ?

**Comment by wuda-io** [comment]
Yes, totally agree. We should ensure there is not a single point of failure in the Management of the Domain. Who controlls the domain?
The hosting itself could be done by github Pages.

**Comment by aramodi** [comment]
js.org is reliable. It's controlled by https://github.com/js-org/js.org

**Comment by wuda-io** [comment]
Ok yes, sounds good to me.
What are the you guys thinking?
Greets

**Comment by Smankusors** [comment]
Hmm I'm alright about this... But there will be possible confusion with materializecss.com and materialize.js.org

cc @DanielRuf

**Comment by DanielRuf** [comment]
> Possibly something like materializecss.js.org ?

See the described steps at https://github.com/js-org/js.org/tree/master

**Comment by DanielRuf** [comment]
> Hmm I'm alright about this... But there will be possible confusion with materializecss.com and materialize.js.org

At least there is no materialize.js.org

**Comment by aramodi** [comment]
> > Possibly something like materializecss.js.org ?
> 
> See the described steps at https://github.com/js-org/js.org/tree/master

Yeah, I read it but I thought they would still accept materializecss since it also uses JS.

**Comment by drusepth** [comment]
Did anyone reach out to them?

Looks like they're clamping down on requests. From [their README](https://github.com/js-org/js.org/commit/cab250acc595795d268fbc371ee1421ba779ff1e#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5):

>***Due to the increased number of requests for js.org subdomains recently, with many having questionable relevancy to the JavaScript community and ecosystem, we've decided that going forward js.org will be focusing on accepting subdomain requests from projects with a clear relation to the JS community.***

**Comment by aramodi** [comment]
@drusepth I have already read this. MaterializeCSS has a clear relationship to JS, doesn't it?

**Comment by drusepth** [comment]
Depends on how they're defining a "clear relationship" to the "JS community", I guess. (I'd say yes, of course.) 

Was just wondering if anyone had reached out (and therefore prompted an actual answer) or if the conversation was stalled on us just wondering what they would say.

Carry on!

**Comment by DanielRuf** [comment]
> Did anyone reach out to them?

Not that I am aware of. Feel free to do so.

**Comment by wuda-io** [comment]
Any updates on this? greets

**Comment by wuda-io** [comment]
Can we set up Github Pages for the first step? @DanielRuf 
[https://pages.github.com/](https://pages.github.com/)

**Comment by DanielRuf** [comment]
@wuda-io it seems the gh-pages branch is outdated. Should we setup this one for the new GitHub Pages?

Afaik we have to compile the documentation.

**Comment by ChildishGiant** [comment]
Github actions could be setup to compile the docs and publish to gh pages

**Comment by wuda-io** [comment]
Yes this would be awesome. I am not so familiar with GH Actions. Can someone implement this? Who implemented the tests?

**Comment by ChildishGiant** [comment]
> Who implemented the tests?

Me 😇 I'll have a look at implementing this and making a PR in the next few days.
