### ISSUE TITLE
Is this the official MaterializeCSS repo from now on?

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#74]
I was looking on the original materializecss and that had issues piling up and it looked abandoned, I was wondering if this is now the official materializecss repo from now on?

if so should we bring the issues from the other repo here?

**Comment by Smankusors** [comment]
Hmm I would say this repo is not really official, but more to community support. As we didn't own the materializecss.com domain. Read more about it on https://github.com/Dogfalo/materialize/issues/6438 and #2.

**Comment by wuda-io** [comment]
We are currently working to get the Hosting and Domain running... Every contribution counts and is very welcome. Thanks.
