### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#77]
Any chance we can get dark mode for the framework?

**Comment by ChildishGiant** [comment]
Would this be a css class given to the body or implemented in JS? How do you see this being implemented?

**Comment by nh916** [comment]
I think there needs to be a JS toggle/switch/button/ or something else that the user interacts with that switches the UI to dark theme. The switch should be easily customizable depending on different websites, so that way every website that is implementing the button/switch/toggle can have something that fits their website theme and doesn't look all the exact same. The html for it should also be syntactically valid for good SEO and accessibility.

I think the change to the dark mode needs to happen on the JS side. The thing to keep in mind with that is that the contrast must still be there in case the developer is using dark gray on white, if we just change the body to black then we no longer have any contrast so we have to also change the brights so they can continue to have good contrast.

Contrast is something that is very important to accessibility and people who have color blindness or just hard of seeing. If we can plan for good accessibility by color blind people here from the start that is all the better, that way our contrast and our accessibility is planned in from the beginning and materializecss gives us perfect UI, UX, accessibility, and as a result good SEO for everyone by just using it. You then have to try to mess it up for it to not go perfectly. 

I think if we can also allow developers to override the default dark color to one that they like that would all the better so each website can make their dark mode a bit more custom, so some websites dark mode will be black, others dark navy, others dark gray, etc. I think that would make our framework very flexible and nice to work with but perfect as the default that developers can put something together quick and it just comes out perfectly from UI and UX and easy to add to websites.

**Comment by bugy** [comment]
Just a note: 
I'm using materialize-css and I added such a possibility in my project, using css variables. 
For it, I redefined materializecss scss color variables with css variables (see the second half of the file): https://github.com/bugy/script-server/blob/master/web-src/src/assets/css/color_variables.scss

This gives me the opportunity to change the variables in runtime (at least after the compilation).

I'm not sure if this is the best way to solve it, but analyzing all the alternatives I found this way is the clearest and modern. For the old browsers support (aka IE11), there is a polyfill available.

Unfortunately, this doesn't work with the current version of materializecss (not all scss variables are overridable), so I submitted a PR for it #85

**Comment by DanielRuf** [comment]
Do you want to champion / lead this as one of the big new features @bugy? That would be great. How can we move forward with the PR? How can the other org members help here?

**Comment by bugy** [comment]
Hi @DanielRuf sure, I can do it if you are fine with the suggested approach using css variables. 
If it's ok, I can work on some prototype and submit a draft PR for it, so we can discuss it in more detail on a real example.

The main help which I would need there is your feedback :)

**Comment by DanielRuf** [comment]
@materializecss/members what do the others think?

Please upvote https://github.com/materializecss/materialize/issues/77#issuecomment-806493788 if you think that the CSS variables approach is the way to go.

**Comment by christinavoudouris** [comment]
I think the variables approach is a good one. There are a few different ways to implement dark mode, and I'm not crazy about the 2 stylesheets idea (I think it can be a bit slow or cause a flash, from what I've seen). Also I'm we probably need something more complex than just toggling the body class with Javascript. 

Here is some good documentation on dark mode from CSS tricks if anyone is curious - https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#toggling-themes

**Comment by ChildishGiant** [comment]
That would fully drop support for IE though: https://caniuse.com/css-variables

**Comment by DanielRuf** [comment]
We can probably compile them to normal CSS (two static css files and one with CSS variables). Would this be an option?

**Comment by DanielRuf** [comment]
Besides this, even Bootstrap 5 dropped IE11 support: https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/

**Comment by DanielRuf** [comment]
We can probably compile them to normal CSS (two static css files and one with CSS variables). Would this be an option?

Besides this, even Bootstrap 5 dropped IE11 support: https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/

And there are polyfills for CSS variables: https://stackoverflow.com/questions/46429937/ie11-does-a-polyfill-script-exist-for-css-variables

**Comment by DanielRuf** [comment]
We can probably compile them to normal CSS (two static css files and one with CSS variables). Would this be an option?

Besides this, even Bootstrap 5 dropped IE11 support: https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/

And there are polyfills for CSS variables:
https://stackoverflow.com/questions/46429937/ie11-does-a-polyfill-script-exist-for-css-variables
https://github.com/nuxodin/ie11CustomProperties
https://github.com/aaronbarker/css-variables-polyfill

**Comment by doughballs** [comment]
The startup theme kind of has this facility. A single body class - light theme, dark theme, should be enough without any flash. Every component would need looking at though, as it a a big task to get this working without throwing a load of !important flags in. Not a fan of css variables mainly because I don’t use them and I write in sass, which suits the current setup of being written in sass.

**Comment by bugy** [comment]
I suggested css variables over a body classes for 2 main reasons:
- it would be easier for users to overwrite default colors when needed, especially dynamically
- it shouldn't affect selectors priority for users, e.g. if user has `.my-project.button` style, we'll overwrite it by `html.dark button`

This might be not do important though

**Comment by christinavoudouris** [comment]
It sounds like either CSS approach could work if done right. I had set up a small project with separate stylesheets but I didn't use !important, just reused a dark-mode class over and over. Maybe not the best way to do it....

Either way I really like the idea of also using a media query to grab the user's settings. I think people would like a button to toggle but as dark mode gains more traction, more people will set their own defaults. It was called gimmicky by some people but as someone who's a night owl, I love dark mode.

**Comment by doughballs** [comment]
Fair point about selectors. Maybe we need to spin up some demos of how the variable method would work then. The IE support is not an issue for me. It’s dead in the water. I do still accomodate it, but a progressive enhancement like dark mode is fine to just ignore IE I think. Honestly, if anyone is using IE they’re probably won’t be flicking dark mode switches 😂

**Comment by nh916** [comment]
I agree we can probably drop support for IE and be fine. We can support the very basic things for IE so it looks good on IE but not the best it can be. 
IE is really not worth supporting, unless if it somehow affects SEO or accessibility, and I don't think that it would be a problem with dark mode, but I am not 100% sure.

I think the first draft is the most important step here because once we have the first step we can start Alpha and Beta testing it hard and tweaking it to perfection. However, if we have a great design philosophy behind it from the beginning, so that we have a clean, easily maintainable, and scalable code then all the better and it would make our framework infinitely better. 

Our framework would work better and for longer and anyone joining us can easily contribute to our code in an instance because everything is clean and designed well.

Alpha and Beta testing this feature is probably going to be HUGE to catch all the scenarios where the new feature breaks and doesn't perform well, so we can continue to tweak and fix it until perfection and then release.

**Comment by bugy** [comment]
Alright, as far as I understood, I should proceed with a prototype using variables. I will adjust several materializecss components and prepare a simple demo app. Then we can discuss the PR and decide if this is a good way to go, or we should consider something else

I will try to prepare the prototype next week, but no strict promises :)

**Comment by DanielRuf** [comment]
That sounds really great =)

**Comment by bugy** [comment]
Hi, please check the draft PR and prototype, when you have time :)
Any feedback is appreciated!

**Comment by L1ghtn1ng** [comment]
As Microsoft has finally given us a date of killing of I.E most people should really be off of it now anyway. So I say we drop I.E 11 support altogether and will allow for modern standards everywhere

**Comment by nh916** [comment]
Was this ever merged into our code base? The feature implemented was beautifully and I was wondering how I can use it in my new projects. We probably also need documentation for use of it as well! Very excited for this!

**Comment by DanielRuf** [comment]
> Was this ever merged into our code base?

I can see that there is a draft PR at the moment, which is linked in this issue here:
https://github.com/materializecss/materialize/pull/113
