### ISSUE TITLE
Add npm-asset support

### ISSUE THREAD

**Issue by DMGPage** [materializecss/materialize#80]
Could you add npm-asset support? I see there "npm-asset/materialize-css", but it's for Dogfalo/materialize. Then there is "npm-asset/materializecss--materialize", but it's again points to Dogfalo/materialize. This repository I can't find there.

**Comment by Smankusors** [comment]
Hmm can you help us here? Can you explain what is "npm-asset"? How we can do to accomplish this?

**Comment by DMGPage** [comment]
> Can you explain what is "npm-asset"?

https://asset-packagist.org/

Before I could use with composer like this: "bower-asset/materialize": "1.0.0". But this repository I can't find in asset-packagist. So, I do not know, hot to add it to composer.

**Comment by Smankusors** [comment]
> This https://www.npmjs.com/package/@materializecss/materialize looks like package from this repository, but it points to github.com/Dogfalo/materialize. Maybe some links are wrong?
> 
> And why after all commits this repository version still stays at 1.0.0, which was added in 2018?

the version is still 1.0 because we haven't released any version yet from this repo

**Comment by DMGPage** [comment]
Maybe you should. Or else only option is to use dev version, which changes all the time?

**Comment by DanielRuf** [comment]
Regarding https://asset-packagist.org/, bower is dead / not actively maintained anymore (they suggest to switch to yarn or npm) and many projects based on Symfony already use a setup with these package manager.

Also see https://github.com/fxpio/foxy

https://asset-packagist.org/package/search?query=%40materializecss%2Fmaterialize&platform=npm

> npm-asset/materializecss--materialize

This is the correct one according to the link.

**Comment by DanielRuf** [comment]
So no need from our side to add / publish anything for them as they automatically pick up our versions.
