### ISSUE TITLE
Footer in documentation is not using proper/semantic html and my fix provided

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#96]
Not to be a stickler but this is something that I noticed today and I thought it could be a smaller fix.
The footer in the documentation is using h5 for the footer content without having an h1-h4. Using h5 without the previous ones just for the style of it is just improper HTML and will affect accessibility and SEO, and we can do better!

```html
<footer class="page-footer">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Footer Content</h5>
              <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul>
                <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">
          © 2014 Copyright Text
          <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
          </div>
        </div>
</footer>
```

From what I have tried is that I replaced the h5 with a p tag and added these styles to it and it looked very similar to the h5. I wasn't sure if it needed to be a span, p, or something else, so I just put it as p for now. I am sure someone here can help write better html and make it more proper.

```html
<p class="white-text" style="font-size: 1.65rem; margin-bottom: -0.3rem; margin-top: 0.7rem">Footer Content</p>
```

I was thinking since we are giving every developer something that they will probably just copy and paste, might as well give them something good!

**Comment by Smankusors** [comment]
Hmm I'm curious about how it's affecting the SEO. I mean, the footer is not the main focus of the SEO, isn't it?

**Comment by nh916** [comment]
That is a great question! Improper html tends to hinder accessibility and signals to Google that this website is not done properly and has accessible problems, and Google only wants to provide the best websites to their users that are the fastest, most recent, most relevant, most accessible, safest, and has the best UI and UX. 

Which, I think makes sense to me because search engines like Google want their users to  show the best websites that they can find to their users so they have happy users. There are many websites that may apply when the user searches for "bees", but search engines only want to show the best one so the users are happy and get websites they like.

**Comment by DanielRuf** [comment]
In most big client projects we applied the same margins and font-size values with classes like `.h5`.

`p` is not correct as this is not a paragraph per se but a heading / single line of text.

**Comment by ChildishGiant** [comment]
Linters often complain about out of order h tags but I'm yet to see any real world impacts and in my experience most people don't see this as poor form.

**Comment by DanielRuf** [comment]
Hm, what should we do here? SEO is not our main problem and not top priority.

**Comment by wuda-io** [comment]
> 
> 
> Hm, what should we do here? SEO is not our main problem and not top priority.

I dont see any issue here too.
