### ISSUE TITLE
Feature discovery moves element when activated

### ISSUE THREAD

**Issue by ChildishGiant** [materializecss/materialize#97]
https://user-images.githubusercontent.com/13716824/112652746-a6f69e80-8e45-11eb-9ddf-dc9a20da1863.mp4

The example on the docs shows this: https://materializecss.github.io/materialize/feature-discovery.html

Reproduced on both firefox and chromium (Errors on IE)

**Comment by roiLeo** [comment]
I can't reproduce it on Firefox. 
Have you tried to inspect what's happening when the tap-target is openning ?

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/113192051-34772b80-9256-11eb-8832-ca3864c65523.png)
The element is always at the incorrect location

**Comment by DanielRuf** [comment]
I wonder if this has to do with some transform origins or similar. Can you check this @ChildishGiant?

**Comment by warrenrodrigues** [comment]
The scroll bar causes this issue. If the document is short enough and doesn't have a Y-scroll bar, it works fine.

To fix this, I propose getting the width of the scrollbar and deducting it from the tap-target-wrapper width. This seems to fix it for me on Chrome (89) and Firefox (86).

Changes are required in the tapTarget.js file. I'll submit a PR.

**Comment by wuda-io** [comment]
Can this be closed?

**Comment by DanielRuf** [comment]
Thanks for the reminder. Yes this can be closed.
You should also be able to close isses @wuda-io.
